wala/WALA

com.ibm.wala.cast.js/dat/prologue.js
These were missing from prologue.js
=> Fixes to Array.prototype models

com.ibm.wala.cast.java.test/src/com/ibm/wala/cast/java/test/IRTests.java, com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/callGraph/Java7CallGraphTest.java, com.ibm.wala.core.tests/src/com/ibm/wala/examples/analysis/SimpleThreadEscapeAnalysis.java, com.ibm.wala.core/src/com/ibm/wala/classLoader/AbstractNestedJarFileModule.java, com.ibm.wala.core/src/com/ibm/wala/classLoader/ClassLoaderImpl.java, com.ibm.wala.core/src/com/ibm/wala/util/config/AnalysisScopeReader.java, com.ibm.wala.core/src/com/ibm/wala/util/io/FileProvider.java, com.ibm.wala.shrike/src/com/ibm/wala/shrikeBT/tools/OfflineInstrumenterBase.java
See <https://github.com/wala/WALA/issues/100>
=> SecurityExceptions when analyzing JARs with broken/expired signatures

com.ibm.wala.dalvik/build.xml
fix for #125 - at least for now...
=> Dexlib fix

com.ibm.wala.util/src/com/ibm/wala/util/collections/IntStack.java
Accrue (http://people.seas.harvard.edu/~chong/accrue.html) uses IntStack
internally for various things and found these convenient.
=> Add int size() and int get(int index) methods to IntStack.

com.ibm.wala.cast/build.xml, com.ibm.wala.core/src/com/ibm/wala/analysis/stackMachine/AbstractIntStackMachine.java, com.ibm.wala.core/src/com/ibm/wala/cfg/ShrikeCFG.java, com.ibm.wala.core/src/com/ibm/wala/classLoader/JarStreamModule.java, com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/impl/AbstractRootMethod.java, com.ibm.wala.core/src/com/ibm/wala/ipa/slicer/SDG.java, com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/classLoader/DexCFG.java, com.ibm.wala.util/src/com/ibm/wala/viz/DotUtil.java
This is a series of small fixes we found useful for JOANA.
=> Pull request  misc bugfixes

com.ibm.wala.core.tests/src/com/ibm/wala/examples/analysis/dataflow/NullAnalysis.java, com.ibm.wala.core.tests/src/com/ibm/wala/examples/analysis/dataflow/NullAnalysisFact.java, com.ibm.wala.core.tests/src/com/ibm/wala/examples/analysis/dataflow/NullSet.java, com.ibm.wala.core.tests/src/com/ibm/wala/examples/drivers/NullAnalysisDriver.java
This pull request contains an IFDS-based analysis for detecting null-pointer dereferences. The analysis tracks access paths that either may be null or may-not be null.
=> IFDS Null Analysis files

com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/propagation/SSAPropagationCallGraphBuilder.java, com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/classLoader/DexIMethod.java, com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/androidModel/AndroidModel.java, com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/androidModel/stubs/AndroidStartComponentTool.java, com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/propagation/cfa/IntentContextInterpreter.java, com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ssa/DexSSABuilder.java, com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/util/AndroidComponent.java, com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/util/AndroidEntryPointLocator.java, com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/util/AndroidManifestXMLReader.java, com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/util/AndroidSettingFactory.java, com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/util/androidEntryPoints/ActivityEP.java
This is a series of small patches for the dalvik/android support in WALA.
=> Pull request  android bugfixes

com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/impl/Util.java, com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/propagation/cfa/ZeroXContainerCFABuilder.java, com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/propagation/rta/AbstractRTABuilder.java, com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/propagation/rta/BasicRTABuilder.java
Other places where IAnalysisCacheView can be used. May not be inclusive.
=> Additional refactorings for IAnalysisCacheView.

com.ibm.wala.ide.jsdt/source/com/ibm/wala/ide/util/JsdtUtil.java
Based on what this code seems to be doing, there's really no officially-sanctioned alternative to the APIs we're using here.
=> Suppress 14 Eclipse warnings about discouraged access to restricted APIs

com.ibm.wala.cast.java.ecj/src/com/ibm/wala/cast/java/translator/jdt/JDTJava2CAstTranslator.java, com.ibm.wala.cast.java.test.data/src/bugfixes/DoWhileInCase.java, com.ibm.wala.cast.java.test/src/com/ibm/wala/cast/java/test/JavaIRTests.java
=> When converting JDT AST to IR, a do-while loop in a case statement will throw NPE

com.ibm.wala.core/src/com/ibm/wala/analysis/typeInference/TypeInference.java
Update to https://github.com/wala/WALA/pull/228.
=> Minor performance improvements to methods in TypeInference class

com.ibm.wala.dalvik/.classpath
=> remove unneeded .classpath entry

com.ibm.wala.ide/src/com/ibm/wala/ide/client/EclipseProjectAnalysisEngine.java
=> This is implicit.

com.ibm.wala.core/src/com/ibm/wala/util/strings/Atom.java
Fix https://github.com/wala/WALA/issues/273.
=> Fix Atom.startsWith() failure case.

.gitignore, .idea/.gitignore, .idea/.name, .idea/misc.xml, .idea/vcs.xml, gradle/wrapper/gradle-wrapper.properties
These are a few minor tweaks to improve handling of WALA as an IntelliJ IDEA project.
=> Tweaks for IntelliJ IDEA

build.gradle, com.ibm.wala.cast.js.html.nu_validator/build.gradle, com.ibm.wala.cast.js.rhino.test/build.gradle, com.ibm.wala.cast.js.test.data/.settings/org.eclipse.jdt.core.prefs, com.ibm.wala.cast.js.test.data/build.gradle, com.ibm.wala.cast.js.test/build.gradle, com.ibm.wala.cast.test/build.gradle, com.ibm.wala.dalvik.test/build.gradle
These changes have the general theme of improving integration of WALA’s Gradle build system with Eclipse and IntelliJ IDEA integrated development environments.
=> Miscellaneous IDE updates

com.ibm.wala.core.testdata/src/libmodels/LibModels.java, com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/callGraph/LibModelsTest.java, com.ibm.wala.core/dat/natives.xml, com.ibm.wala.core/src/com/ibm/wala/ipa/summaries/XMLMethodSummaryReader.java
=> Add models for Runtime.addShutdownHook and Thread.setDefaultUncaughtExceptionHandler

com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/classLoader/DexIMethod.java
I recently faced the same issue. This PR fixes the problem.
=> Fixes #373  (Cast error)

com.ibm.wala.cast/source/java/com/ibm/wala/cast/ipa/callgraph/AstCallGraph.java, com.ibm.wala.core/src/com/ibm/wala/ipa/summaries/SummarizedMethodWithNames.java, com.ibm.wala.core/src/com/ibm/wala/ipa/summaries/VolatileMethodSummary.java
I try to aggregate my code-janitor commits into logical themes. The unifying theme for this small group of fixes is: “Derp.”
=> Fixes for a few rather silly bugs

com.ibm.wala.cast.js.nodejs/src/com/ibm/wala/cast/js/nodejs/NodejsRequiredSourceModule.java, com.ibm.wala.cast/source/java/com/ibm/wala/cast/ir/ssa/SSAConversion.java, com.ibm.wala.core.testdata/src/cornerCases/AliasNames.java, com.ibm.wala.core/src/com/ibm/wala/cfg/AbstractCFG.java, com.ibm.wala.core/src/com/ibm/wala/cfg/InducedCFG.java, com.ibm.wala.core/src/com/ibm/wala/cfg/ShrikeCFG.java, com.ibm.wala.core/src/com/ibm/wala/classLoader/ClassLoaderImpl.java, com.ibm.wala.core/src/com/ibm/wala/classLoader/ShrikeClass.java, com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/impl/BasicCallGraph.java, com.ibm.wala.core/src/com/ibm/wala/ssa/SSACFG.java, com.ibm.wala.core/src/com/ibm/wala/ssa/analysis/ExplodedControlFlowGraph.java, com.ibm.wala.dalvik.test/source/com/ibm/wala/dalvik/test/callGraph/DroidBenchCGTest.java, com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/classLoader/DexCFG.java, com.ibm.wala.ide.jdt.test/source/com/ibm/wala/demandpa/driver/DemandCastChecker.java, com.ibm.wala.ide/src/com/ibm/wala/ide/util/EclipseFileProvider.java, com.ibm.wala.util/src/com/ibm/wala/fixedpoint/impl/AbstractFixedPointSolver.java, com.ibm.wala.util/src/com/ibm/wala/fixpoint/AbstractStatement.java
These commits correct a few simple cases in which we were operating on strings in redundant ways.
=> Minor fixes for redundant string operations

build.gradle, config/hooks/install-pre-commit, config/hooks/pre-commit, config/hooks/pre-commit-stub
I believe that these tweaks address all of the comments that I recently attached to specific lines of code in @msridhar’s work-in-progress pull request #410.
=> Fixes for inconsistent Gradle formatting and shell linter warnings

.idea/codeStyles/codeStyleConfig.xml, .idea/compiler.xml
IntelliJ IDEA 2018.3 wants these settings to exist.  OK, sure.  Nothing in them seems user-specific to me, so let's track them in version control.
=> Add some new IntelliJ IDEA metadata files/settings

com.ibm.wala.cast.js.test/harness-src/com/ibm/wala/cast/js/test/JSCallGraphBuilderUtil.java, com.ibm.wala.cast.js/source/com/ibm/wala/cast/js/ipa/callgraph/JSSSAPropagationCallGraphBuilder.java, com.ibm.wala.cast.js/source/com/ibm/wala/cast/js/ipa/callgraph/correlations/extraction/CorrelatedPairExtractionPolicy.java, com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/propagation/SSAPropagationCallGraphBuilder.java
@AlisaMaas, @juliandolby, and I have some WALA-based research work still in progress. We are not yet ready to make that research public, but these are some miscellaneous WALA changes that have come up along the way. @juliandolby thinks they all make sense for general WALA use, so it is appropriate to upstream them now. We particularly want to minimize any WALA Java code divergences before the upcoming mass reformatting (#433).
=> Assorted Java changes from in-progress research

com.ibm.wala.cast/source/java/com/ibm/wala/cast/ir/ssa/SSAConversion.java, com.ibm.wala.core/src/com/ibm/wala/cfg/AbstractCFG.java, com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ssa/AbstractIntRegisterMachine.java, com.ibm.wala.shrike/src/com/ibm/wala/shrikeBT/Compiler.java, com.ibm.wala.shrike/src/com/ibm/wala/shrikeBT/Decoder.java, com.ibm.wala.shrike/src/com/ibm/wala/shrikeBT/analysis/Analyzer.java, com.ibm.wala.util/src/com/ibm/wala/util/graph/traverse/FloydWarshall.java, com.ibm.wala.util/src/com/ibm/wala/util/graph/traverse/WelshPowell.java, com.ibm.wala.util/src/com/ibm/wala/util/intset/BitVector.java, com.ibm.wala.util/src/com/ibm/wala/util/intset/BitVectorBase.java, com.ibm.wala.util/src/com/ibm/wala/util/intset/FixedSizeBitVector.java, com.ibm.wala.util/src/com/ibm/wala/util/intset/OffsetBitVector.java
A few simple array-related improvements for things that I noticed while doing other work.
=> Small array improvements

com.ibm.wala.core/src/com/ibm/wala/ipa/summaries/LambdaMethodTargetSelector.java, com.ibm.wala.core/src/com/ibm/wala/ipa/summaries/LambdaSummaryClass.java, com.ibm.wala.core/src/com/ibm/wala/ipa/summaries/MethodSummary.java, com.ibm.wala.scandroid/source/org/scandroid/util/AndroidAnalysisContext.java
Just some code cleanup and a couple of comments
=> Refactor some lambda-related code

dependent-projects-trigger.sh
=> Only trigger dependent project builds on WALA master branch

com.ibm.wala.dalvik.test/build.xml
Similar to #455 but for Maven / Ant
=> Fix sample cup download in Maven build

.idea/inspectionProfiles/No_Back_Sliding.xml, com.ibm.wala.cast.js/source/com/ibm/wala/cast/js/html/WebUtil.java, com.ibm.wala.cast/source/java/com/ibm/wala/cast/util/AstConstantCollector.java, com.ibm.wala.core.testdata/src/libmodels/LibModels.java, com.ibm.wala.shrike/src/com/ibm/wala/shrike/cg/Runtime.java, com.ibm.wala.util/src/com/ibm/wala/fixedpoint/impl/DefaultFixedPointSystem.java
No performance penalty here: the existing code already used lambas, so a method reference will be no different.
=> Replace lambda with method reference where possible

gradle-mvn-push.gradle
This is equivalent to using `String.equals()`, but IMHO more readable.
=> Use "==" to compare Gradle strings

.idea/vcs.xml
IntelliJ IDEA recently started bundling the Grazie plugin for checking comment spelling, grammar, etc.  This change appears to reflect IntelliJ IDEA 2019.3 storing the default Grazie configuration.
=> Store default configuration of Grazie checker

README.md
Add GitHub Actions CI status badge for `master` branch, as in: [![GitHub Actions status](https://github.com/wala/WALA/workflows/Continuous%20integration/badge.svg)](https://github.com/wala/WALA/actions?query=workflow%3A%22Continuous+integration%22).
Replace HTML links with proper MarkDown links.
=> Small tweaks and improvements to top-level README.md

gradle/wrapper/gradle-wrapper.properties, gradlew.bat
=> Upgrade to Gradle 6.2.2

build.gradle, com.ibm.wala.cast.java.ecj/build.gradle, com.ibm.wala.cast.java.test.data/build.gradle, com.ibm.wala.cast.js.nodejs/build.gradle, com.ibm.wala.cast.js/build.gradle, com.ibm.wala.cast/build.gradle, com.ibm.wala.cast/cast/build.gradle, com.ibm.wala.cast/smoke_main/build.gradle, com.ibm.wala.core/build.gradle, com.ibm.wala.dalvik/build.gradle, com.ibm.wala.util/build.gradle
Groovy’s`final` implies `def`; we don't need both.
=> Simple replacement of "final def" with "final"

build.gradle
=> Fix "NO-SOURCE" regression in aggregatedJavadoc Gradle task

com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrikeCT/BootstrapMethodsReader.java
=> fix another javadoc warning

com.ibm.wala.ide/src/main/java/com/ibm/wala/ide/util/EclipseProjectPath.java
=> Add back jar parameter

travis/script-gradle
When we landed #749 we forgot to fix up the Travis Gradle scripts
=> Skip ECJ tasks on Travis Mac job

com.ibm.wala.core/build.gradle
hamcrest-core is deprecated and hamcrest is the preferred artifact
=> remove hamcrest-core dep

com.ibm.wala.ide.jdt.test/build.gradle, com.ibm.wala.ide.jdt/build.gradle, com.ibm.wala.ide.jsdt.tests/build.gradle, com.ibm.wala.ide.jsdt/build.gradle, com.ibm.wala.ide.tests/build.gradle, com.ibm.wala.ide/build.gradle
Somehow the versions changed in transitive deps so these projects don't compile anymore.  I don't really understand what happened, but this seems to fix for now.
=> Fix build for IDE projects

.idea/vcs.xml
These are minor changes to project metadata under IntelliJ IDEA 2021.1.2.
=> Minor IntelliJ IDEA 2021.1.2 metadata updates

com.ibm.wala.cast.java.ecj/build.gradle, com.ibm.wala.cast.java/src/testFixtures/java/com/ibm/wala/cast/java/test/IRTests.java
=> Remove some commented-out code

com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/slicer/PDG.java
=> Remove an invalid assertion in PDG construction code

gradle/wrapper/gradle-wrapper.properties
=> Update to Gradle 7.3.1

build.gradle
We didn't write this code and are in no position to critique its formatting.
=> Don't check formatting of downloaded Java sources

build.gradle, buildSrc/build.gradle, com.ibm.wala.cast.js.nodejs/build.gradle, com.ibm.wala.cast.js.rhino/build.gradle, com.ibm.wala.cast.js/build.gradle, com.ibm.wala.core/build.gradle, com.ibm.wala.dalvik/build.gradle, com.ibm.wala.scandroid/build.gradle
Limited to what seemed like "safe" updates that I don't expect to cause test failures.
=> Update various dependencies

buildSrc/src/main/groovy/wala-java.gradle
There is no way I am going to have time to add enough documentation in the near term to fix these warnings; it can be a long-term goal.
=> Disable MissingSummary check

.idea/misc.xml, build.gradle, buildSrc/src/main/groovy/wala-java.gradle
This version allows for a slight simplification in configuration, but otherwise works the same.
=> Bump Error Prone Gradle plugin version to 3.0.1

com.ibm.wala.core/src/testFixtures/java/com/ibm/wala/core/tests/util/WalaTestCase.java
On Windows with Java 11, the `java.class.path` property contains backslash-escaped backslashes, as in "`C:\\foo\\bar`".  These doubled backslashes interfere with the logic for finding classpath entries that contain the requested element.  Using normalized paths for all comparisons seems to fix the problem, and will likely be more robust in general.
=> Revamp classpath search to use normalized paths

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/settings.gradle.kts, buildSrc/src/main/kotlin/com/ibm/wala/gradle/JavaCompileUsingEcj.kt, buildSrc/src/main/kotlin/com/ibm/wala/gradle/NullAway.gradle.kts, buildSrc/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts, com.ibm.wala.cast.java.ecj/build.gradle.kts, com.ibm.wala.cast.java/build.gradle.kts, com.ibm.wala.cast.js.html.nu_validator/build.gradle.kts, com.ibm.wala.cast.js.nodejs/build.gradle.kts, com.ibm.wala.cast.js.rhino/build.gradle.kts, com.ibm.wala.cast.js/build.gradle.kts, com.ibm.wala.cast/build.gradle.kts, com.ibm.wala.core.java11/build.gradle.kts, com.ibm.wala.core/build.gradle.kts, com.ibm.wala.dalvik/build.gradle.kts, com.ibm.wala.ide.jdt.test/build.gradle.kts, com.ibm.wala.ide.jdt/build.gradle.kts, com.ibm.wala.ide.jsdt.tests/build.gradle.kts, com.ibm.wala.ide.jsdt/build.gradle.kts, com.ibm.wala.ide.tests/build.gradle.kts, com.ibm.wala.ide/build.gradle.kts, com.ibm.wala.scandroid/build.gradle.kts, com.ibm.wala.util/build.gradle.kts, gradle/libs.versions.toml
=> Gather dependency versions in a version catalog

build.gradle.kts, gradle/libs.versions.toml
=> Use Eclipse 4.21.0 on all platforms

gradle/libs.versions.toml
=> Update to Error Prone 2.17.0

com.ibm.wala.core/build.gradle.kts
=> Remove an unnecessary dependency

gradle/libs.versions.toml
=> Update to Error Prone 2.18.0

com.ibm.wala.dalvik/build.gradle.kts
Previously, executing this task used several items from the current `Project` or the enclosing root project.  However, the Gradle configuration cache disallows direct `Project` access from tasks' execution logic.  Instead, we need to use an injected service for access to `exec`.  For a few other project-carried values, we need to grab those values earlier, when the task is just being configured.
=> Make `installAndroidSdk` compatible with configuration cache

com.ibm.wala.core/build.gradle.kts
Previously these tasks depended on the current `Project` for access to some Gradle features: `copy`, `tarTree`, and `zipTree`.  However, we want to avoid accessing `project` during a task's execution, because that's incompatible with the Gradle configuration cache.  Instead, we now use injected services to provide access to these same features.
Unfortunately, even with this change, these extraction tasks are still not compatible with the Gradle configuration cache.  Each of them takes input from a `VerifiedDownload` task, and [we're still working out how to make the latter configuration-cache safe](https://github.com/michel-kraemer/gradle-download-task/issues/284).
=> Use injected services for a few extraction tasks

generate-latest-docs.sh
Follow-up to aeb2acd0d6a75a1a7ca6371f082dbee662357fd2
=> Disable configuration cache when generating latest docs

cast/js/rhino/src/test/java/com/ibm/wala/cast/js/rhino/test/HTMLCGBuilder.java, cast/js/src/testFixtures/java/com/ibm/wala/cast/js/test/TestForInBodyExtraction.java, ide/jdt/test/src/test/java/com/ibm/wala/cast/java/test/JDTJavaTest.java
These miscellaneous uses of JUnit 4 escaped my attention in other recent conversion passes.
=> Port a few JUnit 4 odds and ends to JUnit 5

gradle/libs.versions.toml
=> Update NullAway to 0.10.12

summarize-time-trials
Python local variables generally use `snake_case` names.
=> Conform to Python naming conventions

gradle/libs.versions.toml
=> Update to NullAway 0.10.14

gradle/libs.versions.toml
=> Update Error Prone and NullAway

gradle/libs.versions.toml, settings.gradle.kts
Fixes #1278, as a fix for https://github.com/diffplug/goomph/issues/211 has landed in this release.  🎉
=> Bump the goomph plugin version

gradle/libs.versions.toml
=> Update to Error Prone 2.24.0

gradle/libs.versions.toml
=> Update versions for Guava, NullAway, and Gradle versions plugin

gradle/libs.versions.toml
=> Version updates: Error Prone, NullAway, Gradle Error Prone Plugin

gradle/libs.versions.toml
=> Update to Error Prone 2.25.0 and NullAway 0.10.23

build-logic/src/main/kotlin/com/ibm/wala/gradle/NullAway.gradle.kts, build-logic/src/main/kotlin/com/ibm/wala/gradle/cast/helpers.kt, build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts, cast/cast/build.gradle.kts, cast/smoke_main/build.gradle.kts, cast/xlator_test/build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, gradlew.bat
This caused configuration issues on M1 Macs; see #1383
=> Revert Gradle 8.7 upgrade

gradle/libs.versions.toml
=> Update Error Prone to 2.26.1

gradle/libs.versions.toml
=> Update to Error Prone 2.27.1

core/build.gradle.kts, core/src/main/java/com/ibm/wala/core/util/scope/JUnitEntryPoints.java, core/src/test/java/com/ibm/wala/core/tests/cha/JunitEntrypointSupportTest.java, core/src/testSubjects/java/junit/JunitTests.java
=> Fix JUnitEntryPoints annotation check

build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
=> Always compile using JDK 22

gradle/libs.versions.toml
=> Bump Error Prone and NullAway versions to latest

gradle/libs.versions.toml
=> Update to Error Prone 2.32.0

build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
To get the latest javac bug fixes
=> Compile using JDK 23

gradle/libs.versions.toml
=> Update to NullAway 0.12.0

gradle/libs.versions.toml
=> Bump Error Prone and Error Prone plugin to latest

core/src/main/java/com/ibm/wala/ipa/callgraph/cha/CHACallGraph.java
We should only update `targetCache` when computing the call graph, not when reading its current state.  When debugging another issue, I ran into very confusing behavior where the debugger invoked `toString()` on a `CHACallGraph` to display its state, which ended up updating `targetCache` (whose state I was trying to debug) by calling an accessor method.
=> Don't update CHACallGraph internal target cache from CallGraph getter methods

gradle/libs.versions.toml
=> Update to NullAway 0.12.4

gradle/libs.versions.toml
=> Update Error Prone, EP Plugin, and NullAway

.github/codecov.yml, .github/workflows/continuous-integration.yml
Things seem to work, but I can't confirm we can actually see source code lines on Codecov.  I _think_ this has to be merged to the master branch before we can test that.
=> Add Codecov

cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/JavaIRTests.java, cast/src/test/java/com/ibm/wala/cast/test/TestCAstTranslator.java, core/src/test/java/com/ibm/wala/core/tests/basic/FloydWarshallTest.java, core/src/test/java/com/ibm/wala/core/tests/basic/PrimitivesTest.java, core/src/test/java/com/ibm/wala/core/tests/callGraph/CHACallGraphTest.java, core/src/test/java/com/ibm/wala/core/tests/callGraph/ReflectionTest.java, core/src/test/java/com/ibm/wala/core/tests/cha/MissingSuperTest.java, core/src/test/java/com/ibm/wala/core/tests/ir/CFGTest.java, core/src/test/java/com/ibm/wala/core/tests/ir/LocalNamesTest.java, core/src/test/java/com/ibm/wala/core/tests/ir/TypeAnnotationTest.java, core/src/test/java/com/ibm/wala/core/tests/shrike/FloatingPointsTest.java, core/src/testFixtures/java/com/ibm/wala/core/tests/ir/AnnotationTest.java
* d2afed7f3 Improve dynamic type assertions
* cb0e1e465 Simplify check for null array elements
* 2a4955a7c Remove redundant non-null checks
* 0a8e07a4a Simplify checking contents of collections and arrays
* 043553740 Simplify deep equality check
* 705ee0643 Simplify multiple checks on same value
=> Simplify various AssertJ checks

build-logic/src/main/kotlin/com/ibm/wala/gradle/NullAway.gradle.kts, build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts, build-logic/src/main/kotlin/com/ibm/wala/gradle/project.gradle.kts
Subprojects implicitly inherit the root project's version catalog.
=> Access version catalog more concisely

build.gradle.kts
Kotlin will turn this assignment into the setter call that we previously used here.
=> Simplify property assignment

build-logic/src/main/kotlin/com/ibm/wala/gradle/cast/helpers.kt
We're not the only ones to have noticed that native binaries' APIs could be improved.
=> Add GitHub issue link to KDoc documentation

build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
These are equivalent here.  I consider the assignment form to be a nice use of Kotlin's syntactic sugar.
=> Prefer assignment over setter call

gradle/libs.versions.toml
A few other pending updates may require changes to Java source code or Gradle Kotlin build logic.  The updates included here, though, only require changes to the version catalog.
=> Simple dependency updates
