- com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/propagation/FilteredPointerKey.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/propagation/PropagationSystem.java
- com.ibm.wala.core/src/com/ibm/wala/ssa/SSAPhiInstruction.java
The former will include the contents of the array, while the latter only includes the object's identity.
This will allow WALA to be compiled using Google's error-prone compiler (https://github.com/google/error-prone).
> Use Arrays.toString() instead of the default array toString() method.

- com.ibm.wala.cast.js.test/.launchConfigurations/com.ibm.wala.cast.js.test-JUnit.launch
The JUnit launcher of com.ibm.wala.cast.js.test could not access the resource because the runtimeClasspathEntry did not linked to the data package.
> Fixed JUnit launcher of com.ibm.wala.cast.js.test

- com.ibm.wala.cast.java.ecj/src/com/ibm/wala/cast/java/translator/jdt/FakeExceptionTypeBinding.java
The fixes needed for Eclipse Neon are very similar to those previously added for Luna (c9ad359d656463eccea08417d9855d4eb8f4478b + 0e55cd2eecdd830428a4fa16ab99ef7ca98f9df4, fixing #56) and Mars (6df8d1b32d1b6a9750bdb368efaecab8c1edca8c, fixing #98).
> Build fixes for Eclipse Neon

- com.ibm.wala.dalvik.test/build.xml
The proposed additions to the ant script automatically copy the dx.jar from the local Android SDK folder into the `com.ibm.wala.dalvik.test/lib` folder, if ANDROID_HOME is set. This is basically the procedure from [here](https://groups.google.com/forum/#!msg/wala-sourceforge-net/cBYsfEvYVG0/Ua52dyQQU-YJ). As the dx.jar is needed for a clean compile of the whole project, the user does not have to copy it manually anymore.
> Added build script step to copy dx.jar from Android SDK.

- com.ibm.wala.core.tests/META-INF/MANIFEST.MF
Some source files in `com.ibm.wala.core.tests` use [Hamcrest](http://hamcrest.org/), so listing it as a dependency seems reasonable.  What I find confusing is the inconsistency among my Eclipse installations.  On some of my various machines, Eclipse reports an error if this dependency is not listed.  On others, Eclipse finds the required jar and reports no error, even if this dependency is not listed.  I don’t know why the latter works, or why the inconsistency exists at all.  Eclipse is a complex, subtle beast.  What I can say is that this change fixes the error for my Eclipses that were reporting an error, and does not introduce any new errors for my Eclipses that were already happy before this change.
> Add Hamcrest dependency

- com.ibm.wala.core/src/com/ibm/wala/ssa/IR.java
This is a small but handy improvement when debugging exceptional control-flow.
> display which classes each handler catches when outputting IR

- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/util/AndroidEntryPointManager.java
If a client violates these restrictions, I prefer that their code fail at compile time instead of run time.  Changing a few key types from `Class` to `Class<? extends AbstractAndroidModel>` gives us precisely the static enforcement we need and lets us remove an `AbstractAndroidModel.class.isAssignableFrom` run-time check.
However, this does change the public API of `AndroidEntryPointManager` in two ways.  The `getModelBehavior` and `setModelBehavior` methods now respectively accept and return `Class<?  extends AbstractAndroidModel>` instead of `Class`.  Is tightening up a public API in this manner considered OK?
> Enforce restrictions on the model behavior class statically

- com.ibm.wala.core.testdata/src/cfg/exc/inter/CallFieldAccess.java
- com.ibm.wala.core.testdata/src/cfg/exc/intra/B.java
- com.ibm.wala.core.testdata/src/cfg/exc/intra/FieldAccess.java
- com.ibm.wala.core.testdata/src/cfg/exc/intra/FieldAccessDynamic.java
- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/cfg/exc/inter/NullPointerExceptionInterTest.java
- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/cfg/exc/intra/NullPointerExceptionIntraTest.java
- com.ibm.wala.core/src/com/ibm/wala/analysis/nullpointer/IntraproceduralNullPointerAnalysis.java
- com.ibm.wala.core/src/com/ibm/wala/cfg/exc/intra/IntraprocNullPointerAnalysis.java
- com.ibm.wala.core/src/com/ibm/wala/cfg/exc/intra/NullPointerSolver.java
- com.ibm.wala.core/src/com/ibm/wala/cfg/exc/intra/NullPointerState.java
- com.ibm.wala.core/src/com/ibm/wala/cfg/exc/intra/NullPointerTransferFunctionProvider.java
- com.ibm.wala.core/src/com/ibm/wala/cfg/exc/intra/OperatorUtil.java
- com.ibm.wala.core/src/com/ibm/wala/cfg/exc/intra/ParameterState.java
This pull requests fixes intraprocedural Nullpointer analysis by respecting phi-nodes, and correctly initializing entry variables.
Since the changes are non-trivial, i do not expect you to blindly merge them.
Instead, I suggest you to look at the tests added in 1b74b906fc03a1e04678ec513c3db9213c3d05e5, and observe that some of these *fail* with the current implementation.
Specifically w.r.t. soundness, the test `testIf3()` asserts that if a value is returned from the method
```Java
static B testIf3(boolean unknown, B b1) {
if (unknown) {
b1.f = 42;
} else {
System.out.println("rofl");
}
return b1;
}
```
, it cannot be statically to be known `==null`, nor can it statically be known to be `!=null`
This is so because (even though for calls with `unknown == true`, if a value is returned, we …
> Pull request  nullpointer bugfixes

- com.ibm.wala.core/src/com/ibm/wala/classLoader/JavaLanguage.java
- com.ibm.wala.core/src/com/ibm/wala/classLoader/ShrikeIRFactory.java
These commits allow pruning of exceptional control flow for JavaLangNegativeArraySizeException  during array creation for cases like
```
int a[] = new int[42]; // 42 is constant, >=0
int b[] = new int[a.length] // if a!=null, we know that a.length >=0, hence no JavaLangNegativeArraySizeException will ever be thrown
```
> Pull request  exception pruning for safe array creation

- .gitignore
This arises at some point during `mvn compile install`.  I’m not sure exactly when, but it’s definitely automated, and therefore not appropriate to track in git.
> Ignore a "lib" subdirectory that Maven creates

- com.ibm.wala.cast.js.rhino.test/harness-src/com/ibm/wala/cast/js/rhino/callgraph/fieldbased/test/AbstractFieldBasedTest.java
- com.ibm.wala.cast.js.rhino.test/harness-src/com/ibm/wala/cast/js/rhino/callgraph/fieldbased/test/FieldBasedComparisonTest.java
- com.ibm.wala.cast.js.rhino.test/harness-src/com/ibm/wala/cast/js/rhino/test/HTMLCGBuilder.java
- com.ibm.wala.cast.test/harness-src/com/ibm/wala/cast/test/TestCAstPattern.java
- com.ibm.wala.cast.test/harness-src/com/ibm/wala/cast/test/TestCAstTranslator.java
- com.ibm.wala.cast.test/harness-src/com/ibm/wala/cast/test/TestCallGraphShape.java
- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/cha/ExclusionsTest.java
- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/ir/CFGSanitizerTest.java
- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/ptrs/ZeroLengthArrayTest.java
- com.ibm.wala.core.tests/src/com/ibm/wala/examples/analysis/dataflow/DataflowTest.java
- com.ibm.wala.core.tests/src/com/ibm/wala/examples/analysis/dataflow/InitializerTest.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/cha/CHACallGraph.java
- com.ibm.wala.ide.jdt.test/source/com/ibm/wala/cast/java/test/JDTJavaTest.java
- com.ibm.wala.ide.jdt/source/com/ibm/wala/ide/util/JdtUtil.java
The vast majority of these (about 92 in total) are fixed by replacing `junit.framework.Assert` and `junit.framework.AssertionFailedError` (from JUnit 3.*x*) with `org.junit.Assert` and `java.lang.AssertionError` (from JUnit 4.*x*).
Three other deprecation warnings were better suppressed than fixed. One involves WALA asking for a rather old AST JLS version; the other two involve presumed-safe use of an internal WALA API by other parts of WALA.
> Resolve all Eclipse warnings about deprecated APIs

- com.ibm.wala.core/src/com/ibm/wala/escape/FILiveObjectAnalysis.java
As it turns out, I should have been using "`? extends InstanceKey`" rather than "`? super InstanceKey`".  But really, we can just use "`?`" here since `HeapGraph` itself constrains its own type parameter appropriately.
This should fix WALA bug #151, which was first introduced by [this change](https://github.com/wala/WALA/commit/fde65340d22f153914343a33bbaf6f5497ce67f4#diff-6f505606d6841bf44858283ce76371ceL71) in commit fde65340d22f153914343a33bbaf6f5497ce67f4.
> Generalize a generic type parameter even more

- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/slicer/SlicerTest.java
- com.ibm.wala.core.tests/src/com/ibm/wala/examples/drivers/PDFSDG.java
- com.ibm.wala.core.tests/src/com/ibm/wala/examples/drivers/PDFSlice.java
- com.ibm.wala.core/src/com/ibm/wala/client/AbstractAnalysisEngine.java
- com.ibm.wala.core/src/com/ibm/wala/demandpa/util/PABasedMemoryAccessMap.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/propagation/ReflectionHandler.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/modref/ModRef.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/slicer/SDG.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/slicer/Slicer.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/slicer/thin/CISlicer.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/slicer/thin/ThinSlicer.java
- com.ibm.wala.dalvik.test/source/com/ibm/wala/dalvik/drivers/APKCallGraphDriver.java
Special thanks to @khatchad for [asking why this argument was needed](https://github.com/wala/WALA/pull/146#commitcomment-21999159). It isn't!
> Remove unnecessary `klass` argument and propagate back to callers

- com.ibm.wala.cast.java.test/build.properties
- com.ibm.wala.cast.java/build.properties
- com.ibm.wala.cast.js.html.nu_validator/build.properties
- com.ibm.wala.cast.js.nodejs.test/build.properties
- com.ibm.wala.cast.js.nodejs/build.properties
- com.ibm.wala.cast.js.rhino.test/build.properties
- com.ibm.wala.cast.js.rhino/build.properties
- com.ibm.wala.cast.js.test/build.properties
- com.ibm.wala.cast.js/build.properties
- com.ibm.wala.cast.test/build.properties
- com.ibm.wala.cast/build.properties
- com.ibm.wala.core.tests/build.properties
- com.ibm.wala.core/build.properties
- com.ibm.wala.dalvik.test/build.properties
- com.ibm.wala.ide.jdt.test/build.properties
- com.ibm.wala.ide.jdt/build.properties
- com.ibm.wala.ide.jsdt.tests/build.properties
- com.ibm.wala.ide.jsdt/build.properties
- com.ibm.wala.ide.tests/build.properties
- com.ibm.wala.ide/build.properties
- com.ibm.wala.shrike/build.properties
- com.ibm.wala.util/build.properties
Specifically, these are all warnings of the form "The 'javacProjectSettings' build entry should be set when there are project specific compiler settings".
> Fix warnings about unset javacProjectSettings build entries

- com.ibm.wala.core.tests/src/com/ibm/wala/examples/analysis/dataflow/StaticInitializer.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/summaries/VolatileMethodSummary.java
- com.ibm.wala.core/src/com/ibm/wala/util/ssa/ParameterAccessor.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/analysis/typeInference/DalvikTypeInference.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/classLoader/DexIClass.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/classLoader/InstructionArray.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/androidModel/IntentModel.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/androidModel/MicroModel.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/androidModel/MiniModel.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/androidModel/parameters/SpecializedInstantiator.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/androidModel/structure/LoopAndroidModel.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/androidModel/structure/LoopKillAndroidModel.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/androidModel/structure/SequentialAndroidModel.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/androidModel/structure/SingleStartAndroidModel.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/propagation/cfa/Intent.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ssa/DexSSABuilder.java
- com.ibm.wala.ide.jsdt.tests/src/com/ibm/wala/ide/jsdt/tests/Activator.java
- com.ibm.wala.scandroid/source/org/scandroid/domain/DomainElement.java
- com.ibm.wala.scandroid/source/org/scandroid/domain/InstanceKeyElement.java
- com.ibm.wala.scandroid/source/org/scandroid/prefixtransfer/PrefixVariable.java
- com.ibm.wala.scandroid/source/org/scandroid/prefixtransfer/StringBuilderUseAnalysis.java
- com.ibm.wala.scandroid/source/org/scandroid/prefixtransfer/modeledAllocations/ConstantString.java
- com.ibm.wala.scandroid/source/org/scandroid/prefixtransfer/modeledAllocations/UriAppendString.java
- com.ibm.wala.scandroid/source/org/scandroid/prefixtransfer/modeledAllocations/UriParseString.java
- com.ibm.wala.scandroid/source/org/scandroid/spec/EntryArgSinkSpec.java
This fixes 49 Eclipse code style warnings.  I'm not sure why these were overlooked in [my previous sweep of missing-`@Override` warnings](https://github.com/wala/WALA/commit/4cef26162c2d2f73449cd3cf2e80d2cf15cc459c). Ah well; got ’em this time around.
> Add `@Override` annotations to all methods that do override

- .travis.yml
Using the `xvfb-run` script gives us automatic lifetime management for the virtual X server: it will start before the `mvn` test script and will terminate when that test script exits.  The `xvfb-run` script also sets `$DISPLAY` properly in the `mvn` test script, so we no longer need to manage that setting ourselves.
> Simplify management of virtual frame buffer X server

- com.ibm.wala.cast.java.ecj/src/com/ibm/wala/cast/java/translator/jdt/JDTJava2CAstTranslator.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/slicer/SDGSupergraph.java
There were only three left, all fairly straightforward to fix.
> Fix all remaining Eclipse "Unnecessary Code" warnings

- com.ibm.wala.core/src/com/ibm/wala/ipa/slicer/PDG.java
We cannot find any case where this code fixes a problem,
and it doesn't seem to be a good fix anyway.
> Remove code to scan call sites for max param count

- com.ibm.wala.core.tests/launchers/wala.core short profile (non-windows).launch
- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/callGraph/CallGraphTest.java
We should add some proper unit tests if we really care about how
reflection is handled for these tests; they take way too long to run
> speed up some CG tests by disabling reflection handling

- com.ibm.wala.cast.js.nodejs.test/.settings/org.eclipse.jdt.core.prefs
- com.ibm.wala.ide.jdt.test/.settings/org.eclipse.jdt.core.prefs
I’m very picky about code style, but even I see no benefit in requiring `this.field` instead of simply `field`.
This resolves all remaining Eclipse warnings in the “Code Style” category.
> Disable Eclipse warnings about unqualified accesses to instance fields

- com.ibm.wala.core/src/com/ibm/wala/analysis/typeInference/JavaPrimitiveType.java
You can see from: https://github.com/wala/WALA/blob/68f30f949d60b290a75bbd4d52956a412f01f91c/com.ibm.wala.core/src/com/ibm/wala/analysis/typeInference/JavaPrimitiveType.java#L62 that it's missing. In other words, That line would never print since the corresponding constant is missing.
> Add missing void type.

- com.ibm.wala.cast.js.nodejs/build.properties
@juliandolby added this in a recent commit, but has told me that he does not think it is necessary, and that I am free to remove it if it is causing trouble.  Removing this does indeed fix one Eclipse error diagnostic: "Default encoding (UTF-8) for library '.' should be removed as the workspace does not specify an explicit encoding."
> Remove a default encoding setting that Eclipse considers unnecessary

- com.ibm.wala.cast.js.nodejs/.project
This was causing a bunch of errors in Eclipse, but we don't care about Eclipse Maven integration
> disable Maven nature for NodeJS project

- pom.xml
Specifically, this will run the `javadoc` goal of the `maven-javadoc-plugin` and the `plugin-source` goal of the `tycho-source-plugin` whenever Eclipse does a full build.  It will not run these on incremental builds, though.  Maven plugins in general are usually not designed with incremental execution in mind, so rerunning them on every incremental build turns out to be too sluggish in practice.
Previously, M2Eclipse would occasionally notice these two plugins, realize it didn’t know what to do with them, and produce Eclipse error diagnostics that were difficult to resolve.  With this change we are telling Eclipse’s Maven builder to just run the plugins in the natural way even though M2Eclipse has no special handling built-in for them.
Fixes #198, much to my relief.
> Tell M2Eclipse to run a few Maven plugins with no special handling

- com.ibm.wala.util/mvncentral.xml
- com.ibm.wala.util/src/com/ibm/wala/fixpoint/BooleanVariable.java
- com.ibm.wala.util/src/com/ibm/wala/util/collections/Iterator2Collection.java
- com.ibm.wala.util/src/com/ibm/wala/util/collections/ParanoidHashSet.java
- com.ibm.wala.util/src/com/ibm/wala/util/collections/Util.java
- com.ibm.wala.util/src/com/ibm/wala/util/config/FileOfClasses.java
- com.ibm.wala.util/src/com/ibm/wala/util/graph/traverse/DFS.java
- com.ibm.wala.util/src/com/ibm/wala/util/heapTrace/HeapTracer.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/BitVectorIntSetFactory.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/Bits.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/DebuggingMutableIntSet.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/IntSetUtil.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/LongSetUtil.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/MutableMapping.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/MutableSparseIntSetFactory.java
- com.ibm.wala.util/src/com/ibm/wala/util/io/FileUtil.java
- com.ibm.wala.util/src/com/ibm/wala/util/io/TemporaryFile.java
- com.ibm.wala.util/src/com/ibm/wala/util/processes/Launcher.java
- com.ibm.wala.util/src/com/ibm/wala/util/tables/StringTable.java
- com.ibm.wala.util/src/com/ibm/wala/viz/DotUtil.java
Since @liblit was running out of warnings to fix... 😄 This PR enables [Error Prone](http://errorprone.info/) for building the Maven jar of wala.util.  I fixed most of the warnings it emitted, but turned a couple checks off since the issues needed more careful study.
The downside of this change is that Error Prone doesn't run during the standard Eclipse build.  Locally, you can run it by running `./build-maven-jars.py`, but you need to remember to do that.  Since the `wala.util` code is quite stable I think it's reasonable to enable here and experiment.
As you can see by the commented lines in `mvncentral.xml`, another goal is to try [NullAway](https://github.com/uber/NullAway) out on WALA to build up more robustness against NPEs.  But one step at a time.
> Enable ErrorProne on wala.util project

- com.ibm.wala.cast.java.ecj/src/com/ibm/wala/cast/java/translator/jdt/ecj/ECJSourceModuleTranslator.java
- com.ibm.wala.ide.jdt/source/com/ibm/wala/cast/java/translator/jdt/JDTSourceModuleTranslator.java
Near as I can tell, the requests for deprecated versions here are intentional.  The non-deprecated version (`AST.JLS9`) is the latest and greatest, but as far as I can tell we really do want the older version here.
This is similar to 6caecce3e74cec12f4f206bddb39c44875e46ddc, though in that case `JLS8` was the non-deprecated latest version and we were still asking for `JLS3`.
> Suppress deprecation warnings about requesting an old AST version

- com.ibm.wala.cast.java.ecj/mvncentral.xml
- com.ibm.wala.cast.java/mvncentral.xml
- com.ibm.wala.cast.js.rhino/mvncentral.xml
- com.ibm.wala.cast.js/mvncentral.xml
- com.ibm.wala.cast/mvncentral.xml
- com.ibm.wala.dalvik/mvncentral.xml
- com.ibm.wala.scandroid/mvncentral.xml
- com.ibm.wala.shrike/mvncentral.xml
E-mail exchanged with @juliandolby suggests that this is the right thing to do, and that it should have been done back when we converted other parts of the build configuration to Java 8.
> Update Maven Central configurations to also use Java 8

- com.ibm.wala.core.testdata/src/methodLookup/MethodLookupStuff.java
- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/cha/GetTargetsTest.java
- com.ibm.wala.core/src/com/ibm/wala/classLoader/BytecodeClass.java
The previous lookup logic would erroneously look in superclasses for a constructor with parameters.
Bug reported on [the mailing list](https://groups.google.com/forum/#!msg/wala-sourceforge-net/6m_VmDF-lZ0/erZIYQ68BwAJ;context-place=topic/wala-sourceforge-net/TjRzdDyljjY)
> Fix bug with method lookup

- com.ibm.wala.cast.js.rhino.test/harness-src/com/ibm/wala/cast/js/rhino/callgraph/fieldbased/test/AbstractFieldBasedTest.java
These are slow tests that we were already effectively turning into no-ops when running on Travis CI.  By skipping them using the proper JUnit mechanism, these tests will show up as ignored or skipped in test outcome reports.  That's better than having them show up as passing, when we really don't know whether they would have passed or failed.
> Use the proper JUnit mechanism for conditionally skipping tests

- com.ibm.wala.cast.java/src/com/ibm/wala/cast/java/loader/JavaSourceLoaderImpl.java
Since JavaSourceLoaderImpl is an abstract class, I would recommend to give visibility of internal fields at least to all the implementing classes in order to allow user modifications.
> Protected visibility for JavaSourceLoaderImpl's internal methods and classes

- com.ibm.wala.cast.java.test/build.gradle
- com.ibm.wala.cast.java.test/pom.xml
- com.ibm.wala.cast.js.html.nu_validator/pom.xml
- com.ibm.wala.cast.js.nodejs.test/build.gradle
- com.ibm.wala.cast.js.nodejs.test/pom.xml
- com.ibm.wala.cast.js.rhino.test/build.gradle
- com.ibm.wala.cast.js.rhino.test/pom.xml
- com.ibm.wala.cast.js.test/build.gradle
- com.ibm.wala.cast.js.test/pom.xml
- com.ibm.wala.cast.test/build.gradle
- com.ibm.wala.cast.test/pom.xml
- com.ibm.wala.core.tests/build.gradle
- com.ibm.wala.core.tests/pom.xml
- com.ibm.wala.dalvik.test/META-INF/MANIFEST.MF
- com.ibm.wala.dalvik.test/build.gradle
- com.ibm.wala.dalvik.test/pom.xml
- com.ibm.wala.ide.jdt.test/build.gradle
- com.ibm.wala.ide.jsdt.tests/build.gradle
WALA itself does not use any JUnit 4.12 features.  However, I am working on a WALA-based project that does require JUnit 4.12.  Mixing jar versions is a path to madness.  So if the WALA maintainers don’t mind, it would make my life easier if WALA itself required JUnit 4.12. Otherwise, I need to maintain that 4.11/4.12 difference indefinitely as a divergence between official WALA and my WALA variant.
I suppose an alternative could be to let the JUnit version be specified externally somehow. I have not explored this option in depth, but could look into it if simply moving to JUnit 4.12 is undesirable.
> Require JUnit 4.12 instead of 4.11

- com.ibm.wala.cast.java.test.data/build.gradle
- com.ibm.wala.cast.java.test/build.gradle
- com.ibm.wala.cast.java/build.gradle
- com.ibm.wala.cast.js.rhino.test/build.gradle
- com.ibm.wala.cast.js.test.data/build.gradle
- com.ibm.wala.cast.js.test/build.gradle
- com.ibm.wala.cast.test/build.gradle
- com.ibm.wala.cast/build.gradle
- com.ibm.wala.core.testdata/build.gradle
- com.ibm.wala.core.tests/build.gradle
- com.ibm.wala.core/build.gradle
- com.ibm.wala.ide.tests/build.gradle
- com.ibm.wala.ide/build.gradle
- com.ibm.wala.shrike/build.gradle
- com.ibm.wala.util/build.gradle
Apparently the latter is considered a “[legacy method](https://docs.gradle.org/current/userguide/plugins.html#sec:old_plugin_application).” Thanks for [pointing this out](https://github.com/wpilibsuite/gradle-jni/issues/5#issuecomment-391498975), @ThadHouse!
> Load Gradle plugins using “plugins” closure rather than “apply plugin”

- gradle/wrapper/gradle-wrapper.properties
No significant changes in this release that affect us, but it's good to stay up-to-date.
> Upgrade Gradle wrapper to release 4.8.1

- .travis.yml
- travis/install-gradle
- travis/script-gradle
In theory, if Gradle dependencies are set up correctly, then it should be possible to build any subproject starting with a pristine tree. If subproject *X* depends on subproject *Y*, then Gradle should know that building *X* requires building *Y* first. The way to test this is to systematically build each subproject starting from a pristine WALA tree. Unfortunately, with 29 subprojects on 2 supported platforms, that can take a while. Travis CI runs up to five jobs at a time, and running this entire set of tests takes nearly 7 hours. So that’s not something we want to do on every push or on every pull request. However, this would be reasonable to do less frequently, such as once per week.
Fortunately, Travis CI has support for running periodic (e.g., weekly) tests: [cron …
> Have Travis CI periodically try to build each subproject separately

- .idea/.gitignore
- .idea/.name
- .idea/gradle.xml
- .idea/runConfigurations/After_Opening_Pristine_Project.xml
- .idea/vcs.xml
- README-Gradle.md
- build.gradle
- com.ibm.wala.cast.test/build.gradle
- com.ibm.wala.dalvik.test/build.gradle
We already had some IntelliJ IDEA project metadata files in `.idea`. I've revisited and updated those now that I have more experience with Gradle + IntelliJ IDEA + Git.  I think this now represents a better set of decisions regarding what does and does not belong in version control.
This commit also extends `README-Gradle.md` with [clear instructions on how to bring up WALA as a top-level IntelliJ IDEA project](https://github.com/liblit/WALA/blob/WALA-as-IntelliJ-IDEA-project/README-Gradle.md#intellij-idea).  The instructions are of a similar flavor to the Eclipse instructions that were already present, though the details vary.  Most notably, with IntelliJ IDEA you should *open* WALA as an existing project, not *import* it as a new Gradle project derived from `build.gradle`. This is …
> Tweaks and instructions for WALA as an IntelliJ IDEA project

- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/cha/AnalysisScopeTest.java
- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/cha/MissingSuperTest.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/AnalysisScope.java
This is useful, e.g., if you have the bytes of a jar file in memory and want to load it into an AnalysisScope.
> Add API to add an InputStream for a jar to an AnalysisScope

- build.gradle
These changes allow one to use `./gradlew publishToMavenLocal` to put WALA jar archives in a local Maven repository for subsequent use by other Maven-based projects. We do not have any remote Maven repositories configured, though presumably that would work too if someone cared to set it up. I doubted whether this work work properly on the first try to fix #326. Apparently it does, at least to @msridhar’s satisfaction. Cool!
Note for future work: this change does nothing special in support of the Eclipse Provisioning Platform (p2). If p2 repositories are still considered important, then more work would be needed before Gradle could replace Maven entirely. liblit/WALA#6 has some discussion on this.
> Publish all generated Java bytecode jar archives

- settings.gradle
The issue here is a planned change to how `publishing` blocks work. Per [the Gradle documentation](https://docs.gradle.org/4.9/userguide/publishing_maven.html#publishing_maven:deferred_configuration), the right way to prepare for this change is to enable it and check for unexpected changes in what gets published to a local repository. I have done this, and find no unexpected changes.
So we are actually ready for Gradle 5.0; the warning is a false positive for us.  Leaving the future change enabled means we won’t keep seeing this warning.  It also means that any further changes to our use of `publishing` will be tested under that future change, which is a good way to avoid surprises later.
> Turn off a Gradle warning about Gradle 5.0 incompatibility

- build.gradle
This leverages [new Eclipse 4.8 (Photon) features that distinguish main code from test code](https://www.eclipse.org/photon/noteworthy/index.php#test-sources). An eventual fix to an [open feature request](https://github.com/gradle/gradle/issues/4802) might mean that Buildship starts doing this automatically, but for now we can do it ourselves.
If using an older Eclipse release, this change does nothing useful, but neither does it cause any harm.
> Categorize Eclipse sources as main vs. test

- buildSrc/build.gradle
- com.ibm.wala.cast.test/build.gradle
- com.ibm.wala.core.testdata/.gitignore
- com.ibm.wala.core.testdata/build.gradle
Recent WALA changes added several new downloads and build tasks related to the [Kawa Scheme language](https://www.gnu.org/software/kawa/). This pull request [reworks the Gradle build logic for those tasks](https://github.com/wala/WALA/commit/febf20145e5fe495764c9e476b6ef0c803fe32fe) to make better use of Gradle infrastructure: incremental builds, precise dependency management, build caching, integrated download support, etc. We get all of this in 28% fewer lines of build code thanks to factoring out repeated logic and leveraging existing Gradle facilities.
I’m also sneaking in a [small tweak](https://github.com/wala/WALA/commit/a7cef8e77abc91bab47d557ac4485fe4801fa175) to add declared outputs for a JNI-related test task. Without those declared outputs, this task could not be cached and …
> Improvements for Kawa- and JNI-related Gradle build tasks

- com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/propagation/ConstantKey.java
For cross language analysis using WALA, ``ConstantKey`` should be compared using both of the type and value to distinguish same constant values having different types due to the languages.
> Fix the comparison method for ConstantKey

- com.ibm.wala.cast/source/java/com/ibm/wala/cast/tree/CAstNode.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/tree/impl/CAstOperator.java
I'm in the process of attempting to support more python features.
I added the GLOBAL_DECL CAstNode to model the python global statement.
I also added the OP_NOT_IN CAstOperator to support the "not in" operation, as WALA would crash for any script including this operation.
> Added a CAstNode and a CAstOperator to support some wanted python features.

- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/util/AndroidAnalysisScope.java
Fixes inconsistent behavior of the exclusions argument.
Depending on the androidLib argument, setting exclusions to null
is either fine or raises an exception.
This patch makes exclusions truely optional for any case
when null is passed.
> Fixes #360  Exception in AndroidAnalysisScope 

- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/cha/MissingSuperTest.java
- com.ibm.wala.core/src/com/ibm/wala/classLoader/BytecodeClass.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/cha/ClassHierarchy.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/cha/ClassHierarchyFactory.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/cha/SeqClassHierarchyFactory.java
Build ClassHierarchy and replace any missing superclass
with the hierarchy root. Adds necessary changes to co-exist
with makeWithPhantom.
> Introduce ClassHierarchyFactory.makeWithRoot

- com.ibm.wala.core/src/com/ibm/wala/ssa/SSACFG.java
Don’t copy an entire array just to iterate over its elements. Instead, use `ArrayList::asList` to create a `List` backed by the existing array. Strictly speaking, these are not equivalent: the array-backed list is read-only, whereas the list copied from an array is modifiable.  But I strongly suspect that nobody is modifying the list used here anyway, so we may as well avoid the O(_n_) copy operation.
> Don’t copy an entire array just to iterate over its elements

- .idea/encodings.xml
IntelliJ IDEA 2018.3 added this automatically.  The encoding it represents is to _not_ add a byte-order mark (BOM) to new UTF-8 files. That’s what the existing files use, and is presumably what we want in the future.
> New IntelliJ IDEA project metadata file for file encoding settings

- com.ibm.wala.dalvik/META-INF/MANIFEST.MF
- com.ibm.wala.dalvik/build.gradle
- com.ibm.wala.dalvik/mvncentral.xml
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/dex/instructions/BinaryLiteralOperation.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/dex/instructions/BinaryOperation.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/dex/instructions/UnaryOperation.java
We don't want this dependency since Dalvik is not an AST-based frontend.  Removal required creating a couple of new enums in the Dalvik package.  This will break any clients that relied on the old CAst enum values, unfortunately, and I don't know a good way to make that a compile-time failure.  But we should still break this bad dependence.
/cc @reddr 
Issue pointed out in #393
> Remove com.ibm.wala.dalvik dependency on CAst

- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/impl/AndroidEntryPoint.java
Implement `ExecutionOrder.compareTo` in a simpler way, and correct some code that uses this method to not assume that `compareTo` always returns {-1, 0, +1}.
> ExecutionOrder.compareTo improvements

- com.ibm.wala.core/src/com/ibm/wala/classLoader/JarFileModule.java
Instead, create and return an `Iterator` instance that is really just a lightweight wrapper around the underlying `JarFile` entry `Enumerator`.
> Avoid creating an entire HashSet just to iterate

- com.ibm.wala.core/src/com/ibm/wala/ipa/summaries/LambdaMethodTargetSelector.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/summaries/LambdaSummaryClass.java
Fixes #419 
Move the cache from `LambdaSummaryClass` to `LambdaMethodTargetSelector` and make it non-static.  There should be only one instance of `LambdaMethodTargetSelector` per analysis so this should remove the leak.
Also remove use of `WeakHashMap` as in these cases the keys are reachable from the values via strong references.
> Fix leak in LambdaSummaryClass

- .travis.yml
- travis/install-gradle
- travis/script-gradle
The weekly Travis CI test tries to build each subproject in isolation, to test whether we have any implicit ordering dependencies among subprojects.  Part of that per-subproject work is to build the `javadoc`
task.  For most subprojects, that does what you’d expect:  build the Javadoc documentation for the subproject’s Java code.  For subprojects that build native components, though, there is no Java code and the `javadoc` task doesn’t even exist.
Fixes #424.
> Teach Travis CI that native components have no Javadoc

- buildSrc/src/main/groovy/verified-download.groovy
The build cache would have worked here on its own. Unfortunately I was accidentally disabling it due to an ill-conceived `upToDateWhen` call. See [Gradle issue #8564](https://github.com/gradle/gradle/issues/8584) for more discussion of [why I thought that call was useful](https://github.com/gradle/gradle/issues/8584#issuecomment-466451327), but [why it turned out to be harmful instead](https://github.com/gradle/gradle/issues/8584#issuecomment-466299895).
This should give second and subsequent rebuilds a nice performance boost. It might even speed up our Travis CI builds and make them less flaky, since we ask Travis CI to cache (snapshot and restore) the Gradle build cache across jobs.
That being said, the original `upToDateWhen` call was added to work around a specific problem, whereby …
> Allow the build cache to work for verified downloads

- com.ibm.wala.cast.java.ecj/src/com/ibm/wala/cast/java/translator/jdt/JDTJava2CAstTranslator.java
- com.ibm.wala.cast.js.rhino/source/com/ibm/wala/cast/js/translator/RhinoToAstTranslator.java
- com.ibm.wala.cast.js.test/harness-src/com/ibm/wala/cast/js/test/CAstDumper.java
- com.ibm.wala.cast.js/source/com/ibm/wala/cast/js/ipa/callgraph/ArgumentSpecialization.java
- com.ibm.wala.cast.js/source/com/ibm/wala/cast/js/ipa/callgraph/correlations/extraction/ClosureExtractor.java
- com.ibm.wala.cast.js/source/com/ibm/wala/cast/js/ipa/callgraph/correlations/extraction/CorrelatedPairExtractionPolicy.java
- com.ibm.wala.cast.js/source/com/ibm/wala/cast/js/ipa/callgraph/correlations/extraction/NodePos.java
- com.ibm.wala.cast.js/source/com/ibm/wala/cast/js/translator/JavaScriptTranslatorToCAst.java
- com.ibm.wala.cast.js/source/com/ibm/wala/cast/js/translator/PropertyReadExpander.java
- com.ibm.wala.cast.test/harness-src/java/com/ibm/wala/cast/test/TestCAstPattern.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/ir/translator/AstTranslator.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/ir/translator/ConstantFoldingRewriter.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/ir/translator/TranslatorToCAst.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/tree/CAst.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/tree/CAstControlFlowMap.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/tree/CAstLeafNode.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/tree/CAstNode.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/tree/impl/CAstImpl.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/tree/impl/CAstOperator.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/tree/impl/CAstValueImpl.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/tree/rewrite/CAstRewriter.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/tree/visit/CAstVisitor.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/util/CAstFunctions.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/util/CAstPrinter.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/util/CAstToDOM.java
Previously access to AST children was provided via `getChildCount()` and `getChild(int)` methods.  These effectively treated the children as some sort of array-like sequence, but with none of the API conveniences that a proper Java array or `Collection` offers.  Exposing a node’s children as a standard `List` makes it easy for us to write loops over children, create `Iterator`s over children, use bulk operations like `Collections.addAll`, etc.
Most such `List`s of children will actually still be arrays, wrapped up as `ArrayList`. One might fear that this extra level of encapsulation would harm performance. However, I found no consistent performance change across 20 trials of the `com.ibm.wala.core.tests.callGraph*` tests.
> Expose AST node children as overt List rather than covert array

- build.gradle
- com.ibm.wala.cast.java.test.data/build.gradle
- com.ibm.wala.cast.java.test/build.gradle
- com.ibm.wala.cast.js.html.nu_validator/build.gradle
- com.ibm.wala.cast.js.nodejs.test/build.gradle
- com.ibm.wala.cast.js.nodejs/build.gradle
- com.ibm.wala.cast.js.rhino.test/build.gradle
- com.ibm.wala.cast.js.test.data/build.gradle
- com.ibm.wala.cast.js.test/build.gradle
- com.ibm.wala.cast.js/build.gradle
- com.ibm.wala.cast.test/build.gradle
- com.ibm.wala.cast/build.gradle
- com.ibm.wala.core.testdata/build.gradle
- com.ibm.wala.core.tests/build.gradle
- com.ibm.wala.core/build.gradle
- com.ibm.wala.dalvik.test/build.gradle
- com.ibm.wala.dalvik/build.gradle
- com.ibm.wala.ide.jdt.test/build.gradle
- com.ibm.wala.ide.jsdt.tests/build.gradle
- com.ibm.wala.util/build.gradle
The main [Gradle task configuration avoidance page](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) recommends using `tasks.named('foo').configure { ... }` to add lazy configuration logic to an existing task named `foo`. That was indeed the best option when the task configuration avoidance APIs first appeared.
However, [additional `named(...)` overloads were added later](https://github.com/gradle/gradle/pull/6688) that take the configuration closure as a final argument. Thus, `tasks.named('foo').configure { ... }` can now be simplified to `tasks.named('foo') { ... }`.
This change does not introduce any deep shifts in how the build happens. It is merely a syntactic-sugar-level refactoring to replace a chained sequence of two method calls with a single call that …
> Use an overload to configure tasks more tersely

- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/callGraph/CallGraphTest.java
- com.ibm.wala.core/src/com/ibm/wala/analysis/pointers/BasicHeapGraph.java
- com.ibm.wala.core/src/com/ibm/wala/cfg/AbstractCFG.java
- com.ibm.wala.core/src/com/ibm/wala/dataflow/IFDS/BackwardsSupergraph.java
- com.ibm.wala.core/src/com/ibm/wala/dataflow/IFDS/ICFGSupergraph.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/pruned/PrunedCallGraph.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/cfg/AbstractInterproceduralCFG.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/cfg/PrunedCFG.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/slicer/PDG.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/slicer/SDGSupergraph.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/slicer/thin/CISDG.java
- com.ibm.wala.core/src/com/ibm/wala/ssa/SSACFG.java
- com.ibm.wala.core/src/com/ibm/wala/ssa/analysis/ExplodedControlFlowGraph.java
- com.ibm.wala.scandroid/source/org/scandroid/domain/IFDSTaintDomain.java
- com.ibm.wala.scandroid/source/org/scandroid/prefixtransfer/PrefixTransferGraph.java
- com.ibm.wala.scandroid/source/org/scandroid/prefixtransfer/UriPrefixTransferGraph.java
- com.ibm.wala.util/src/com/ibm/wala/util/collections/ObjectArrayMapping.java
- com.ibm.wala.util/src/com/ibm/wala/util/graph/AbstractGraph.java
- com.ibm.wala.util/src/com/ibm/wala/util/graph/GraphSlicer.java
- com.ibm.wala.util/src/com/ibm/wala/util/graph/NodeManager.java
- com.ibm.wala.util/src/com/ibm/wala/util/graph/impl/BasicNodeManager.java
- com.ibm.wala.util/src/com/ibm/wala/util/graph/impl/BasicOrderedMultiGraph.java
- com.ibm.wala.util/src/com/ibm/wala/util/graph/impl/DelegatingGraph.java
- com.ibm.wala.util/src/com/ibm/wala/util/graph/impl/DelegatingNumberedNodeManager.java
- com.ibm.wala.util/src/com/ibm/wala/util/graph/impl/ExtensionGraph.java
- com.ibm.wala.util/src/com/ibm/wala/util/graph/impl/SlowNumberedNodeManager.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/MutableMapping.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/OffsetOrdinalSetMapping.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/OrdinalSetMapping.java
This allows expressing some graph operations more succinctly by using the Java stream APIs.  However, be cautious: performance implications of Java streams are nontrivial.
For some folks, Java streams have a reputation for poor performance. The reality is more nuanced.  Yes, they can encourage needless abstraction, adding layers of indirect objects, making simple tasks unnecessarily slow.  But they can also speed things up by encouraging use of higher-level bulk operations.  Processing stream elements in parallel can also either boost or harm performance, depending on how many items are being manipulated and much potential concurrency is available.  So … it’s complicated.
> Add NodeManager stream API

- com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/pruned/PrunedCallGraph.java
In `PrunedCallGraph`, require that `keep` (the set of nodes to be kept) be a subset of the nodes in the unpruned graph.  Check for this at construction time, and raise an exception if violated.
The caller could potentially change either the `keep` set or the unpruned graph after constructing the `PrunedCallGraph` instance.  If they do that, then PrunedCallGraph might break, and the caller gets to keep all the pieces.  We could be rechecking the “subset” relationship in each and every place it is assumed to hold, but that seems excessive.  So instead we just add a big warning in the constructor’s Javadoc documentation.
See <https://github.com/wala/WALA/pull/427#discussion_r259913855> for the concluding piece of the discussion that led us to enact this “subset” requirement.
> In PrunedCallGraph, require that kept nodes be subset of unpruned graph

- com.ibm.wala.dalvik.test/build.gradle
- travis/install-gradle
Two small tweaks to our Gradle integration of Google Java Format (GJF):
- Exclude generated Java code from GJF rules
- Use the full name of a GJF task
> Small Gradle tweaks for Google Java Format

- build.gradle
This maintains our existing effort to leverage the [Gradle task configuration avoidance APIs](
https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) as much as possible.
> Avoid configuring installGitHooks task unless needed

- build.gradle
- travis/install-gradle
- travis/script-gradle
Per <https://docs.travis-ci.com/user/job-lifecycle/>, the `install` stage should "install any dependencies required", while the `script` stage should "run the build script".
For our purposes, it makes sense to treat WALA's many assorted extra download tasks as `install`-stage dependencies: `downloadAndroidSdk`, `downloadBcel`, `downloadJavaCup`, etc.  If any of these fails, I believe Travis CI will treat that job as "errored" rather than "failed".  That might make it easier for us to quickly recognize when the problem was a transient inability to download (which happens often).
Having moved pre-build downloads into the `install` stage, it makes sense for the `script` stage to encompass both building WALA and running all of its various checks/tests.  In particular, `verifyGoogleJavaFormat` …
> Move responsibilities among Travis CI lifecycle scripts

- .idea/scopes/WALA_Controlled.xml
- com.ibm.wala.cast.java.test/src/com/ibm/wala/cast/java/test/JavaIRTests.java
- com.ibm.wala.cast.js.rhino/source/com/ibm/wala/cast/js/translator/RhinoToAstTranslator.java
- com.ibm.wala.cast.js/source/com/ibm/wala/cast/js/ipa/callgraph/correlations/extraction/CorrelatedPairExtractionPolicy.java
- com.ibm.wala.core.testdata/src/arraybounds/NotInBound.java
- com.ibm.wala.core.testdata/src/bug144/A.java
- com.ibm.wala.core.testdata/src/cfg/exc/intra/FieldAccess.java
- com.ibm.wala.core.testdata/src/cfg/exc/intra/FieldAccessDynamic.java
- com.ibm.wala.core.testdata/src/demandpa/TestFieldsHarder.java
- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/exceptionpruning/ExceptionAnalysis2EdgeFilterTest.java
- com.ibm.wala.core.tests/src/com/ibm/wala/demandpa/driver/CompareToZeroOneCFADriver.java
- com.ibm.wala.core.tests/src/com/ibm/wala/demandpa/driver/TestAgainstSimpleDriver.java
- com.ibm.wala.core/src/com/ibm/wala/analysis/arraybounds/ConditionNormalizer.java
- com.ibm.wala.core/src/com/ibm/wala/classLoader/JavaLanguage.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/slicer/HeapReachingDefs.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/slicer/SliceFunctions.java
- com.ibm.wala.core/src/com/ibm/wala/util/ssa/ParameterAccessor.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/classLoader/DexCFG.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/classLoader/DexIMethod.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/dex/instructions/BinaryLiteralOperation.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/dex/instructions/BinaryOperation.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/dex/instructions/UnaryOperation.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/androidModel/parameters/FlatInstantiator.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/androidModel/parameters/Instantiator.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/util/AndroidSettingFactory.java
- com.ibm.wala.ide.jdt.test/source/com/ibm/wala/demandpa/driver/DemandCastChecker.java
- com.ibm.wala.scandroid/source/org/scandroid/util/EntryPoints.java
- com.ibm.wala.shrike/src/com/ibm/wala/shrikeCT/ClassWriter.java
- com.ibm.wala.shrike/src/com/ibm/wala/shrikeCT/ConstantPoolParser.java
Updated inspections in IntelliJ IDEA 2019.1 found some minor code nits that previously went unnoticed. These fixes are not specific to IntelliJ IDEA 2019.1, though: we can merge them now without waiting for the IntelliJ IDEA 2019.1 project configuration updates in #443.
> Fix small code nits detected by IntelliJ IDEA 2019.1 inspections

- .travis.yml
- travis/before-cache-gradle
Fixes #446 
Beyond caching this directory, update the cleanup script to remove a few other files inside the Gradle cache that seem to change needlessly between runs.  If we don't remove these files, Travis is forced to re-upload on each build, which takes about a minute.  I've confirmed by repeatedly running a build job that deleting these files does not put the cache in an inconsistent state that breaks future builds.  I also filed gradle/gradle#9175 as a start at trying to get some root cause issues fixed.
> cache the p2asmaven directory on Travis

- .idea/externalDependencies.xml
"Required" here is interpreted broadly.  Strictly speaking, one doesn't _need_ to have the Google Java formatter, Git integration, or JUnit integration.  But these are strongly recommended, so let's try requiring them and see if anyone complains.
A more strict treatment of "required" would list only the Gradle plugin and the version of IntelliJ IDEA itself.  Regarding the latter, unfortunately I haven't actually been able to get IntelliJ IDEA to complain no matter what "min-version" I list for the IDE itself.  Not sure what I'm doing wrong here.
> List some required IntelliJ IDEA plugins

- .idea/scopes/WALA_Controlled.xml
JavaScript files in `com.ibm.wala.cast.js.nodejs/dat/core-modules` are downloaded and moved into place by the `unpackNodeJSLib` Gradle task. Running IntelliJ IDEA inspections on these files is not useful, since we don't control them anyway.
> Exclude node.js lib from "WALA-Controlled" file scope

- com.ibm.wala.dalvik.test/build.gradle
Fixes #455, wherein Georgia Tech downloads were failing. Even if those faillures were only temporary, Maven should be a more reliable long-term source for this file.
Furthermore, extracting this file from a Maven-tracked artifact means that we can use Gradle’s standard mechanisms for declaring dependencies and resolving those dependencies in online repositories like Maven Central. Nice! I wish more of WALA’s required downloads were available from Maven repositories as well.
The rebuilt `downloadSampleCup` task looks like it should be a `Copy` task, since all it does is extract a file from a Jar archive. However, a `Copy` task will always treat the entire destination directory as its task outputs. This specific task is only adding one file to an existing directory; the rest of the …
> Download `parser.cup` from Maven, not Georgia Tech

- .travis.yml
If we use the Xenial Ubuntu release we get JDK 11 by default.  Mac JDK 11 builds are still broken, so we disable them for now.
> Fix Linux OpenJDK 11 builds and disable Mac OpenJDK11

- build.gradle
- com.ibm.wala.core.testdata/build.gradle
- com.ibm.wala.core.tests/build.gradle
A `Copy` or `Sync` task always treats its entire destination directory as the task’s output.  When we’re copying or extracting a single file, it is often more useful to treat just that one file as the output.  This requires turning the `Copy` or `Sync` task into a generic task that calls the `Project.copy` method.
Also for these tasks, if task _A_’s inputs are given as some other task _B_, that implicitly does two useful things: (1) it treats _B_’s outputs as _A_’s inputs, and (2) it establishes a dependency of _A_ upon _B_.  We can’t use this everywhere, but where we can, it’s a nice simplification.
>  Be more precise about Gradle Cop and Sync tasks’ inputs and outputs

- .travis.yml
The underlying Travis issue is [fixed now](https://travis-ci.community/t/install-of-openjdk11-is-failing-again/3061/27).
> Reenable Mac JDK 11 Travis builds

- gradle/wrapper/gradle-wrapper.properties
Nothing interesting for us in Gradle 5.3._x_ or 5.4._x_, but it's good practice to keep current.
> Update Gradle to version 5.4.1

- com.ibm.wala.cast/source/java/com/ibm/wala/cast/ipa/callgraph/ScriptEntryPoints.java
Using `Math.min(0, other)` as the length of an array was surely not intended here. If `other` is zero or positive, then this would allocate a 0-element array. If `other` is negative, then this would fail after trying to allocate a negative-sized array.
Evidently we have no tests that trigger this code.  I don’t feel well-informed enough to add a suitable test myself. I’m guessing what the correct size calculation should be based on context, but this is presumably still untested.
> Fix likely bug in array size calculation

- build.gradle
- com.ibm.wala.cast.java.ecj/build.gradle
- com.ibm.wala.cast.java.ecj/gradle.properties
- com.ibm.wala.cast.java.test/build.gradle
- com.ibm.wala.cast.java/build.gradle
- com.ibm.wala.cast.java/gradle.properties
- com.ibm.wala.cast.js.rhino.test/build.gradle
- com.ibm.wala.cast.js.rhino/build.gradle
- com.ibm.wala.cast.js.rhino/gradle.properties
- com.ibm.wala.cast.js.test/build.gradle
- com.ibm.wala.cast.js/build.gradle
- com.ibm.wala.cast.js/gradle.properties
- com.ibm.wala.cast.test/build.gradle
- com.ibm.wala.cast/build.gradle
- com.ibm.wala.cast/gradle.properties
- com.ibm.wala.core.tests/build.gradle
- com.ibm.wala.core/build.gradle
- com.ibm.wala.core/gradle.properties
- com.ibm.wala.dalvik.test/build.gradle
- com.ibm.wala.dalvik/build.gradle
- com.ibm.wala.dalvik/gradle.properties
- com.ibm.wala.scandroid/build.gradle
- com.ibm.wala.scandroid/gradle.properties
- com.ibm.wala.shrike/build.gradle
- com.ibm.wala.shrike/gradle.properties
- com.ibm.wala.util/build.gradle
- com.ibm.wala.util/gradle.properties
- gradle-mvn-push.gradle
- gradle.properties
We should use Gradle for creating Maven artifacts, to enable deprecation of WALA Maven builds.  I couldn't get proper artifacts built with the maven-publish plugin, so this PR switches to the maven plugin.  It makes use of the [gradle-mvn-push](https://github.com/chrisbanes/gradle-mvn-push/blob/master/gradle-mvn-push.gradle) script, with slight modifications.
I've tested locally and successfully installed artifacts to the local M2 repository.  Once this lands, I plan to enable uploading of snapshots on every successful CI build of master, so that will give us some testing on CI.
To test locally, run `./gradlew install` and then check the contents of `~/.m2/repository/com/ibm/wala` for the artifacts.
> Switch to maven Gradle plugin

- .travis.yml
- build.gradle
- com.ibm.wala.cast.test/build.gradle
- travis/script-gradle
Java compilation uses ECJ instead of the default Java compiler if the `javaCompiler` project property is set to either `ecj` or `eclipse` (case-insensitive).  For example, use `-PjavaCompiler=ecj` on the Gradle command line or add `javaCompiler=ecj` to the `gradle.properties` file. Fixes #466.
When using ECJ, diagnostics use the same per-subproject settings that Eclipse uses, as stored in `*/.settings/org.eclipse.jdt.core.prefs` files.
In Travis CI, use ECJ for static checks only. [Six of WALA’s JUnit tests fail when using ECJ as the Java compiler.](https://travis-ci.org/wala/WALA/jobs/528368589) [It’s not clear that anyone really cares whether ECJ-compiled WALA runs correctly, though.](https://github.com/wala/WALA/issues/466#issuecomment-489456520) What we do care about is that WALA …
> Optionally use ECJ in Gradle builds

- .idea/inspectionProfiles/No_Back_Sliding.xml
- com.ibm.wala.cast.js/source/com/ibm/wala/cast/js/ipa/callgraph/correlations/extraction/CorrelatedPairExtractionPolicy.java
- com.ibm.wala.cast/source/java/com/ibm/wala/cast/tree/impl/CAstControlFlowRecorder.java
- com.ibm.wala.core/src/com/ibm/wala/dataflow/IFDS/TabulationSolver.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/propagation/cfa/ZeroXInstanceKeys.java
- com.ibm.wala.core/src/com/ibm/wala/util/PrimitiveAssignability.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ipa/callgraph/androidModel/AndroidModelClass.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/util/AndroidManifestXMLReader.java
- com.ibm.wala.scandroid/source/org/scandroid/domain/IFDSTaintDomain.java
- com.ibm.wala.scandroid/source/org/scandroid/flow/InflowAnalysis.java
- com.ibm.wala.scandroid/source/org/scandroid/flow/OutflowAnalysis.java
- com.ibm.wala.scandroid/source/org/scandroid/prefixtransfer/PrefixTransferGraph.java
- com.ibm.wala.scandroid/source/org/scandroid/prefixtransfer/UriPrefixTransferGraph.java
- com.ibm.wala.shrike/src/com/ibm/wala/shrike/cg/OfflineDynamicCallGraph.java
- com.ibm.wala.util/src/com/ibm/wala/util/collections/MapUtil.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/BitVectorRepository.java
`Map.getOrDefault` seems like a clear win when the default value is a constant (e.g., `-1` or `null`).
`Map.computeIfAbsent` adds a lambda, which might be a performance concern. `Map.computeIfAbsent` *can* be implemented in a manner that turns two lookups (`Map.get` followed by `Map.put`) into just one, which might help performance. There is no hard *requirement* that `Map.computeIfAbsent` incorporate that optimization, though.
To assess any performance impact empirically, I performed 20 repetitions of the `com.ibm.wala.core.tests.callGraph` tests before and after the commits in this pull request:
|Revision|Mean Execution Time (M:SS.SS)|
|-|-|
|before|6:31.23|
|after|6:30.75|
Inter-trial variance (not shown here) is significantly larger than the small difference in means shown above. More …
> Leverage Java 8 high-level Map methods

- change-version.py
- gradle-mvn-push.gradle
* Update `change-version.py` to also update `gradle.properties`
* Fix `needsSigning()` in `gradle-mvn-push.gradle` to match on `name` rather than using `hasTask` (which requires the fully-qualified task name)
> Couple of fixes for build scripts

- .idea/inspectionProfiles/No_Back_Sliding.xml
Some of these inspections check for problems we would truly want to avoid.  For these, it is good to know that as of now, none of those problems are present.  If future changes create instances of these problems, IntelliJ IDEA will find them.
Some of these inspections may check for “problems” that we disagree with or just don’t care about.  No such instances appear in WALA now, but if any arise in the future, then we can at least be aware of them and make a well-considered decision to either fix the problems or disable the inspections that we disagree with.
Lastly, a few inspections mostly involve replacing various repetitive constructs with uses of the stream API.  Streams can hurt performance if used naively, though, so I’m not convinced we want to apply these changes broadly. These …
> enable many more IntelliJ IDEA inspections

- build.gradle
- travis/script-gradle
Create a common `linters` task for extra checkers. These extra checkers are things we want to test for, but which are not Java JUnit tests. @msridhar has expressed a preference in the past for not simply adding these extra checks as dependencies of the `check` task. So instead we now have a distinct `linters` task as a single collection point for these other checks.
Also add a `shellCheck` task: a [`shellcheck`](https://www.shellcheck.net/)-based linter for all shell scripts. This `shellCheck` task assumes that shell scripts are OK if `shellcheck` is absent. For example, Travis CI has `shellcheck` preinstalled on Linux images, but not on macOS images. So our Travis CI Linux jobs will lint-check shell scripts, but on macOS we just optimistically assume that everything is OK. `shellcheck` …
> Add "linters" and "shellCheck" tasks

- com.ibm.wala.core/src/com/ibm/wala/dataflow/IFDS/TabulationSolver.java
We want to make this code easy to enable simply by changing `DEBUG_LEVEL`, even if it is dead with `DEBUG_LEVEL` at its standard setting.
> Allow dead code due to DEBUG_LEVEL setting

- .idea/inspectionProfiles/No_Back_Sliding.xml
- com.ibm.wala.core/src/com/ibm/wala/analysis/reflection/GetMethodContextSelector.java
- com.ibm.wala.core/src/com/ibm/wala/ssa/IR.java
- com.ibm.wala.core/src/com/ibm/wala/ssa/SSAIndirectionData.java
- com.ibm.wala.core/src/com/ibm/wala/types/TypeReference.java
- com.ibm.wala.core/src/com/ibm/wala/types/annotations/TypeAnnotation.java
- com.ibm.wala.util/src/com/ibm/wala/fixpoint/AbstractVariable.java
- com.ibm.wala.util/src/com/ibm/wala/fixpoint/IFixedPointSolver.java
Use `{@code …}` in Javadoc, not `<tt>…</tt>`. Javadoc from JDK 1.8 allows either, but more recent JDK releases may disallow `<tt>…</tt>`.
Remove unnecessary Javadoc links to containing class.
Enable additional IntelliJ IDEA Javadoc inspections that find nothing.
> Javadoc fixes and IntelliJ IDEA Javadoc inspection updates

- com.ibm.wala.core.testdata/build.gradle
Hoist some jar files out of `com.ibm.wala.core.testdata/build`. The `com.ibm.wala.core.testdata/build.properties` file that Eclipse uses expects to find these jar files directly in the `com.ibm.wala.core.testdata` directory, not in the `com.ibm.wala.core.testdata/build` subdirectory.
Let Gradle generate some `clean*` tasks automatically. Previously we had to (or thought we had to) create these ourselves, but Gradle actually creates them correctly on its own.
> Relocate some jar files and simplify "clean*" tasks

- com.ibm.wala.core.testdata/src/lambda/MethodRefs.java
- com.ibm.wala.core.testdata/src/lambda/ParamsAndCapture.java
- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/callGraph/LambdaTest.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/summaries/LambdaSummaryClass.java
- com.ibm.wala.dalvik.test/source/com/ibm/wala/dalvik/test/util/Util.java
This PR fixes two issues with handling of lambdas in WALA:
* handling of method references to constructors (#445)
* handling of cases where the lambda both has parameters and captures values
See the new test cases `testMethodRefs()` and `testParamsAndCapture()`.
As part of the fixes, we significantly refactor the logic for generating trampoline methods in `LambdaSummaryClass` for ease of understanding.
Fixes #445
> Fix two bugs with handling of lambdas

- .idea/inspectionProfiles/No_Back_Sliding.xml
- com.ibm.wala.cast.java.test.data/src/foo/QualifiedNames.java
- com.ibm.wala.core.testdata/build.gradle
- com.ibm.wala.core.tests/src/com/ibm/wala/examples/analysis/SimpleThreadEscapeAnalysis.java
- com.ibm.wala.core/src/com/ibm/wala/classLoader/SourceDirectoryTreeModule.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/propagation/SSAPropagationCallGraphBuilder.java
- com.ibm.wala.core/src/com/ibm/wala/ssa/SSABuilder.java
- com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/ssa/DexSSABuilder.java
- com.ibm.wala.shrike/src/com/ibm/wala/shrikeCT/StackMapTableWriter.java
- com.ibm.wala.util/src/com/ibm/wala/util/graph/GraphIntegrity.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/BitVector.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/BitVectorIntSet.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/Bits.java
- com.ibm.wala.util/src/com/ibm/wala/util/intset/OffsetBitVector.java
Prefer operator assignments where possible, such as `x += y` instead of `x = x + y`.
Enable more assignment-related IntelliJ IDEA inspections
In Gradle code, remove an unused assignment, and clean up an inconsistency regarding property setters versus standard methods.
> Minor code clean-ups relating to assignments

- build.gradle
Collect all Javadoc-related material under one new section. Move some Eclipse-related material into the existing Eclipse section. Move some Google Java Format material into the existing linter section.
Nothing very exciting here. This is preparatory clean-up before enacting a few more interesting Gradle changes.
> Reorganize sections of top-level Gradle build script

- build.gradle
- buildSrc/build.gradle
- com.ibm.wala.cast.java.ecj/build.gradle
- com.ibm.wala.cast.java.test/build.gradle
- com.ibm.wala.cast.java/build.gradle
- com.ibm.wala.cast.js.html.nu_validator/build.gradle
- com.ibm.wala.cast.js.nodejs.test/build.gradle
- com.ibm.wala.cast.js.nodejs/build.gradle
- com.ibm.wala.cast.js.rhino.test/build.gradle
- com.ibm.wala.cast.js.rhino/build.gradle
- com.ibm.wala.cast.js.test/build.gradle
- com.ibm.wala.cast.js/build.gradle
- com.ibm.wala.cast.test/build.gradle
- com.ibm.wala.cast.test/smoke_main/build.gradle
- com.ibm.wala.cast.test/xlator_test/build.gradle
- com.ibm.wala.cast/build.gradle
- com.ibm.wala.core.tests/build.gradle
- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/cha/MissingMethodRefTest.java
- com.ibm.wala.core/build.gradle
- com.ibm.wala.dalvik.test/build.gradle
- com.ibm.wala.dalvik/build.gradle
- com.ibm.wala.ide.jdt.test/build.gradle
- com.ibm.wala.ide.jdt/build.gradle
- com.ibm.wala.ide.jsdt.tests/build.gradle
- com.ibm.wala.ide.jsdt/build.gradle
- com.ibm.wala.ide.tests/build.gradle
- com.ibm.wala.ide/build.gradle
- com.ibm.wala.scandroid/build.gradle
- com.ibm.wala.shrike/build.gradle
The `java-library` plugin distinguishes dependencies needed only for a library’s internal implementation from dependencies that form part of a library’s external API. A library’s implementation dependencies are not transitively made available to other components that depend on that library. This keeps classpaths shorter and helps reduce recompilation. See [the `java-library` plugin documentation](https://docs.gradle.org/current/userguide/java_library_plugin.html) for more information.
I took an empirical approach to determining which dependencies are implementation dependencies and which are API dependencies. In general, one should prefer the more restrictive implementation categorization wherever possible. What I’ve done here is to use implementation dependencies everywhere I could, and …
> Convert to java-library Gradle plugin

- build.gradle
The `tasks.withType(Javadoc).configureEach` closure appearing [slightly earlier](https://github.com/wala/WALA/blob/667dd100e6d8b82451aa0f3e7deffea485f4cd92/build.gradle#L176) will take care of setting the appropriate `Xdoclint` and quietness options. That works even though this configuration closure appeared before the `aggregatedJavadocs` task was registered, thanks to the magic of Gradle’s on-demand task configuration system.
> Remove redundant Javadoc task configuration

- gradle-mvn-push.gradle
`version` and `group` were already set in the top-level `build.gradle`, and are inherited by all subprojects.
The `com.ibm.wala.*-1.5.4-SNAPSHOT.pom` files installed under `~/.m2` are unaffected by this change.
> Remove redundant assignments to project version and group

- com.ibm.wala.cast.java.test.data/src/SimpleCalls.java
- com.ibm.wala.cast.java.test.data/src/bugfixes/VarDeclInSwitch.java
- com.ibm.wala.cast.java.test.data/src/foo/QualifiedNames.java
- com.ibm.wala.cast.java.test.data/src/javaonepointfive/EnumSwitch.java
- com.ibm.wala.cast.java.test.data/src/javaonepointfive/ExplicitBoxingTest.java
- com.ibm.wala.core.testdata/src/slice/TestCD4.java
- com.ibm.wala.core.testdata/src/string/SimpleStringOps.java
Test code often does things that we would not consider ideal coding practice, for the sake of keeping tests small, simple, and probative.
> Suppress some IntelliJ IDEA warnings in test code

- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/shrike/DynamicCallGraphTestBase.java
The `Java.setArgs` and `Java.setJvmargs` APIs claim to be deprecated in output from tests that use them.
> Modernize use of Ant Java task’s argument APIs

- README-Gradle.md
The process for setting up WALA in IntelliJ IDEA became simpler in commit 1699567aa153bd9b07512e85b2f7a18998ff327e.  That commit claimed that "'README-Gradle.md' has been updated to reflect the simpler procedure for getting started with WALA in IntelliJ IDEA", but in fact no such documentation update was made.  This commit applies those forgotten changes.
> Simplify IntelliJ IDEA setup instructions

- buildSrc/build.gradle
Nothing interesting for us in this version, but it’s good practice to keep current, especially given that this is a new major release.
> Update Gradle download plugin to v4.0.0

- buildSrc/src/main/groovy/verified-download.groovy
WALA downloads many things, and some of those are from slow or flaky servers that chronically time out.  The [recent update of our Gradle download plugin](https://github.com/wala/WALA/pull/526) finally gives us a tidy way to cope with this:  retrying failed downloads.
We could tweak this for each individual download task, but I think that's overkill.  Let's start by simply retrying *any* failed download up to five times.
> Retry failed downloads up to five times

- com.ibm.wala.util/src/com/ibm/wala/util/intset/BitVectorRepository.java
`Map.computeIfAbsent` can do the same thing we need here, but might only perform one `Map` lookup instead of two (if implemented efficiently).
> Suppress suggestion to use Map.computeIfAbsent

- build.gradle
Also add an explicit return type to help IntelliJ IDEA’s Gradle checkers understand what it returns.  Apparently even in its original form, those checkers were unable to infer a return type more specific than `Object`.
> Reimplement a function in a stream’y, functional style

- .idea/gradle.xml
These changes were not prompted by any explicit settings change from me. They appear to simply be a change in what project information IntelliJ IDEA 2019.2 stores explicitly versus earlier IntelliJ IDEA versions.
> Minor project metadata updates for IntelliJ IDEA 2019.2

- .idea/inspectionProfiles/No_Back_Sliding.xml
Commit 307e642e82697a47673d194ad73643ad83074231 removed the last remaining violation of this style check.
> Warn about raw types used instead of generics

- build.gradle
- com.ibm.wala.cast.test/xlator_test/build.gradle
- com.ibm.wala.cast/cast/build.gradle
- gradle/wrapper/gradle-wrapper.properties
Update Gradle and the p2-as-Maven Gradle plugin to their respective latest releases.
Indent two `build.gradle` scripts using tabs as our other `build.gradle` scripts already do.
> Gradle 5.6 and minor tweaks

- com.ibm.wala.util/src/com/ibm/wala/util/intset/MultiModalIntVector.java
Near as I can tell, `size` here is never larger than `MAX_SIZE`, which means that this integer division would almost always be 0.  Presumably it was intended to be a floating-point ratio measuring how close `size` is to `MAX_SIZE`.
> Change a questionable integer division to double

- com.ibm.wala.cast.test/smoke_main/.gitignore
Crash logs shouldn’t arise when tests are passing, but if a regression causes `smoke_main` to fail, then these crash logs will appear. We won’t ever want to check them into git, though, so git should ignore them.
> Have git ignore JVM crash logs

- com.ibm.wala.cast.js.test/harness-src/com/ibm/wala/cast/js/test/TestSimpleCallGraphShape.java
- com.ibm.wala.core.tests/build.gradle
- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/callGraph/KawaCallGraphTest.java
- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/util/SlowTests.java
837160d2c35f9655828bf1aa4e470accbe719d95 adds the ability to categorize specific JUnit tests or test classes as slow, and to optionally exclude this category when running Gradle tests:
* To mark a test method or class as slow, annotate it with
`@org.junit.experimental.categories.Category(com.ibm.wala.core.tests.util.SlowTests.class)`.
* To exclude tests categorized as slow, add `-PexcludeSlowTests` to your Gradle command line, or use [any other method you prefer](https://docs.gradle.org/current/userguide/build_environment.html#sec:project_properties) to set the `excludeSlowTests` Gradle project property.
1418e0dbd6c8029c32b6212625c330a2194f505a applies this `SlowTests` category to several tests based on my empirical measurements of test execution times. See that commit’s message for more …
> Mark and optionally exclude slow tests

- com.ibm.wala.core/src/com/ibm/wala/properties/WalaProperties.java
This debug warning prints much more often after #447, which can cause a lot of log noise.  Only print the warning when the `wala.properties` file actually has an invalid directory in it.
> Only print warning when directory is non-null

- com.ibm.wala.cast.js.rhino.test/launchers/JsViewerDriver.launch
- com.ibm.wala.cast.js.rhino.test/launchers/TestForInLoopHackRhino.launch
- com.ibm.wala.cast.js.rhino.test/launchers/TestMozillaBugPagesRhino.launch
- com.ibm.wala.cast.js.rhino.test/launchers/com.ibm.wala.cast.js.rhino.test-JUnit.launch
- com.ibm.wala.cast.js.test/.launchConfigurations/com.ibm.wala.cast.js.test-JUnit.launch
- com.ibm.wala.cast.test/.launchConfigurations/com.ibm.wala.cast.test-JUnit.launch
- com.ibm.wala.core.tests/launchers/ConstructAllIRs.launch
- com.ibm.wala.core.tests/launchers/CountParameters.launch
- com.ibm.wala.core.tests/launchers/GetLoadedFields.launch
- com.ibm.wala.core.tests/launchers/JavaViewerDriver.launch
- com.ibm.wala.core.tests/launchers/PDFCallGraph.launch
- com.ibm.wala.core.tests/launchers/PDFControlDependenceGraph.launch
- com.ibm.wala.core.tests/launchers/PDFSDG.launch
- com.ibm.wala.core.tests/launchers/PDFSlice.launch
- com.ibm.wala.core.tests/launchers/PDFTypeHierarchy.launch
- com.ibm.wala.core.tests/launchers/PDFWalaIR.launch
- com.ibm.wala.core.tests/launchers/wala.core short profile (non-windows).launch
- com.ibm.wala.core.tests/launchers/wala.core short profile.launch
- com.ibm.wala.core.tests/launchers/wala.core.launch
- com.ibm.wala.ide.jdt.test/launchers/ECJJavaIRTest.launch
- com.ibm.wala.ide.jdt/source/com/ibm/wala/cast/java/translator/jdt/JDTSourceModuleTranslator.java
- com.ibm.wala.ide.jdt/source/com/ibm/wala/ide/util/JdtUtil.java
- com.ibm.wala.ide.tests/launchers/IFDSExplorerExample.launch
- com.ibm.wala.ide.tests/launchers/SWTCallGraph - OCaml - ipascal.launch
- com.ibm.wala.ide.tests/launchers/SWTCallGraph.launch
- com.ibm.wala.ide.tests/launchers/SWTPointsTo.launch
- com.ibm.wala.ide.tests/launchers/SWTTypeHierarchy.launch
1. Manually remove some unnecessary warning suppressions.
1. Implicitly remove the `CLASSPATH_PROVIDER` attribute from all launchers.
> Minor updates for Eclipse 2019-09

- .travis.yml
Several minor clean-ups to the configuration of Travis CI jobs:
- Activate [Travis CI build config validation](https://blog.travis-ci.com/2019-10-24-build-config-validation).
- Replace `matrix:` Travis CI configuration key alias with standard `jobs:` key.
- Assume that all builds use the `java` language environment except where overriden for Maven builds.
- Assume that all builds use Gradle unless overridden to use Maven.
- Assume that all macOS builds use XCode 8.3.
> Travis CI build jobs cleanup

- .idea/codeStyles/Project.xml
Nothing interesting here; just a minor change to how IntelliJ IDEA
2019.2 stores some project metadata.
> IntelliJ IDEA 2019.2 metadata churn

- README-Gradle.md
- README.md
Update documentation to reflect Gradle’s status as WALA’s preferred, supported build system. Maven is not quite gone entirely, but WALA users should prefer to work within Gradle if at all possible.
Recommended by @msridhar in discussion of issue #577.
> Post-Maven documentation updates

- build.gradle
- com.ibm.wala.ide.jdt.test/build.gradle
- com.ibm.wala.ide.jdt/build.gradle
- com.ibm.wala.ide.jsdt.tests/build.gradle
- com.ibm.wala.ide.jsdt/build.gradle
- com.ibm.wala.ide.tests/build.gradle
- com.ibm.wala.ide/build.gradle
Many core Eclipse libraries are now cross-published directly to Maven Central. The WST JSDT libraries are not cross-published there, but I've found a source for them in a different public Maven repository. So now we can get everything we need from Maven repositories rather than downloading and converting P2 repositories.
Getting Eclipse libraries from proper Maven repositories should make the first build in a clean WALA tree faster and friendlier. We still need to download the Eclipse libraries, of course. But those downloads can now be concurrent with other Gradle build activity, such as compiling and running tests for non-Eclipse-based pieces of WALA. We also get better download progress reporting, proper Gradle caching, etc.
> Stop using Eclipse P2 repositories

- build.gradle
- com.ibm.wala.core.tests/build.gradle
Previously we were only filtering out tests marked as slow in the `com.ibm.wala.core.tests` subproject.  However, `com.ibm.wala.cast.js.test` has some slow tests too.
> Correct slow-test filtering in all subprojects

- com.ibm.wala.cast.js.html.nu_validator/build.gradle
- com.ibm.wala.cast.js.nodejs.test/build.gradle
- com.ibm.wala.cast.test/build.gradle
- gradle/wrapper/gradle-wrapper.properties
This required some test classpath tweaks, presumably due to changes in how Gradle 6.x handles dependency resolution.
Gradle 6.0 also added built-in support for publishing Javadoc and source archives, which is something for which we currently rely on third-party plugins and scripts. Unfortunately, Gradle’s built-in support only works with the `maven-publish` and `ivy-publish` plugins. We [switched to using `maven` instead of `maven-publish`](https://github.com/liblit/WALA/commit/53e64de8cc6bc8ab9773168aff8fabd4b66efd5a) some time ago because we “couldn't get proper artifacts built with the `maven-publish` plugin”. So for now Gradle’s built-in support will remain unused by us. I have [a branch that partially enables this](https://github.com/liblit/WALA/tree/use-Gradle-6-built-in-javadoc-and- …
> Upgrade to Gradle 6.0.1

- .travis.yml
- travis/before-install-gradle
- travis/before-install-maven
Remove some Travis CI tweaks and hacks that are no longer relevant now that we stopped using the `p2.asmaven` plugin.
> Travis CI p2.asmaven cleanups

- .idea/runConfigurations/Build_excluding_slow_tests.xml
This IntelliJ IDEA run configuration uses the Gradle `build` task to run nearly all tests, excluding those tagged as slow. It also runs all Gradle-configured linters and builds Javadoc documentation. This configuration is intended to be a fairly thorough check that everything is in order, while still not taking an unreasonably long time to finish.
> Add IntelliJ IDEA run configuration that builds nearly all tests

- .idea/.gitignore
IntelliJ IDEA 2019.3 stores this file as part of the project’s metadata. However, for a Gradle-based project such as WALA, this file is automatically derived from the Gradle build scripts.
> Ignore “.idea/jarRepositories.xml”

- .github/workflows/continuous-integration.yml
GtiHub Actions could potentially replace Travis CI as our continuous integration engine. So far I’m not actually sure which I prefer. Neither is dramatically faster than the other, for example. However, if GitHub Actions had fewer download timeouts then Travis CI, that would be a clear win. I propose that we use both for a while, and see if a winner emerges.
This initial configuration of GitHub Actions for continuous integration comprises three jobs:
1. Full Gradle build and test using JDK 1.8 on recent Ubuntu
2. Full Gradle build and test using JDK 1.8 on recent macOS
3. Java compilation only using ECJ on recent Ubuntu
There is certainly more than we could do, such as adding older OS releases, adding Windows, building using Maven, etc. But this is a sensible start.
> Explore GitHub Actions for continuous integration

- buildSrc/build.gradle
This release restores download progress reporting, fixing #597.
> Upgrade download plugin to latest v4.0.2 release

- build.gradle
- run-time-trials
- summarize-time-trials
The `run-time-trials` script repeatedly uses Gradle to rerun all tests.  During these runs, some extra Gradle logic is activated to record the start and end times of each individual test method.
The `summarize-time-trials` script describes the overall distribution of recorded test times, along with the top slowest individual test methods.
This was all useful for deciding which tests to annotate as `SlowTests`. I did that some time ago, but never committed these supporting tools.
> Add infrastructure for identifying slow tests

- .github/workflows/continuous-integration.yml
By default, GitHub Actions cancels the rest of a workflow if any job in that workflow fails.  I think I'd rather let the other jobs continue, as we already have with Travis CI.
> If one GitHub CI job fails, let others continue

- config/hooks/pre-commit
- config/hooks/pre-commit-stub
Restore @liblit's aborted improvements to the pre-commit script from #599.  Those changes were aborted as they would cause a hard-to-understand error in the existing `pre-commit-stub` script.  Here we detect the bad condition and emit a more understandable error asking the user to update their script.
> Convert pre-commit script to bash

- com.ibm.wala.cast.java.ecj.test/build.gradle
- com.ibm.wala.cast.java.test/build.gradle
- com.ibm.wala.cast.java.test/build.properties
- com.ibm.wala.cast.java.test/pom.xml
- com.ibm.wala.ide.jdt.test/build.gradle
There are actually no tests run in `com.ibm.wala.cast.java.test`.  It just has abstract test classes that get extended in other test modules.  So, use the main source set instead of the test source set, which will enable us to more easily put an artifact on Maven Central (to let us move IDE projects out of the repo, to enable retiring Maven).
> Convert cast.java.test to use the main source set

- com.ibm.wala.core.testdata/src/lambda/CallMetaFactory.java
- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/callGraph/LambdaTest.java
- com.ibm.wala.core/src/com/ibm/wala/ipa/summaries/LambdaMethodTargetSelector.java
Fixes #285 
Previously, a direct call to the constructor of `LambdaMetafactory` would be incorrectly treated as coming from an `invokedynamic`, causing a crash.
> Check for LambdaMetafactory <init> calls in LambdaMethodTargetSelector

- build.gradle
Gradle JUnit `SlowTest` filtering broke recently; these changes fix it.
> Fix recent regressions in SlowTest filtering

- travis-after-success.sh
Before we would deploy snapshot builds from cron jobs running for individual submodules, which is a waste.
> Don't deploy snapshots on cron builds

- com.ibm.wala.cast.java.ecj/build.gradle
- com.ibm.wala.cast.java.test.data/build.gradle
- com.ibm.wala.cast.js.nodejs/build.gradle
- com.ibm.wala.cast.js.test.data/build.gradle
- com.ibm.wala.cast.test/xlator_test/build.gradle
Treat each subproject's Gradle `sourceSet` configurations as authoritative regarding what is where.  Derive other Gradle paths from those, rather than hard-coding paths relative to subproject roots.
This change may seem to be more pedantic than practically useful. However, it lays the ground work for a larger upcoming reorganization of source locations.
> Avoid hard-coded paths to source files

- com.ibm.wala.ide.tests/META-INF/MANIFEST.MF
- com.ibm.wala.ide.tests/build.gradle
`com.ibm.wala.ide.tests` has had a runtime dependency on `com.ibm.wala.ide.jdt` at least as far back as 530d74929fa2b00594f26c4f6b3dea8a6544c0c8, in the early days of building WALA with Gradle. I don’t know where I got the impression that this dependency was needed; perhaps from Maven before that?  In any case, this dependency is apparently not needed after all:  all automated CI tests still pass with this dependency removed.
@msridar [described](https://github.com/wala/WALA/issues/636#issuecomment-569527600) this dependency as one that “seems like a mistake or bad.” Removing it now seems safe, and fixes #638 as easily as anyone could hope for.
> Remove an unnecessary runtime dependency

- com.ibm.wala.cast.js.nodejs/build.gradle
All tests pass either way, but this way puts some downloaded files in the right place for an existing `.gitignore` to do what it should.
> Set resource path *before* deriving other paths from it

- buildSrc/src/main/groovy/package-list.groovy
- com.ibm.wala.cast.js/build.gradle
- com.ibm.wala.core/src/com/ibm/wala/util/io/FileProvider.java
- com.ibm.wala.dalvik/build.gradle
- com.ibm.wala.util/build.gradle
Properly escape ampersands in Javadoc.
Match Java SE Javadoc to version of Java in use.
In a custom Gradle task used to help build Javadoc documentation, don’t apply `@PathSensitive` to non-file inputs.
> Assorted Javadoc and Javadoc+Gradle fixups

- build.gradle
See [the docs](https://github.com/ben-manes/gradle-versions-plugin/blob/master/README.md).  Now we can run `./gradlew dependencyUpdates` to see which dependencies are out of date.  This is a complement to dependabot, which doesn't work perfectly.  (E.g., there are still a bunch of references to JUnit 4.12, even though we already updated to 4.13 based on the dependabot PR.)  The plugin is customizable so eventually we could ignore certain deps, certain types of releases, etc.
> Add Gradle versions plugin

- com.ibm.wala.cast.java.ecj/build.gradle
The `run` task here really serves as a test.  We don’t validate the output; the test merely consists of completing the run successfully. So now we log this `run` task’s `stdout` and `stderr` to a file, and set
that file as the task’s output.  Without this, Gradle thinks that the `run` task must be rerun every time we run the test suite.  In general, Gradle caching and incremental rebuilds work best if it knows where each task’s output is stored.
> Log stdout and stderr from ECJ run

- com.ibm.wala.core.tests/src/com/ibm/wala/core/tests/callGraph/LambdaTest.java
We still build the call graph, which "shouldn't crash" per the existing comment.  But there's no need to save it in an otherwise-unused local variable.
> Don't save a CallGraph we never use in the future

- com.ibm.wala.dalvik/build.gradle
Android’s `sdkmanager` ultimately runs a JVM, defaulting to `$JAVA_HOME`.  Ideally we would always use a Java 1.8 installation here, since `sdkmanager` does not currently work under Java 9+. However, there is no automated way to select a JVM for a given desired version. So instead we prefer to use whichever Java installation the Gradle build is using. In most cases that will be `$JAVA_HOME`, but if it is not, then the developer probably had good reasons to build using something different. For example, perhaps `$JAVA_HOME` is Java 9+, so the developer intentionally used a different installation to run Gradle under Java 1.8.
> Try to pick a suitable JDK for Android SDK setup

- .github/pull_request_template.md
- CONTRIBUTING.md
This is just a quick guide to contributing, including info on what blocking jobs we run on CI.  Mostly cribbed from Uber's [Android template](https://github.com/uber/android-template).
> Add document on contributing

- build.gradle
- com.ibm.wala.core/src/main/java/com/ibm/wala/util/scope/JUnitEntryPoints.java
Enhancement to add JUnit4 entrypoint support. AFAIK, WALA previously only supported JUnit3.
I did not include regression tests in this PR as I am not very familiar with entrypoint testing in WALA. I am happy to add some if you think that they can be useful.
> Add JUnit4 entrypoint support

- com.ibm.wala.core/build.gradle
- travis/script-gradle
This should fix the timeouts we have been seeing on Travis. Not sure why they started, but I don’t see a fundamental underlying performance problem that arose recently
> More verbose output for wala.core tests

- com.ibm.wala.cast.js.nodejs/build.gradle
IntelliJ IDEA was incorrectly identifying the `RelativePath` constructor as a private one, even though we were actually using a different, public constructor. Using an equivalent `RelativePath.parse` factory method removes a spurious IntelliJ IDEA warning.
Prior commit d20ddc7b924a49c77e0d5f93d33ec12f1c5c88db addressed one instance of this problem. This commit applies the analogous fix elsewhere.
> Appease IntelliJ IDEA with different RelativePath API

- travis/script-gradle
We don't need to run these lint checks on both Linux and Mac.  The Mac JDK 8 job seems to be the slowest one right now, so this should speed it up slightly.
> Only run linter tasks on the Linux Travis CI job

- build.gradle
- com.ibm.wala.cast.java/build.gradle
Use correct plural and subjunctive verb mood in an task description.
Avoid directory clash for `main` and `testFixtures` Javadocs. This clash led to two tasks making each other appear perpetually out-of-date.
> Assorted minor Javascript fixes

- com.ibm.wala.dalvik/build.gradle
This task really just extracts one file from a dependency that would already have been downloaded by Gradle's generic dependency-fetching code.
> Rename a `download*` task that doesn't download

- com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/ipa/callgraph/AstSSAPropagationCallGraphBuilder.java
This output is not describing an error, and is not conditional on any debugging flags. It was probably accidentally left behind during development of the surrounding code.
> Remove some routine System.err output

- com.ibm.wala.dalvik/build.gradle
The downloaded/unpacked material that the `cleanDownloadSampleCup` task used to remove is now stored under a "build" subdirectory. It will be removed by the standard `clean` task with no extra effort from us.
Fixes #691.
> Remove obsolete extra-cleaning task

- build.gradle
- com.ibm.wala.cast.java.ecj/gradle.properties
- com.ibm.wala.cast.java/build.gradle
- com.ibm.wala.cast.java/gradle.properties
- com.ibm.wala.cast.js.rhino/gradle.properties
- com.ibm.wala.cast.js/gradle.properties
- com.ibm.wala.cast/gradle.properties
- com.ibm.wala.core/gradle.properties
- com.ibm.wala.dalvik/gradle.properties
- com.ibm.wala.scandroid/gradle.properties
- com.ibm.wala.shrike/gradle.properties
- com.ibm.wala.util/gradle.properties
- gradle-mvn-push.gradle
- gradle.properties
- travis-after-success.sh
- travis/before-install-maven
- travis/script-gradle
Previously we published three jars for each subproject: sources, Javadoc, and class files. We still publish those, and now also publish sources, Javadoc, and class files for each subproject’s test fixtures. We also publish various checksum files. All jar archives and the POM files should be signed (via command-line GnuPG) when publishing a release.
Names of tasks used for publishing have changed. Run `./gradlew tasks --group=publishing` for a list of all publishing-related tasks. Tasks likely to be of most interest are:
* `publishAllPublicationsToProjectBuildRepository`: populates a Maven repository in `build/maven-repository`. This is a good way to see what would be published without actually affecting the world outside the build tree.
* `publishToMavenLocal`: populates a Maven …
> Reimplement publishing using `maven-publish` plugin

- build.gradle
Composite builds only build and use artifacts from the default configuration of included builds. This [known limitation](https://docs.gradle.org/current/userguide/composite_builds.html#included_build_substitution_limitations) makes WALA test fixtures unavailable when WALA is included in a composite build. As a workaround for composite projects that rely on those test fixtures, we extend the `main` `sourceSet` to include all test-fixture sources too.  This hack is only applied when WALA itself is an included build.
> Allow WALA's test fixtures to be used in composite builds

- com.ibm.wala.dalvik/.gitignore
- com.ibm.wala.dalvik/build.gradle
Previously we were copying several jars out of the Android SDK into other locations. That's no longer necessary, for various reasons. Instead we can just use these jar files where they sit within the installed Android SDK tree.
> Use Android jars in-place, rather than copying

- com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/shrike/FloatingPointsTest.java
IntelliJ IDEA thinks that this class is "unrunnable by most JUnit test runners, including IDEA's" because it does not expose a public constructor that takes either no arguments or one String argument. However, this class does indeed offer a public nullary constructor, and running it in IntelliJ IDEA works just fine.
> Suppress a false-positive JUnit warning

- com.ibm.wala.dalvik/build.gradle
- com.ibm.wala.dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/DroidBenchCGTest.java
We shouldn't assume that the current build tree is the only thing running that might be interested in `/tmp/DroidBench`.  Better to keep everything we need in our own `build` subdirectories and avoid cross-build-tree interference.
> Unpack DroidBench under `build`, not under `/tmp`

- buildSrc/src/main/groovy/package-list.groovy
- com.ibm.wala.cast.js.nodejs/build.gradle
- com.ibm.wala.cast.js/build.gradle
- com.ibm.wala.cast/build.gradle
- com.ibm.wala.cast/smoke_main/build.gradle
- com.ibm.wala.cast/xlator_test/build.gradle
- com.ibm.wala.core/build.gradle
- com.ibm.wala.dalvik/build.gradle
- com.ibm.wala.util/build.gradle
- gradle-mvn-push.gradle
The goal is to make builds faster by only configuring tasks that are actually needed.  The naive approach to establishing task dependencies effectively looks like:
1. Configure task *A*.
2. Fetch information about task *A*’s outputs.
3. Use that information to configure task *B*’s inputs.
4. If task *B* is ever needed, task *A* (upon which *B* depends) has already been configured, so we’re good to go.
The preferred approach, using properties, providers, and [lazy task configuration](https://docs.gradle.org/current/userguide/lazy_configuration.html), is more like:
1. Fetch a closure that will compute task *A*’s outputs when needed.
2. Set task *B*’s outputs to this closure, or some other closure computed from that closure.
3. If task *B* is ever needed, task *A* (upon which *B* depends) …
> Use properties and providers for lazier task configuration

- build.gradle
- com.ibm.wala.cast.java.ecj/build.gradle
- com.ibm.wala.cast.js.rhino/build.gradle
- com.ibm.wala.cast/smoke_main/build.gradle
- com.ibm.wala.core/build.gradle
- com.ibm.wala.dalvik/build.gradle
- gradle-mvn-push.gradle
Continue earlier efforts (#711) to use lazy configuration, task configuration avoidance, and implicit task dependencies.
| Revision | Build Scan | Created Immediately :-1: | Created During Configuration :-1: | Not Created :+1: | Configuration Time :-1: |
|-|-|-:|-:|-:|-:|
| Before (3651dc48ef37c9fd90f1aabe4b91cc252f51781e) | [Link](https://scans.gradle.com/s/ld4n3iirz6be6/performance/configuration) | 46 tasks | 171 tasks | 1,015 tasks | 2.007 sec |
| After (77951632735172717db1f29369b6410598512f8c ) | [Link](https://scans.gradle.com/s/llnnxjcq33pbk/performance/configuration) | 11 tasks | 48 tasks | 1,135 tasks | 1.501 sec |
* :-1:: lower is better
* :+1:: higher is better
The remaining eagerly-created tasks are all outside of our control. A few are created by us, but only because the …
> Lazier task configuration

- com.ibm.wala.core/build.gradle
- com.ibm.wala.dalvik/build.gradle
- com.ibm.wala.dalvik/src/test/resources/.gitignore
- com.ibm.wala.ide.jdt.test/src/test/resources/.gitignore
Improve use of implicit dependencies in Gradle tasks for building material used in tests.
Build more test-related resources under various `com.ibm.wala.*/build` directories rather than under `com.ibm.wala.*/src` or directly in `com.ibm.wala.*` subdirectories.
> Gradle task improvements for building test resources

- com.ibm.wala.cast/smoke_main/build.gradle
- com.ibm.wala.core/.gitignore
- com.ibm.wala.core/build.gradle
- com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/cha/AnalysisScopeTest.java
Taken together, these changes mean that `com.ibm.wala.core` finally puts *all* of its generated files into `com.ibm.wala.core/build`, rather than in `com.ibm.wala.core` or other subdirectories thereof.
> More work on moving built artifacts into `build` subdirectories

- .travis.yml
- travis/script-gradle
- travis/script-maven
Each of these was needed at some point, but all of our Travis CI jobs pass now without them.
> Travis CI jobs no longer need realpath or xvfb

- com.ibm.wala.cast.js.nodejs/build.gradle
We were getting many CI failures downloading directly from GitHub.  Let's download from the official location instead (which shouldn't have as strict of rate limiting).
> Change NodeJS download URL to be more robust

- build.gradle
- com.ibm.wala.cast.js.nodejs/build.gradle
- com.ibm.wala.core/src/main/java/com/ibm/wala/classLoader/IBytecodeMethod.java
- com.ibm.wala.core/src/testFixtures/java/com/ibm/wala/core/tests/ir/AnnotationTest.java
- com.ibm.wala.core/src/testSubjects/java/annotations/AnnotationWithParams.java
- com.ibm.wala.core/src/testSubjects/java/annotations/AnnotationWithSingleParam.java
- com.ibm.wala.dalvik/build.gradle
- com.ibm.wala.dalvik/src/test/java/com/ibm/wala/dalvik/test/ir/DalvikAnnotationsTest.java
- com.ibm.wala.dalvik/src/test/java/com/ibm/wala/dalvik/test/util/Util.java
`dx` is deprecated so this modernizes our test code.  Also, using `d8` means we don't need to pull in the Android SDK as a `testCompile` dependence in `com.ibm.wala.dalvik`, since `d8` can be pulled from a Maven repository.  We still require the Android SDK as a `testRuntime` dependence.
Apparently `d8` strips out all bytecode annotations that are not runtime retention (undocumented, but mentioned [here](https://github.com/DexPatcher/dexpatcher-tool/releases/tag/v1.8.0-alpha4)).  So, we change our test code for Dalvik annotations to only look for annotations with runtime retention.  Cleaned up some related code in the process.
> Switch from dx to d8 for converting jar to dex

- .idea/misc.xml
This info lets IntelliJ IDEA associate this project with GitHub for purposes of IntelliJ IDEA's tasks & contexts feature. For example, you can tell the IDE that you are working on a specific GitHub issue.
> Add IntelliJ IDEA project task metadata

- com.ibm.wala.dalvik/build.gradle
We only download one component now: "platforms".  Fixes #726.
Also changes download directory to be under `build` instead of `build/tmp`.  We really shouldn't be using the temporary directory for anything that should be kept around after the task finishes.
> Simplify installAndroidSDK task

- .github/workflows/continuous-integration.yml
- .idea/runConfigurations/Compile_using_ECJ.xml
- CONTRIBUTING.md
- build.gradle
- com.ibm.wala.cast.js.nodejs/src/main/java/com/ibm/wala/cast/js/nodejs/NodejsRequiredCoreModule.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/ipa/callgraph/JSCallGraphUtil.java
- com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/loader/CAstAbstractModuleLoader.java
- com.ibm.wala.ide.jsdt/src/main/java/com/ibm/wala/ide/util/JavaScriptEclipseProjectPath.java
- com.ibm.wala.scandroid/src/main/java/org/scandroid/util/AndroidAnalysisContext.java
- com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/cg/OfflineDynamicCallGraph.java
- com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrikeBT/tools/OfflineInstrumenterBase.java
- com.ibm.wala.shrike/src/main/java/com/ibm/wala/sourcepos/Debug.java
- com.ibm.wala.util/src/main/java/com/ibm/wala/util/io/TemporaryFile.java
- travis/script-gradle
Plug several resource leaks detected by Eclipse. Suppress one such detection that is actually a false positive.
Other Eclipse leak warnings remain, but this is an initial step on the ones that I could fix in the obvious way.
> Fix several Eclipse-detected resource leaks

- .github/workflows/continuous-integration.yml
- .idea/runConfigurations/Build_excluding_slow_tests.xml
- CONTRIBUTING.md
- build.gradle
- travis/script-gradle
Previously some verification steps happened as part of `./gradlew check` and therefore also under `./gradlew build`, while others only happened as part of `./gradlew linters`.  Now we are retiring the `linters` task and moving all of its dependent verification tasks to be dependencies of `check` instead.
Fixes #740.
> Absorb `linters` task into `check`

- travis/before-cache-gradle
This script is failing repeatedly on macOS when run during GitHub Actions CI jobs.  The first "`find ... -delete`" command reports "No such file or directory".  This is probably some transient inconsistency in our view of the file system that holds the per-user Gradle cache.  It should be safe to ignore those errors: if a file we wanted to delete is already gone, then mission accomplished!
> Ignore failed deletions during cache cleanup

- .idea/misc.xml
I don't know what this attribute change means in practical terms, but IntelliJ IDEA 2020.1 definitely wants to change it in this manner. OK, sure. If it seems to be flipping to different values for different developers, we can take a closer look.
> Minor metadata update for IntelliJ IDEA 2020.1

- .github/workflows/continuous-integration.yml
- build.gradle
- buildSrc/src/main/groovy/java-compile-using-ecj.groovy
- buildSrc/src/main/java/com/ibm/wala/gradle/EclipseJavaCompiler.java
- buildSrc/src/main/java/com/ibm/wala/gradle/EclipseJavaCompilerFactory.java
- buildSrc/src/main/java/com/ibm/wala/gradle/EclipseJavaCompilerToolChain.java
- com.ibm.wala.cast/build.gradle
- com.ibm.wala.core/build.gradle
We still use the default Java compiler for builds, tests, published jar archives, etc.  But now we *also* compile all Java using ECJ as part of the standard `check` validation tasks.
Set the `skipJavaUsingEcjTasks` project property if you want to skip ECJ compilation for some reason.  For example, `./gradlew -PskipJavaUsingEcjTasks ...`.
Our encapsulation of ECJ as a Gradle-compatible Java compilation tool chain is inspired by, and derived from, @TwoStone's [gradle-eclipse-compiler-plugin](https://github.com/TwoStone/gradle-eclipse-compiler-plugin). Existing pull request #744 used that plugin to provide the required ECJ tool chain, but in a way that was somewhat hackish as it deviated from the usage style that gradle-eclipse-compiler-plugin was designed for. [I reached out to @TwoStone to …
> Run ECJ compiler as part of Gradle `check` tasks

- buildSrc/src/main/java/com/ibm/wala/gradle/EclipseJavaCompilerFactory.java
- com.ibm.wala.cast/build.gradle
- gradle/wrapper/gradle-wrapper.properties
A [default directory for native-method headers](https://docs.gradle.org/6.3/release-notes.html#customizing-location-of-native-headers-generated-from-java-source) means we no longer need to set our own.
Our ECJ-for-Gradle encapsulation got a bit simpler, since the factory API it is required to implement shrank.
> Updates for Gradle 6.3

- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/summaries/LambdaMethodTargetSelector.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ssa/SSAInvokeDynamicInstruction.java
- com.ibm.wala.core/src/testSubjects/java/lambda/CallMetaFactory.java
- com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrikeCT/BootstrapMethodsReader.java
Fixes #717
To determine whether an `invokedynamic` instruction is for Java lambdas, we now directly check if the bootstrap method is the one used in compiling such lambdas.  There is an additional test line in `CallMetafactory` capturing the behavior observed in #717
> improve detection of invokedynamic for Java lambdas

- .idea/inspectionProfiles/No_Back_Sliding.xml
- .idea/runConfigurations/Compile_using_ECJ.xml
- com.ibm.wala.cast.java.ecj/build.gradle
- com.ibm.wala.cast.js.rhino/src/main/java/com/ibm/wala/cast/js/translator/RhinoToAstTranslator.java
- com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/ir/translator/AstTranslator.java
- com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/util/CAstPattern.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/PropagationSystem.java
- com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/androidModel/AndroidModel.java
Easy:
- 90a11e2: Correct IntelliJ IDEA warning about unused assignment
- 7e11d4f: Disable some inspections on test code
- 0ba4127: Suppress a warning about overlapping array copy
- baa99cd: Update run configuration for new ECJ strategy
- bb5a582: Use method references instead of lambdas where possible
A bit more subtle:
- 8a8362d: Hoist common actions out of if/else branches
- 3432d71: Restructure a conditional that includes dead code
Tricky, so please check carefully:
- c4e98d0: Simplify a complex knot of conditionals
> Multiple minor warning/linter fixes

- com.ibm.wala.core/build.gradle
Previously we were suppressing these by adding `-err:none` to the ECJ command line. But that's not actually a valid ECJ flag. It did suppress the error diagnostics, but also produced a warning about the invalid flag. Now we suppress the specific error diagnostics that the Java test subjects trigger, and we do it using valid ECJ flags.
> Suppress ECJ errors on Java test subjects

- com.ibm.wala.cast.js.nodejs/build.gradle
We only need to download and unpack NodeJS to run `com.ibm.wala.cast.js.nodejs` tests.  It should not get packaged as part of the main resources.
> Only download and unpack NodeJS as part of processing test resources

- .github/workflows/continuous-integration.yml
I have been seeing some persistent `fatal: reference is not a tree` failures during the initial checkout stage of our GitHub actions. Skimming reports by others suggests that [`actions/checkout@v2` does better in the situations that trigger this under `@v1`](https://github.com/actions/checkout/issues/23).
> Upgrade GitHub checkout action

- build.gradle
- com.ibm.wala.cast.java.ecj/build.gradle
- com.ibm.wala.cast.js.nodejs/build.gradle
- com.ibm.wala.cast.js/build.gradle
- com.ibm.wala.cast/smoke_main/build.gradle
- com.ibm.wala.core/build.gradle
- com.ibm.wala.dalvik/build.gradle
A task's `temporaryDir` is supposed to be for short-lived files that need not outlive that task.  In theory, Gradle could delete these temporary directories at any time, even though it currently does not.
A good example of something that would be sensible to store in `temporaryDir` would be a file that contains additional command-line flags to be given to an external command.  That file need not be retained after the task that runs the command finishes.
By contrast, files that constitute a task's outputs should not go in `temporaryDir`.  There's no guarantee that `temporaryDir` files will be retained after each task finishes.
> Don't use Gradle tasks' temporaryDir for retained files

- build.gradle
- buildSrc/src/main/java/com/ibm/wala/gradle/EclipseJavaCompilerToolChain.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/vis/JsPaPanel.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/util/ssa/SSAValueManager.java
- com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/exceptionpruning/ExceptionAnalysis2EdgeFilterTest.java
- com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/classLoader/DexIField.java
- com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/androidModel/AndroidModelClass.java
- travis/script-gradle
It seems the `verifyGoogleJavaFormat` task was not running on CI.  I think it is because at the top level, the `build` task does not depend on `check`.  This PR re-enables the check and also fixes some formatting issues that have crept in.
> Re-enable Google Java Format checking on CI

- build.gradle
I find this plugin very useful for visualizing task dependencies.  Example run related to #771:
```
$ ./gradlew :build :taskTree
> Task :taskTree
------------------------------------------------------------
Root project
------------------------------------------------------------
:build
\--- :check
+--- :shellCheck
\--- :verifyGoogleJavaFormat
```
> Add task-tree plugin

- build.gradle
This works around a missing feature that [has already been requested for
the Gradle google-java-format plugin](https://github.com/sherter/google-java-format-gradle-plugin/issues/43).
> Help Gradle cache the verifyGoogleJavaFormat task

- com.ibm.wala.cast.js.rhino/build.gradle
- com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/rhino/callgraph/fieldbased/test/AbstractFieldBasedTest.java
- com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/test/TestCallGraph2JSON.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/FieldBasedCallGraphBuilder.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/FlowGraph.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/util/CallGraph2JSON.java
- com.ibm.wala.cast.js/src/test/resources/tests/fieldbased/native_call.js
- com.ibm.wala.cast.js/src/test/resources/tests/fieldbased/native_callback.js
- com.ibm.wala.cast.js/src/testFixtures/java/com/ibm/wala/cast/js/test/ExtractingToPredictableFileNames.java
This PR includes various improvements to `CallGraph2JSON` for serializing call graphs built with the field-based call graph builder.  It also adds some tests for `CallGraph2JSON`.  Opportunistically clean up some related code (like removing prints, removing mutable static fields, and fixing a Javadoc warning).
I may land this without review as its on the critical path for a research project.  But, if any issues are spotted I can fix in a follow-up PR.
> Improvements to CallGraph2JSON

- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/FieldBasedCallGraphBuilder.java
- com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/ipa/callgraph/CrossLanguageCallGraph.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/CGNode.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/cha/CHACallGraph.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/impl/BasicCallGraph.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/SSAPropagationCallGraphBuilder.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/rta/AbstractRTABuilder.java
Several call graph builders rely on this API, and we have no alternative.  So the method should not be marked as deprecated.  Added "NOTE" in all caps to the javadoc to further discourage use of the method outside of call graph builders.
> Un-deprecate CGNode.addTarget()

- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/util/FieldBasedCGUtil.java
We already support this for other JS call graph builders; add a relevant API method.
> Support for constructing field-based call graphs for all scripts in a directory

- com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/rhino/callgraph/fieldbased/test/TestFieldBasedCG.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/JSMethodInstructionVisitor.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/ipa/summaries/JavaScriptConstructorFunctions.java
- com.ibm.wala.cast.js/src/test/resources/tests/fieldbased/new_fn_empty.js
Fixes a crash in the field-based call graph builder
> Don't crash for new Function() called with empty string

- com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/rhino/callgraph/fieldbased/test/AbstractFieldBasedTest.java
- com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/test/TestCallGraph2JSON.java
- com.ibm.wala.cast.js/build.gradle
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/util/CallGraph2JSON.java
We now output JSON in a format that includes information on the containing method for each call site, which makes determining things like method reachability from an entrypoint much easier.  Also, use Gson for serializing JSON rather than coding that ourselves.
> Add method info to CallGraph2JSON output

- com.ibm.wala.core/src/main/java/com/ibm/wala/core/tests/callGraph/CallGraphTestUtil.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/core/tests/util/TestConstants.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/cfa/CallStringContextSelector.java
- com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/callGraph/ReflectionTest.java
- com.ibm.wala.core/src/testSubjects/java/reflection/Reflect24.java
Override `com.ibm.wala.ipa.callgraph.propagation.cfa.CallStringContextSelector.CallStringContextPair#isA()` to prevent possible problems when dealing with reflection and other situations.
For example: in the case of N-CFA, `com.ibm.wala.analysis.reflection.GetClassContextInterpeter#understand()` will not match `JavaTypeContext`
I think this bug is relatively simple, so I did not add related test cases. If necessary, please contact me.
> Override the isA() method of CallStringContextPair 

- com.ibm.wala.cast.js.rhino/build.gradle
- com.ibm.wala.cast.js.rhino/src/main/java/com/ibm/wala/cast/js/translator/RhinoToAstTranslator.java
- com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/rhino/callgraph/fieldbased/test/AbstractFieldBasedTest.java
- com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/test/TestCallGraph2JSON.java
- com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/test/TestFlowGraphJSON.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/FieldBasedCallGraphBuilder.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/FlowGraph.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/vertices/ArgVertex.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/vertices/CallVertex.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/vertices/FuncVertex.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/vertices/ParamVertex.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/vertices/RetVertex.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/vertices/VarVertex.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/vertices/Vertex.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/client/JavaScriptAnalysisEngine.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/util/CallGraph2JSON.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/util/FieldBasedCGUtil.java
- com.ibm.wala.cast.js/src/test/resources/tests/fieldbased/flowgraph_constraints.js
- com.ibm.wala.cast.js/src/testFixtures/java/com/ibm/wala/cast/js/test/TestPointerAnalyses.java
- com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/tree/CAstSourcePositionMap.java
- com.ibm.wala.ide.jsdt/src/main/java/com/ibm/wala/cast/js/client/EclipseJavaScriptAnalysisEngine.java
- com.ibm.wala.util/src/main/java/com/ibm/wala/util/graph/GraphPrint.java
This required a refactoring to expose the `FlowGraph` in the relevant construction APIs.  Also, add the ability to print a nicer, source-level representation of `Vertex` nodes in the flow graph, rather than printing info about WALA SSA variables.
> Add ability to serialize flow graph from JS field-based call graph builder to JSON

- com.ibm.wala.dalvik/src/test/java/com/ibm/wala/dalvik/test/util/Util.java
This way, if compilation fails, we get a `CompilationFailedException` and can try to understand it.  Before, we just invoked the `main()` method, and a failure would result in a `System.exit()` call that killed the whole JVM.
> Invoke D8 via proper API

- build.gradle
This formula is suggested on [this page](https://guides.gradle.org/performance/).  I've found that using maximum parallelism for tests can slow things down since the JVM still needs to run GC threads, etc.  On my laptop, this change makes `:com.ibm.wala.dalvik:test` run significantly faster (from ~4m to ~2m45s).
> Reduce test parallelism

- com.ibm.wala.core/src/main/java/com/ibm/wala/core/tests/util/TestConstants.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/impl/Util.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/cfa/AllocationString.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/cfa/AllocationStringContext.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/cfa/nObjBuilder.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/cfa/nObjContextSelector.java
- com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/ptrs/ObjectSensitiveTest.java
- com.ibm.wala.core/src/testSubjects/java/objSensitive/A.java
- com.ibm.wala.core/src/testSubjects/java/objSensitive/B.java
- com.ibm.wala.core/src/testSubjects/java/objSensitive/C.java
- com.ibm.wala.core/src/testSubjects/java/objSensitive/TestObjSensitive1.java
- com.ibm.wala.core/src/testSubjects/java/objSensitive/TestObjSensitive2.java
First of all, I am sorry to submit the pr after so long. Considering that if `HeapContextSelector` is introduced, it may not be consistent with the existing logic of `GetClassContextSelector`, `CloneContextSelector`, etc., eventually there may be problems in processing reflection. So I finally changed the implementation of object sensitivity and decided to make `CGNode `and `AllocationSiteInNode` use the same `Context`, as you mentioned before.
If there is something inappropriate, you can contact me. :blush:
> add k-limited object sensitivity (#801)

- README.md
See #626, specifically https://github.com/wala/WALA/issues/626#issuecomment-641469315.  This is the revamped README.  Some of this content will become the new WALA home page at https://wala.sourceforge.net.
I kept the build instructions that were there in the README before but it's now further down the page.
> Revamp of README

- build.gradle
- com.ibm.wala.ide/build.gradle
Fixes #823.  Since we only try to compile `com.ibm.wala.ide` code from Gradle, not run it, I think just excluding the entire `com.sun.jna` group is an ok solution.
> Exclude deps on com.sun.jna group

- com.ibm.wala.cast.js.rhino/src/main/java/com/ibm/wala/cast/js/translator/RhinoToAstTranslator.java
- com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/rhino/callgraph/fieldbased/test/TestFieldBasedCG.java
- com.ibm.wala.cast.js/src/test/resources/tests/recursive_lex_write.js
Previously, we always treated the name of a function as being declared in the scope of the function body.  But this is only true for function expressions, not function statements.  Hence, there were cases when WALA IR was modeling a read of a function name as a local variable access, when in fact it was a lexical access.  This PR fixes the bug and adds a corresponding test `recursive_lex_write.js` that we would previously handle unsoundly.
> JavaScript: make refs to enclosing function names lexical

- .idea/codeStyles/Project.xml
These settings keep getting added to this file by IntelliJ, which makes it modified in `git status`.  I think they are added by the latest Kotlin plugins.  It seems safe to just add them to the config file.
> Add Kotlin settings that IntelliJ adds by default

- build.gradle
- com.ibm.wala.dalvik/build.gradle
It seems R8 releases are not pushed to the main Google Maven repo very often.  Pull them from the alternate repo instead.
> Update R8 using different Maven repo

- com.ibm.wala.ide.tests/build.gradle
Somehow the dependence version of `org.eclipse.ui.workbench` got bumped, so code wasn't compiling anymore in Gradle on Java 8 (due to JDK 11 classes in the new jar).  Forcing an older version seems to fix it.
> Force dependence on old version of org.eclipse.ui.workbench to fix a compile error

- com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/test/TestFlowGraphJSON.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/WorklistBasedOptimisticCallgraphBuilder.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/vertices/AbstractVertexVisitor.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/vertices/ReflectiveCallVertex.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/vertices/VertexFactory.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/vertices/VertexVisitor.java
- com.ibm.wala.cast.js/src/test/resources/tests/fieldbased/flowgraph_constraints.js
This vertex more explicitly captures which variable holds the function invoked when using `Function.prototype.call` and `Function.prototype.apply`.  The addition does not affect the computed call graph, but can be helpful for downstream clients inspecting the flow graph.
> Add ReflectiveCallVertex to JS flow graph

- com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/rhino/callgraph/fieldbased/test/TestFieldBasedCG.java
- com.ibm.wala.cast.js/src/test/resources/tests/switch_default.js
- com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/ir/translator/AstTranslator.java
Before, the explicit default case in the generated CFG was unreachable, leading to the code being deleted completely from the IR.  Add some comments and a JavaScript test.  Presumably Java (and other CAst languages) are also affected by this fix.
> Fix handling of default case in switch statements

- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/cha/ClassHierarchy.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/cha/IClassHierarchy.java
See #871.  Clarify that `resolveMethod()` only works when the receiver represents a class.
Also delete duplicative documentation between `IClassHierarchy` and `ClassHierarchy` for these methods.
> Clarify Javadoc of ClassHierarchy resolveMethod

- build.gradle
- buildSrc/src/main/groovy/java-compile-using-ecj.groovy
- buildSrc/src/main/java/com/ibm/wala/gradle/EclipseJavaCompiler.java
- com.ibm.wala.cast.java.ecj/build.gradle
- com.ibm.wala.core/build.gradle
These tweaks don't actually allow us to upgrade to Gradle 7: see wala/WALA#892. But they do smooth the path for a future upgrade by modernizing some things that are deprecated in Gradle 6 or 7.
> Minor Gradle 6 updates for better future-compatibility

- build.gradle
This pull request is an alternative to #898 that centralizes constraint configuration in one place for all subprojects.
> Avoid Eclipse artifact versions that require Java 11+

- .github/workflows/continuous-integration.yml
The advantage of `--continue` is that you might see more CI failures in one run.  But there are disadvantages, including:
1. It takes longer to get notified when some failure exists.
2. It can be hard to search through the extra log output for the root cause of the failure.
Overall, I think we're better off without `--continue`.
> Remove --continue flag from Gradle jobs on CI

- .idea/vcs.xml
This extra bit of project metadata teaches IntelliJ IDEA to recognize
mentions of issues in commit messages and turn them into GitHub WALA
project links.  Subtle, but handy!
See https://www.jetbrains.com/help/idea/handling-issues.html for more
information about this IntelliJ IDEA feature.
> Configure IntelliJ IDEA issue navigation

- .idea/.gitignore
- .idea/.name
Julian removed all IntelliJ IDEA project metadata in commit 2c8f34c39c68680d0a2cc865e22fc10e8af0a01d.  He restored most of that in commit 708ad6542908e0494df07aa3f383028f13a02fb9, but not all.  The overlooked files begin with `.`, so were probably missed by some `*` wildcard.  This commit restores those last two overlooked files.
> Restore more of the recently removed IDE metadata

- com.ibm.wala.ide.jsdt/src/main/java/com/ibm/wala/ide/util/EclipseWebProjectPath.java
- settings.gradle
The JSDT Gradle projects pull artifacts from the Alfresco Maven repository, which now does not work due to an expired certificate.  Rather than trying to fix this in Gradle, this PR disables Gradle on the modules.  The modules are still built and tested via the "Maven Eclipse tests" CI job, which pulls the relevant artifacts from a p2 repository (via Tycho) so it is unaffected.
> Don't compile JSDT projects with Gradle

- .idea/WALA-fix.iml
- .idea/modules.xml
These metadata files were added without review in
abe0e1d39c08380790eb0c540336c133feb60757, presumably by accident.
> Remove spurious IntelliJ IDEA metadata about a non-existent module

- com.ibm.wala.cast.js/build.gradle
- com.ibm.wala.cast.js/gradle.lockfile
JUnit should only be required for tests.
> Remove JUnit as an implementation dependence of cast.js

- .github/workflows/continuous-integration.yml
This reverts commit 4118f17e5986f305cb23e947ac8f6d4cbb08e66c.
I'd like to be able to see GitHub actions results on my branches *before* I turn them into pull requests.
> Revert "only run CI jobs on push to master (#858)"

- build.gradle
- com.ibm.wala.cast.java.ecj/build.gradle
- com.ibm.wala.cast.java.test.data/build.gradle
- com.ibm.wala.cast.js.nodejs/build.gradle
Previously we were looking up some task providers by name.  But we created those task providers just slightly earlier in this same
`build.gradle` script.  We may as well retain references to the providers we created instead of discarding them and looking them up again later.
> Save task providers for reuse a few lines later

- com.ibm.wala.cast.java.test.data/build.gradle
`compileTestJavaUsingEcj` uses an output file created by `downloadJLex`, but the former did not previously declare the latter as a dependency. By adding that dependency now, we resolve a Gradle warning, enable certain Gradle execution optimizations, and remove a potential source of task-order-dependent non-determinism in builds.
> `compileTestJavaUsingEcj` depends on `downloadJLex`

- com.ibm.wala.core/build.gradle
[`JavaExec.main`](https://docs.gradle.org/7.2/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main) is deprecated in Gradle 7 and will be removed in Gradle 8.  Replace it with `JavaExec.mainClass`.
[`SourceDirectorySet.outputDir`](https://docs.gradle.org/7.2/dsl/org.gradle.api.file.SourceDirectorySet.html#org.gradle.api.file.SourceDirectorySet:outputDir) is deprecated in Gradle 7 and will be removed in Gradle 8.  Its direct replacement is `SourceDirectorySet.outputDir`, but I prefer a different replacement that would potentially include directories containing class files that did not come from Java.
> Update Gradle 7 deprecations

- build.gradle
`autoLintGradle` creates no output files, which causes Gradle to treat it as always out-of-date.  By creating a simple, empty stamp file to record that this task has run and succeeded, we allow Gradle to avoid rerunning this task unnecessarily.  This task will still be rerun when needed, though, such as when any of the `**/build.gradle` files change.
> Give `autoLintGradle` task an empty output file

- .github/workflows/continuous-integration.yml
Dependabot pushes to branches in the `wala/WALA` repo for its changes, which means that right now, two sets of (redundant) jobs run on these PRs: one set for the pull request, and one for the push to the branch.  This change eliminates the jobs on the branch push, which will save some CI resources.  Not a huge deal in the grand scheme of things, but I hate wasting compute 🙂
> Don't run CI jobs on pushes to dependabot branches

- com.ibm.wala.util/build.gradle
- com.ibm.wala.util/gradle.lockfile
- com.ibm.wala.util/src/main/java/com/ibm/wala/util/graph/impl/BasicEdgeManager.java
- com.ibm.wala.util/src/main/java/com/ibm/wala/util/graph/impl/BasicGraph.java
- com.ibm.wala.util/src/test/java/com/ibm/wala/util/test/BasicGraphTest.java
This way, we have an implementation that does not require node numbering, as an example and to use in tests, etc.
> Add a basic graph implementation

- .github/workflows/continuous-integration.yml
Sometimes I end up pushing multiple times to a PR in a short time, and by default GitHub will run CI jobs for each push.  But only the most recent CI job "counts" in terms of checking the changes.  This changes adds a step to cancel running but outdated workflows; see https://github.com/styfle/cancel-workflow-action/blob/main/README.md
> Add CI step to cancel previous workflows for same branch / PR

- com.ibm.wala.cast.java.ecj/src/main/java/com/ibm/wala/cast/java/ecj/util/SourceDirCallGraph.java
A Javadoc `@throws FooException` with no explanation as to the circumstances under which the exception arises is useless.  Presumably these were added at some point to pacify a linter's requirement that all thrown exceptions be documented.  An empty `@throws FooException` tag is *not* real documentation, and in fact, these empty tags are producing warning diagnostics of their own when building Javadoc.
> Remove useless empty @throws tags

- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/PropagationCallGraphBuilder.java
There's no point in declaring `protected` members of a `final` class. These members may as well be `private`.
> Privatize protected members of final classes

- .github/workflows/continuous-integration.yml
Looks like yesterday's failures were transient.  I tried the snapshot upload on a branch just now and it succeeded:
https://github.com/wala/WALA/runs/3624072775?check_suite_focus=true
Fixes #981
> Re-enable snapshot uploads

- .github/workflows/continuous-integration.yml
This is an improved version of #976 using [the `concurrency` feature](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency) of GH Actions workflows.  This ensures our CI workflow only runs for the latest commit on any branch / PR, and also that only one workflow for each branch is running at any given time.  The latter is useful for the WALA master branch in particular, since before it was possible for workflows to upload Javadoc and snapshot builds out of order if one ran particularly slowly.
> Cancel outdated jobs using workflow concurrency

- com.ibm.wala.core.java11/src/test/java/com/ibm/wala/core/tests/jdk11/privateInterfaceMethods/PrivateInterfaceMethodsTest.java
- com.ibm.wala.core.java11/src/testSubjects/java/privateInterfaceMethods/testArrayReturn/ReturnArray.java
- com.ibm.wala.core.java11/src/testSubjects/java/privateInterfaceMethods/testArrayReturn/TestArrayReturn.java
Java package names conventionally start with lower-case letters.
> Conform to Java package naming conventions

- com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/ir/translator/AstTranslator.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/core/util/ref/CacheReference.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/core/util/strings/Atom.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/types/FieldReference.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/types/MethodReference.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/types/TypeName.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/types/TypeReference.java
- com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeCT/SourcePositionTableReader.java
- com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/sourcepos/CRTData.java
- com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/sourcepos/CRTFlags.java
- com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/sourcepos/CRTable.java
- com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/sourcepos/MethodPositions.java
- com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/sourcepos/Position.java
- com.ibm.wala.util/src/main/java/com/ibm/wala/util/intset/OffsetBitVector.java
In a `final` class, all methods are implicitly `final`.  No need to make that explicit.
> Remove hundreds of redundant `final` qualifiers

- .idea/.gitignore
So far, the only setting that I am seeing stored here is a preference for whether to activate a view that is specialized for Python scientific code.  This seems like a per-developer preference, not an intrinsic property of the WALA code base.
> Exclude `other.xml` from Git

- run-time-trials
This variable expansion is actually safe even without quoting, since it can only ever be a number from 1 through 10.  But ShellCheck apparently isn't smart enough to know that.  In general, we want to keep this kind of warning enabled, so the easiest thing to do is add the (unnecessary) quotes here to satisfy ShellCheck.
> Double-quote a variable expansion

- com.ibm.wala.cast.java.ecj/src/main/java/com/ibm/wala/cast/java/translator/jdt/JDTJava2CAstTranslator.java
- com.ibm.wala.core.java11/src/testSubjects/java/nestmates/Outer.java
One of these is in a test subject, but the `final`ness of the field appears to be irrelevant to the test.
> Make `private` fields `final` where possible

- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/ssa/Util.java
`Collections::singleton` already returns an unmodifiable collection.
> Remove redundant `unmodifiableCollection` wrapper

- com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/shrikeCT/tools/AddSerialVersion.java
- com.ibm.wala.util/src/main/java/com/ibm/wala/util/math/Logs.java
Instead, be explicit that we're working with `long` values from the start.
> Avoid `int` shifts that implicitly cast to `long`

- com.ibm.wala.dalvik/src/test/java/com/ibm/wala/dalvik/test/cha/MultiDexScopeTest.java
`FileInputStream` and `FileOutputStream` offer constructors that take a `String` argument.  No need to create new `File` instances here.
> Remove gratuitous `new File` creations

- com.ibm.wala.cast.java.test.data/src/test/java/StaticInitializers.java
- com.ibm.wala.cast.java.test.data/src/test/java/foo/bar/hello/world/InnerClasses.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/analysis/arraybounds/ArrayBoundsGraph.java
Also mark two other seemingly-gratuitous uses of unary `-` or `+` as ignored.  These occur in test inputs and are presumably intentional.
> Remove a gratuitous unary negation

- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/JSMethodInstructionVisitor.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/ipa/summaries/JavaScriptConstructorFunctions.java
`String::isEmpty` is preferred over using `String::equals` to compare a
`String` to `""`.
> Specialize String emptiness checks

- com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/test/TestCallGraph2JSON.java
When both keys and values will be needed, `Map::entrySet` is a better thing to iterate over than `Map::keySet`.
> Optimize iterations over Maps' keys and values

- .github/workflows/continuous-integration.yml
- xvfb-gradle.sh
Presumably the Gradle developers know best how to configure things like caching.  I'm particularly interested in seeing our GitHub actions use better caching because we run those actions more frequently now due to our stricter `master`-branch merge policies.
Historically, we have disabled Gradle caching during CI/CD builds: `./gradlew --no-cache ...`.  Presumably we wanted to get a "clean" build every time for the strictest possible checking.  However, clean builds with no cache take a long time!  Furthermore, I believe that our build caching is extremely trustworthy.  I cannot remember the last time that something broken ended up in my cache.  Likewise, I cannot remember the last time that a build succeeded by using the cache, but should have failed if the cache were empty.
I propose …
> Use official Gradle GitHub actions

- .github/workflows/IntelliJ-IDEA-inspections.yml
- build.gradle
- buildscript-gradle.lockfile
**Add two new top-level Gradle tasks:**
* `runInspections` applies all configured IntelliJ IDEA inspections to the entire WALA project and records the results for future examination. IntelliJ IDEA must already be installed; we don’t download and install it automatically.
* `checkInspectionResults` examines `runInspections` results, summarizes any errors or non-weak warnings, and fails if any such errors or non-weak warnings were found.
---
**Add a new GitHub Actions workflow that installs IntelliJ IDEA Community Edition and runs the above tasks.**
`runInspections` takes about 30 minutes to run as a GitHub Actions workflow: too slow to use in every merge or pull request. So instead, this workflow runs once per week. It can also be started manually, either via GitHub’s REST API or using the …
> Add Gradle tasks and GitHub workflow for IntelliJ IDEA inspections

- .idea/inspectionProfiles/No_Back_Sliding.xml
Unfortunately this IntelliJ IDEA inspection disapproves of `@see` with a newline before the referenced symbol or link.  The Google Java formatter will put those newlines back if we remove them, so there's just no way to make both Google Java style and IntelliJ IDEA's inspection happy at the same time.  I have [reported this conflict](https://intellij-support.jetbrains.com/hc/en-us/community/posts/4408317078930-Javadoc-problems-inspection-should-allow-newline-after-see) to JetBrains.  Until they take action on this problem, I think that we have no choice but to reduce this inspection's severity from "warning" to "weak warning".
> Weaken Javadoc warnings in IntelliJ IDEA

- .github/workflows/IntelliJ-IDEA-inspections.yml
I mistakenly assumed that each Gradle action could accept an array of `arguments`. Nope! But `arguments` can be a multi-line YAML string.
Unfortunately there’s just no easy way to test a manually triggered workflow *before* merging it to `master`.
> Correct multiple arguments to Gradle actions

- build.gradle
- com.ibm.wala.cast.java.ecj/src/main/java/com/ibm/wala/cast/java/translator/jdt/FakeExceptionTypeBinding.java
This change allows for Eclipse-based code that uses SWT to build on ARM-based Macs.  A more recent Eclipse version is needed since an SWT artifact for ARM Mac was only introduced recently.  We do not bump the Eclipse version globally since recent Eclipse versions require JDK 11, and we want to preserve the ability to run this code on JDK 8.
> Build against Eclipse 4.21.0 on ARM-based Macs

- com.ibm.wala.cast/cast/build.gradle
- com.ibm.wala.cast/smoke_main/build.gradle
- com.ibm.wala.cast/xlator_test/build.gradle
This trick convinces Gradle to run the built-in Clang / gcc on M1 Macs to compile native CAst code, when executing with a native ARM JVM.  I don't think it should cause any harm on other platforms, since all we support otherwise is 64-bit x86.  If / when https://github.com/gradle/gradle/issues/18876 is fixed, we can remove this change.
Fixes #1045
> Temporary fix for building CAst native code on M1 Macs

- .github/workflows/IntelliJ-IDEA-inspections.yml
If any inspections fail, it can be useful to examine the complete inspection results manually. This change has GitHub preserve those results whenever we run the IntelliJ IDEA inspections workflow.
Artifacts are preserved for 90 days by default, but that seems much longer than we'll need these results to be retained. We run this workflow once per week, so let's retain those results for two weeks.
> Preserve IntelliJ IDEA inspection results as workflow artifact

- com.ibm.wala.cast.java.test.data/build.xml
The embedded `isset` element ensures that we will only `buildTempFolder` to set the value of `pluginTemp` if `buildTempFolder` is actually set.
Each of these `base*` properties is defined using some other Ant property that IntelliJ IDEA thinks is unknown. Those other properties might be set in one of the Eclipse launchers (`JDTJava15IRTests.launch`), but I don't see them being set anywhere else. In any case, none of the four `base*` properties are ever mentioned again anywhere in this `build.xml` file. My guess is that these properties are no longer used, and therefore that they can be removed.
> IntelliJ IDEA Ant unknown property fixes

- build.gradle
- com.ibm.wala.cast.java/src/testFixtures/java/com/ibm/wala/cast/java/test/IRTests.java
- com.ibm.wala.core/src/test/java/com/ibm/wala/util/io/FileProviderTest.java
No reason to escape `#` in Java regular expressions.
No need to escape `]` after escaped `\[`. An unescaped `]` has no special meaning for Java or Groovy regular expressions unless it's inside a character class that was introduced using an unescaped `[`.
> IntelliJ IDEA regexp inspections fixes

- gradle-mvn-push.gradle
It seems the external gpg command support is poor and doesn't really work out of the box with `gpg2`.  I have re-configured the signing config on my local machine to be compatible and `gpg2` and the built-in Gradle signing functionality.  So this is no longer necessary.  I will also update the documentation at https://github.com/wala/WALA/wiki/WALA-Releases-and-Snapshots#initial-setup appropriately.
I've tested locally and signing seems to work, though the true test will only happen next time we want to cut a release (which should probably be soon anyway).
> Stop using external gpg command for signing artifacts

- com.ibm.wala.cast.java.test.data/build.gradle
The `JLex.java` file that we download is compiled as part of the `com.ibm.wala.test.data` test sources, but we still shouldn't treat it as "real" hand-authored, git-tracked source code.  This file is built by running a task, just like any other build artifact.
Happily, treating `JLex.java` as a built actually makes the relevant build script simpler.  There's some subtlety to the way that this download gets hooked up as source to compile, but now that we know how to do that, this change lets us shrink the build logic by about a dozen lines.
> Download JLex into build subdir, not sources

- com.ibm.wala.cast/build.gradle
- com.ibm.wala.core/build.gradle
When a task is executing, it should not refer directly to the state of another task instance.  Doing so is incompatible with [configuration caching](https://docs.gradle.org/7.3/userguide/configuration_cache.html#config_cache:requirements:task_access).
Instead, each task should refer only to its own inputs and outputs, which in turn were defined during task *configuration* (not task *execution*).
> Avoid referring to other task during task execution

- com.ibm.wala.core.java11/build.gradle
- com.ibm.wala.core/build.gradle
- com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/callGraph/CallGraphTest.java
- com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/cha/SourceMapTest.java
- com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/shrike/FloatingPointsTest.java
- com.ibm.wala.core/src/testFixtures/java/com/ibm/wala/core/tests/util/WalaTestCase.java
In order for the `SourceMapTest` tests to pass, they must be able to see files inside the wala.core `testSubjects` source directory.  This PR adjusts the `testRuntimeOnly` path to include this directory, so the tests now pass.  This change enables removing the `analyzingJar` configuration that was added to skip the tests.
> Fix SourceMapTest so it can run on CI

- com.ibm.wala.cast.js.nodejs/build.gradle
This reverts commit a9157d8cce595798baffef04ae62e27a9e96c909.
Fixes #1033.  Unfortunately, I am not sure why I made this change in the first place, but it seems wrong to me now, as the built `wala.cast.js.nodejs` artifact won't work without these resources packaged in.  I may have been thinking about how we could package up `nodejs` for release to Maven Central (since we wouldn't want to re-distribute NodeJs code in such a case).  But since we still haven't done that, for now revert the change.
> Revert unpacking NodeJs code to test resources rather than main resources

- .idea/scopes/Java_Sources_as_Test_Subjects.xml
The "Java Sources as Test Subjects" IntelliJ IDEA files scope no longer included the download JLex sources after we moved those under `build/downloadJLex`, which in turn meant that we were no longer skipping certain inspections for these files.  This commit corrects that regression.
> Update an inspection scope for new JLex location

- com.ibm.wala.cast.js.html.nu_validator/build.gradle
- com.ibm.wala.cast.js.rhino/build.gradle
Turns out, IntelliJ IDEA doesn't like having a single directory be a content root for more than one module.  OK, we can easily configure this differently so that resources are copied from another task without adding reusing that other task's resource directories to multiple `SourceSet`s.
> Conform to IntelliJ IDEA restrictions on content roots

- com.ibm.wala.cast/build.gradle
- com.ibm.wala.cast/xlator_test/build.gradle
Instead of task A explicitly declaring that it `dependsOn` task B, the preferred style is for task A to declare that its inputs include task B's outputs (or some subset thereof).  The dependency between the tasks should be implicit, to be inferred by Gradle.
> Prefer to depend on tasks implicitly

- .github/workflows/continuous-integration.yml
- build.gradle
- wala-java.gradle
- wala-javadoc.gradle
Javadoc tasks only arise in Java-containing subprojects, with one important exception: the `aggregatedJavadocs` task in the top-level project.  Extract Javadoc-specific configuration into its own script plugin that we can reuse wherever we need it, even in projects that do not contain any Java code of their own.
Corrects [a regression](https://github.com/wala/WALA/runs/4424048891?check_suite_focus=true) that was introduced by pull request #1075.
I'm also adding `aggregatedJavadocs` to the standard tasks performed by all pre-merge GitHub CI jobs.  That should help us catch any future regressions of this task earlier, before merging to `master`.
> Extract Gradle logic for Javadoc tasks

- com.ibm.wala.core/build.gradle
As used here, it's enough to have a `Provider` for the `Task` that may eventually be created.  We don't need to force creation of that task right away.
> Don't force premature task instantiation

- wala-java.gradle
Our previous approach triggered deprecation warnings.  This new approach works fine, and should be compatible with some future Gradle 8.x release.  The important change seems to be to treat subprojects' Javadoc tasks' class paths as Gradle "artifacts", which are allowed to be produced and consumed in different (sub)projects.
Fixes #1079.
> Refine gathering of classpath for whole-project Javadoc

- buildSrc/src/main/groovy/java-compile-using-ecj.groovy
As [pointed out by `$RANDOM_INTERNET_PERSON`](https://github.com/TwoStone/gradle-eclipse-compiler-plugin/issues/13#issuecomment-995488621), this extra step is not needed.  Setting an executable in the fork options (which we do) is sufficient.
> Remove unnecessary Java toolchain de-configuration

- buildSrc/build.gradle
- buildSrc/src/main/groovy/verified-download.groovy
This release has [a few improvements](https://github.com/michel-kraemer/gradle-download-task/releases/tag/5.0.0) over the 4.x versions of this plugin. For example, it can download concurrently with other build tasks or downloads, and it shows the destination file name in the build progress message.
> Upgrade to Gradle download plugin v5.0.1

- build.gradle
- buildSrc/src/main/groovy/wala-subproject.gradle
For the best Gradle performance, we should always use Gradle task-configuration-avoidance APIs to configure tasks only when truly needed.
> Avoid configuring some tasks prematurely

- build.gradle
My recent attempt to avoid premature task configuration accidentally
broke the `aggregatedJavadocs` task.  This commit corrects that
regression.
> Restore generation of whole-project Javadocs

- build.gradle
`subprojects` can be invoked directly with a closure to apply to each subproject.
> Remove an unnecessary `.each`

- com.ibm.wala.core/build.gradle
As @liblit noted at https://github.com/wala/WALA/pull/1123#issuecomment-1246039827, this probably has no impact in terms of download integrity.  Still, using unencrypted http when not needed feels gross :-)  I tried switching the two other `http://` download URLs we have as well, but those didn't work with https.
> Switch download of bcel to https

- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/SSAPropagationCallGraphBuilder.java
in the comment, this `aubclasses` should be `subclasses` ?
> fix a typo in SSAPropagationCallGraphBuilder.java

- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/cha/CHACallGraph.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/impl/ExplicitCallGraph.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/impl/ExplicitPredecessorsEdgeManager.java
- com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/callGraph/CHACallGraphTest.java
Previously, computing the predecessors of each node in the `CHACallGraph` would require traversing all call graph nodes, a very expensive operation.  This PR changes the implementation to store the predecessors in a data structure from the beginning, making predecessor lookup fast.  This consumes more memory, but the benefits in running time are worth it.
> Cache all predecessors in CHACallGraph

- com.ibm.wala.core/src/main/java/com/ibm/wala/demandpa/alg/DemandRefinementPointsTo.java
This can arise in rare cases where the up-front call graph is a `CHACallGraph`, which may consider call sites not present after constructing IR (which does some dead-code elimination).  It's hard to create a test for this scenario, but the code changes are safe, in that they are adding nullness / array length checks that were not present before.
> Make demand-driven points-to analysis robust to missing call sites

- build.gradle
- buildSrc/src/main/groovy/wala-java.gradle
- com.ibm.wala.cast.java.ecj/src/main/java/com/ibm/wala/cast/java/translator/jdt/JDTJava2CAstTranslator.java
- com.ibm.wala.cast.java.test.data/build.gradle
- com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/ipa/callgraph/AstCallGraph.java
- com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/loader/AstMethod.java
- com.ibm.wala.core/build.gradle
- com.ibm.wala.core/src/main/java/com/ibm/wala/analysis/reflection/GetMethodContextSelector.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/cfg/exc/intra/OperatorUtil.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/core/tests/callGraph/CallGraphTestUtil.java
- com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/AnalysisScope.java
- com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/basic/FloydWarshallTest.java
- com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/collections/TwoLevelVectorTest.java
- com.ibm.wala.scandroid/src/main/java/org/scandroid/util/AndroidAnalysisContext.java
- com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeCT/SourcePositionTableReader.java
We only run Error Prone on JDK 11 builds, as recent Error Prone releases do not run on JDK 8.  We also disable WARNING level checks for now, to reduce the noise in the build output (we get hundreds of WARNING-level messages from Error Prone, which we should try to fix gradually).
This PR also fixes all ERROR-level issues reported by Error Prone.
> Add Error Prone to build

- com.ibm.wala.util/src/main/java/com/ibm/wala/fixpoint/IntSetVariable.java
Thank you for contributing to WALA!  Please see the contribution guidelines at https://github.com/wala/WALA/blob/master/CONTRIBUTING.md for information on code style and general guidelines for pull requests.
The filed `V` here may be `null`, also, other APIs of `IntSetVariable` will do a non-null check. So it seems consistent and safe to add a non-null check here.
Here we return false when `V` is null, it's straightforward to see that, when a points-to set is null, it contains nothing. Furthermore, the case that argument `IntSet instances` is null will be handled by the `V.containsAny`(see [here](https://github.com/wala/WALA/blob/6bd373104e4f4fca5888f0c2557bb427f76f1892/com.ibm.wala.util/src/main/java/com/ibm/wala/util/intset/BitVectorIntSet.java#L409)).
> Add a non-null check in IntSetVariable.containsAny()

- buildSrc/src/main/groovy/wala-java.gradle
WALA has many optimizations involving using == to check reference equality.  These optimizations may be unnecessary on modern JITs, but fixing these issues requires subtle changes that could introduce bugs.
> Disable ReferenceEquality check

- buildSrc/src/main/groovy/wala-java.gradle
- com.ibm.wala.cast.java.test.data/build.gradle
This will prevent new compiler warnings from creeping in.
> Compile with `-Werror`

- .github/workflows/continuous-integration.yml
We were getting various warnings about use of deprecated constructs before, e.g., here:
https://github.com/wala/WALA/actions/runs/3356903414
Switching to more recent versions of standard actions seems to fix these problems.
> Bump dependency versions for GitHub Actions configuration

- settings.gradle
These subprojects have no sources and no `build.gradle` files.  They define no useful tasks and provide nothing of value to the rest of the Gradle build configuration.  There's really no benefit in treating these subdirectories as subprojects.
Could these subdirectories be removed entirely?  Or are they important somehow when this project is opened in Eclipse instead of IntelliJ IDEA?
> Remove Gradle subprojects that don't do anything

- gradle.properties
I was seeing out-of-memory errors during concurrent Java compilation, specifically reporting depletion of the metaspace.  That space defaults to 256 MB, so let's enlarge it by 50% and see if the errors go away.
> Enlarge Gradle daemon's metaspace size limit

- com.ibm.wala.dalvik/build.gradle.kts
The Android SDK installer requires that `$JAVA_HOME` be set to some reasonable Java installation.  We shouldn't assume that's already set in the environment.  Instead, set it ourselves to whatever Java 11 SDK we're using for the rest of the build.
It may seem unlikely for a build to get this far with no `$JAVA_HOME`, but it is possible.  I recently set up IntelliJ IDEA to build WALA on a Windows machine that I had not previously used for Java development. IntelliJ IDEA downloaded and used a JVM automatically, which was quite helpful.  But that JVM was not installed system-wide and no `$JAVA_HOME` was set to its location.
> Set $JAVA_HOME for Android SDK installer

- build.gradle.kts
- buildSrc/src/main/kotlin/com/ibm/wala/gradle/aggregated-javadoc.gradle.kts
- buildSrc/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- buildSrc/src/main/kotlin/com/ibm/wala/gradle/javadoc.gradle.kts
- buildSrc/src/main/kotlin/com/ibm/wala/gradle/maven-eclipse-jsdt.gradle.kts
- buildSrc/src/main/kotlin/com/ibm/wala/gradle/subproject.gradle.kts
- com.ibm.wala.cast.js/build.gradle.kts
- com.ibm.wala.cast/build.gradle.kts
- com.ibm.wala.core/build.gradle.kts
- com.ibm.wala.ide.jsdt.tests/build.gradle.kts
- com.ibm.wala.ide.jsdt/build.gradle.kts
- com.ibm.wala.util/build.gradle.kts
The previous approach used cross-project task access, which is strongly discouraged and which actually broke when we converted the build from Gradle+Groovy to Gradle+Kotlin.  The new approach implemented here uses `Configuration`s to export relevant sets of Javadoc-related files and paths from each subproject.  The root project's can build dependencies on these so that the root `aggregatedJavadoc` task will have access to the right material when needed.
> Correct regression in aggregated Javadocs

- .github/workflows/continuous-integration.yml
- buildSrc/src/main/kotlin/com/ibm/wala/gradle/javadoc.gradle.kts
#1184 recently corrected a regression of the `aggregatedJavadocs` build task. Unfortunately, that fix caused a new regression in the "Publish snapshot" GitHub action. Here we correct the latter regression. We also improve our GitHub CI actions so that future regressions of this sort will be caught earlier.
> Fix regression of "Publish snapshot" GitHub action

- build.gradle.kts
Apache Commons IO snapshot releases have timestamped versions like `20030203.000550`.  We don't want these.  We only want stable releases, which have versions like `2.11.0`.
> Teach versions plugin to skip Commons IO snapshots

- .idea/kotlinc.xml
We recently upgraded to Kotlin 1.8.0 in the plugins configuration.  This change reflects that in IntelliJ IDEA's project metadata.
> Update IntelliJ IDEA Kotlin version

- buildSrc/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
Gradle's Kotlin API lets us use `publishing` and `java` with code blocks (closures) in which the appropriate object is already scoped as `this`. So there's no effect and no benefit from using `.run` here.
> Remove unnecessary uses of `.run`

- buildSrc/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
Resolves #1201.
Previously we had two nearly identical publications: `local` and `remote`.  `local` was unsigned, and was only intended for local installation, but we could not really enforce that very well. Conversely, `remote` was signed (for non-snapshots) and was only intended for remote installation, which we likewise could not enforce very well.
Now we just have a single `maven` publication.  We always attempt to sign this publication's artifacts.  However, signature misconfiguration is quietly allowed unless we are publishing a non-snapshot to a real Maven remote repository.  Near as I can tell, this is the idiomatic way to sign official remote releases but not sign local installations or snapshot releases.
**Note:** [this wiki …
> Publish test fixtures everywhere and simplify signature configuration

- build.gradle.kts
Kotlin's compiler doesn't know whether these calls to non-Kotlin code return nullable or non-nullable results.  Add explicit types to avoid some weak IntelliJ IDEA warnings.
> Resolve Kotlin warnings about inferred platform types

- CONTRIBUTING.md
- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- buildSrc/src/main/kotlin/com/ibm/wala/gradle/project.gradle.kts
- com.ibm.wala.cast.java.test.data/build.gradle.kts
- config/hooks/pre-commit
- gradle/libs.versions.toml
Spotless integrates nicely with the Java- and Kotlin-specific formatters we were already using, and also with Gradle.  Furthermore, it *appears* that Spotless may be ready for use with the Gradle configuration cache, which isn't the case for the Google Java formatter plugin we were using previously.  Thus, this change should move us a bit closer to #1206.
> Use Spotless for Java and Kotlin formatting

- .github/workflows/continuous-integration.yml
- build.gradle.kts
- gradle/libs.versions.toml
Also, require that ShellCheck pass for all macOS and Linux builds, not just builds where a `shellcheck` executable can be found.  If you want to build WALA, you need to install ShellCheck.  Fortunately, [ShellCheck is quite easy to
install](https://github.com/koalaman/shellcheck#installing) on all supported platforms.
Unfortunately, this ShellCheck plugin [does not work reliably on Windows](https://github.com/felipefzdz/gradle-shellcheck-plugin/issues/7). Until that bug is fixed, it's simpler to just skip ShellCheck on Windows.  We still run ShellCheck on macOS and Linux, so there's no risk of a bad shell script slipping into `master`.
> Use third-party Gradle plugin for ShellCheck

- com.ibm.wala.dalvik/build.gradle.kts
Previously, executing this task used [`copy`](https://docs.gradle.org/7.6/javadoc/org/gradle/api/Project.html#copy-org.gradle.api.Action-) and [`zipTree`](https://docs.gradle.org/7.6/javadoc/org/gradle/api/Project.html#zipTree-java.lang.Object-) from the current [`Project`](https://docs.gradle.org/7.6/javadoc/org/gradle/api/Project.html).  However, [the Gradle configuration cache disallows direct `Project` access from tasks' execution logic](https://docs.gradle.org/7.6/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution).  Instead, we need to use these two features as provided by [injectable services](https://docs.gradle.org/7.6/userguide/custom_gradle_types.html#service_injection).  In particular, …
> Make `extractSampleCup` compatible with configuration cache

- buildSrc/src/main/kotlin/com/ibm/wala/gradle/subproject.gradle.kts
This task depends on all download tasks.  But it doesn't read input from any of the files that those downloads create.
> The `downloads` task doesn't really have inputs

- buildSrc/src/main/kotlin/com/ibm/wala/gradle/VerifiedDownload.kt
- com.ibm.wala.cast.java.test.data/build.gradle.kts
- com.ibm.wala.cast.js.nodejs/build.gradle.kts
- com.ibm.wala.cast.js/build.gradle.kts
- com.ibm.wala.core/build.gradle.kts
- com.ibm.wala.dalvik/build.gradle.kts
Previously, the `VerifiedDownload` class provided convenience setters for each configurable `Property`.  However, the `dest` convenience setter used `project`, making it incompatible with the Gradle configuration cache if called during task execution.  So that setter needed to go away.  For consistency, let's just get rid of all of these convenience setters.  Instead, users of this task should use the `Property.set` methods of the individual properties.
> Remove `VerifiedDownload` convenience setters

- com.ibm.wala.cast/build.gradle.kts
When using the Gradle configuration cache, accessing a `Configuration` during task execution is discouraged or outright forbidden.  Instead, fetch the required file from that `Configuration` when configuring the task that uses it.
> Don't access a `Configuration` during task execution

- com.ibm.wala.cast/build.gradle.kts
Instead, fetch the required environment variables during task configuration.  Otherwise, we introduce an execution time access to the current `Project`, thereby making the task incompatible with the Gradle configuration cache.
That being said, even after this fix, this specific task won't get very far using the Gradle configuration cache, because the latter does not yet support native C++ compilation: gradle/gradle#13484, gradle/gradle#13485.
> Don't access environment variables during task execution

- build-logic/build.gradle.kts
We're picking up the right Kotlin plugin(s) already, and we don't actually have any Java code in this `build-logic` project.
> Skip loading an unnecessary plugin

- .github/workflows/continuous-integration.yml
- gradle/wrapper/gradle-wrapper.properties
These recommendations from [Protecting Project Integrity](https://blog.gradle.org/project-integrity) seem prudent.
We could go further, by recording and checking the expected SHA256 hash of every dependency.  But that seems like a large maintenance chore in exchange for reducing what is, in all likelihood, a very small risk of actual attack.
> Add countermeasures against supply chain attacks

- build-logic/src/main/kotlin/com/ibm/wala/gradle/VerifiedDownload.kt
- com.ibm.wala.core/build.gradle.kts
- gradle/libs.versions.toml
Also use some new features added to this plugin's latest release that let us avoid referring to the current `Project` during the action method of `VerifiedDownload` instances.  This change makes our `VerifiedDownload` tasks compatible with the Gradle configuration cache.
Unfortunately we also need to change how we set the inputs for a few tasks that postprocess downloads.  It's not clear to me whether this is due to a problem in our `VerifiedDownload` task, in the `gradle-download-task` plugin, or in Gradle itself.  I can live with this change for now, but it would be nice to understand it better.
> Update gradle-download-task plugin

- build-logic/src/main/kotlin/com/ibm/wala/gradle/cast/native.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
- com.ibm.wala.cast/cast/build.gradle.kts
- com.ibm.wala.cast/smoke_main/build.gradle.kts
- com.ibm.wala.cast/xlator_test/build.gradle.kts
If an incompatible task is scheduled to run, Gradle will warn about the incompatibility, but will not fail the build.  Instead, the configuration state will simply be discarded (not cached) when the build completes.
This approach seems like a reasonable compromise given that we use some standard Gradle tasks that are not yet compatible with the configuration cache.  It lets us still use the cache for builds that don't involve these incompatible tasks.
> Mark some kinds of tasks as incompatible with Gradle's configuration cache

- settings.gradle.kts
[We are not yet ready to enable the Gradle configuration cache by default.](https://github.com/orgs/wala/projects/1/views/2)  If someone turns it on locally, though, we should use it in [its stricter mode of behavior](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:stable). Per the Gradle documentation, "It is recommended to enable [`STABLE_CONFIGURATION_CACHE`] as soon as possible in order to be ready for when we remove the flag and make the linked features the default."
> Be more strict when caching Gradle configuration

- build.gradle.kts
- com.ibm.wala.cast.java.ecj/build.gradle.kts
- com.ibm.wala.ide.jdt.test/build.gradle.kts
- com.ibm.wala.ide.jdt/build.gradle.kts
- com.ibm.wala.ide.jsdt.tests/build.gradle.kts
- com.ibm.wala.ide.jsdt/build.gradle.kts
- com.ibm.wala.ide.tests/build.gradle.kts
- com.ibm.wala.ide/build.gradle.kts
- gradle/libs.versions.toml
- settings.gradle.kts
Fixes #1230 using advice from diffplug/goomph#203.
Unfortunately, as far as I can tell, the `libs.versions.toml` version catalog we use elsewhere is not available in `settings.gradle{,.kts}` files.  The generated version accessors are associated with the root `Project` instance rather than the global `Settings` instance.
> Fix Gradle configuration cache for `compileTestJava` tasks

- .github/workflows/continuous-integration.yml
After this change is approve and merged, we'll enable GitHub's beta "Require merge queue" branch protection rule for the `master` branch.
> Trigger CI workflow for new items in merge queue

- README-Gradle.md
These scripts were called `build.gradle` when they used Groovy. Now that they use Kotlin, they are called `build.gradle.kts`.
> Update name of Gradle build scripts

- .github/workflows/continuous-integration.yml
This reverts commit 2647cfb0033ae0fe2c8836491fb3ea9d0b06fa60.
I strongly believe that there should be some way to configure GitHub Actions to work _really_ well for us, including the beta merge queue feature. But…I just do not know how to do it. The more I read about GitHub Actions, triggers, jobs, cancellation, etc. the more confused I get.
I suspect that [our `concurrency` settings in `continuous-integration.yml`](https://github.com/wala/WALA/blob/d1b60945d006717b4dbab19b591ff6960bd62330/.github/workflows/continuous-integration.yml#L8-L10) might be interfering with the merge queue. But if I just remove that, then we're back to running wasteful jobs. We're also back to the potential for race conditions, as @msridhar pointed out in 1306282ca773d1b5d23526a38cf9150ff4ced605. So I don't know …
> Disable merge queue

- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/project.gradle.kts
- build.gradle.kts
I had not previously realized that Spotless offers a `kotlinGradle` configuration separate from its `kotlin` configuration.  Most of WALA is written in Java, with Kotlin only appearing in Gradle build scrips.  So for most of WALA, we want to configure Spotless for `java` and `kotlinGradle`, but not `kotlin`.  However, for the `build-logic` subproject, we want both `kotlin` and `kotlinGradle`, since this subproject uses Kotlin (and only Kotlin) for both its Gradle build scripts and for the code that those scripts are building.
Explicitly configure the top-level `check`, `spotlessCheck`, and `spotlessApply` tasks to depend on the same-named `build-logic` tasks. In general, tasks implicitly depend on same-named tasks in subprojects. But `build-logic` is an included build, not a subproject. …
> Clean up Spotless format checks

- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
If we're asking JUnit to exclude tests in the `SlowTests` category, then JUnit needs to be able to find the `SlowTests` interface.  That interface is implemented in the `testFixtures` source set of the `com.ibm.wala.core` subproject.
Without this fix, asking to exclude slow tests would fail in subprojects that have no slow tests and no other reason to depend on the `testFixtures` source set of the `com.ibm.wala.core` subproject.  For example, `./gradlew :com.ibm.wala.ide.tests:test -PexcludeSlowTests` would fail before this fix.  Now that command, correctly excluding the zero slow tests in the `com.ibm.wala.ide.tests` subproject.
> Ensure that JUnit can find `SlowTests` category

- com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/rhino/callgraph/fieldbased/test/AbstractFieldBasedTest.java
- com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/rhino/callgraph/fieldbased/test/TestFieldBasedCG.java
- com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/ipa/summaries/JavaScriptConstructorFunctions.java
- com.ibm.wala.cast.js/src/test/resources/tests/fieldbased/bad_new_function_call.js
Our code for handling `new Function(...)` calls tries to parse and analyze the body argument to the call if it is a string constant.  But, when that argument is malformed, previously we would crash.  This PR adds a null check to make WALA's behavior more robust for that case.
> Fix crash in JS CG construction for malformed calls to new Function

- gradle.properties
[As noted](https://github.com/wala/WALA/issues/1206#issuecomment-1436129956), we'll have some unsightly (but harmless) warnings in any builds that include artifact-signing tasks or native-code-compilation tasks. Resolves #1206.
> Enable Gradle's configuration cache by default

- build-logic/settings.gradle.kts
Set this included build's Gradle project name explicitly.  Unlike subprojects, an included build doesn't pick up its name from the project that included it.
Update an explanatory comment, which was still referring to `build-logic` as the `buildSrc` subproject.
Correct a typo in that same explanatory comment.
> Gradle settings tweaks for `build-logic` project

- build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
This used to happen implicitly, because `com.ibm.wala` was the root project's name and `com.ibm.wala.` was a prefix for all subproject names.  In #1247 we shortened the project name to just `wala` and removed the common `com.ibm.wala.` prefix from all subproject names.  So now we need to tweak things a bit to bring those prefixes back for publications.
Tested locally using the `publishAllPublicationsToFakeRemoteRepository` task, which actually just "publishes" to the local file system under `build/maven-fake-remote-repository`.  The published files now consist of:
* `com/ibm/wala/com.ibm.wala.*/maven-metadata.xml*`
* `com/ibm/wala/com.ibm.wala.*/1.6.1-SNAPSHOT/com.ibm.wala.*`
* `com/ibm/wala/com.ibm.wala.*/1.6.1-SNAPSHOT/maven-metadata.xml*`
The complete publication listing consists of: …
> Prefix publications with `com.ibm.wala`

- .mdlrc
- CONTRIBUTING.md
- README-Gradle.md
- README.md
- markdownlint-wala.rb
The `mdl` configuration describes how WALA's use of Markdown differs from the default style that `mdl` checks.  Specifically, we disable the following rules:
* [MD002](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md002---first-header-should-be-a-top-level-header): First header should be a top level header
* [MD041](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md041---first-line-in-file-should-be-a-top-level-header): First line in file should be a top level header
Nothing actually runs `mdl` to validate Markdown during a standard build.  I'd like to do that, but doing so would add nontrivial extra dependencies, given that `mdl` is written in Ruby.
> Tidy up Markdown and add `mdl` configuration

- .idea/runConfigurations/Build_with_configuration_cache.xml
This new "Build with configuration cache" run configuration performs the same Gradle tasks as our GitHub Actions CI job when run on Ubuntu, except that:
1. it excludes slow tests, and
1. it excludes tasks relating to native code and code signing that we already know are not compatible with the Gradle configuration cache.
This run configuration can be useful for identifying other configuration-cache problems that we still need to work on.
Noe that this run configuration is not actually used by any GitHub Actions CI job.  It's only here to be run manually, in an interactive IntelliJ IDEA session.
> Add IntelliJ IDEA run configuration for testing configuration cache

- README.md
Looks like Google isn't indexing GitHub wiki pages (maybe there's a `robots.txt?`). Switch to GitHub native wiki search.
> Fix link to site-specific search

- ide/src/main/java/com/ibm/wala/ide/classloader/EclipseSourceFileModule.java
The `getLocation()` API is returning `null`, resulting in an NPE. Use `getFullPath()` instead, which seems to work.
> Fix NPE in EclipseSourceFileModule ctor

- core/build.gradle.kts
- ide/tests/build.gradle.kts
The `:ide:tests:runIFDSExplorerExample` task uses the Java classloader to find a `com.ibm.wala.core.testdata_1.0.0.jar` resource. The `:core` subproject builds that resource using the `:core:collectTestData` task, and exports a consumable `collectTestDataJar` configuration containing it. However, we were not actually including that configuration's files in the `:ide:tests:runIFDSExplorerExample` task's classpath.  Now we do.
For extra subtlety, the `:ide:tests:runIFDSExplorerExample` task requires access to the complete `com.ibm.wala.core.testdata_1.0.0.jar` archive as a single file, not as a collection of files in which other resources can be found. Thus, the `collectTestDataJar` configuration should actually consist of the directory *containing* `com.ibm.wala.core.testdata_1.0.0.jar`, …
> Fix :ide:tests:runIFDSExplorerExample

- cast/js/src/main/java/com/ibm/wala/cast/js/translator/JSAstTranslator.java
This PR improves the source location used for the WALA IR instruction that performs a constructor invocation corresponding to a JS function statement.  Previously, the location used was the location of the closest enclosing function / script, which was both too coarse and led to duplicate locations when there were multiple function statements in a scope.  Now, we use the location of the function statement itself.
The implementation here is a bit hacky, but the source location code has complex invariants spread across multiple files and passes, so I think a local change is safest.
> Improve source locations for constructor calls for JS function statements

- build.gradle.kts
Workaround for diffplug/spotless#1644 using idea found at <https://github.com/diffplug/spotless/issues/1527#issuecomment-1409142798>.
> Work around Spotless conflict with Gradle configuration cache

- build.gradle.kts
- core/src/main/java/com/ibm/wala/ipa/callgraph/Entrypoint.java
- core/src/test/java/com/ibm/wala/core/tests/callGraph/StaticInterfaceMethodTest.java
When a static Interface method is selected as an Entrypoint, WALA creates an invokeinterface instead of an invokestatic instruction in FakeRootMethod. This will lead to an out-of-array read when resolving the receiver for an interface invocation.
A test can be simply an Android app generated by Android Studio for a Basic Activity demo (either Java or Kotlin). In my case, the problem occurs for handling:
40149 = invokeinterface < Application, Landroidx/window/layout/WindowMetricsCalculator, getOrCreate()Landroidx/window/layout/WindowMetricsCalculator; > @32353 exception:40150
And the exception is as follows:
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.lambda$getTargetsForCall$0(SSAPropa …
> Properly handle static interface methods as entrypoints

- gradle/libs.versions.toml
Just to stay up to date.  Also, Guava 32 fully fixed some CVEs: https://github.com/google/guava/releases/tag/v32.0.0
> Update to Guava 32.0.1

- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/eclipse-maven-central.gradle.kts
- build.gradle.kts
- cast/java/ecj/build.gradle.kts
- gradle/libs.versions.toml
- ide/build.gradle.kts
- ide/jdt/build.gradle.kts
- ide/jdt/test/build.gradle.kts
- ide/jsdt/build.gradle.kts
- ide/jsdt/tests/build.gradle.kts
- ide/tests/build.gradle.kts
A new `walaEclipseMavenCentral` Kotlin DSL extension allows configuring the diffplug MavenCentral plugin more easily by internalizing certain WALA-specific behaviors and adding a few convenience features.  See KDoc comments in
`build-logic/src/main/kotlin/com/ibm/wala/gradle/eclipse-maven-central.gradle.kts` for more details about what this new extension can do.
Resolves wala/WALA#1280.
> Simplify Maven Eclipse configuration

- gradle/libs.versions.toml
This is a minor update; none of the [new Kotlin 1.9.0 features](https://kotlinlang.org/docs/whatsnew19.html) are particularly interesting for our use of Kotlin to drive Gradle.
> Upgrade to Kotlin 1.9.0

- gradle/libs.versions.toml
Version 20220924 has [a known
vulnerability](https://devhub.checkmarx.com/cve-details/CVE-2022-45688).
Thank you for contributing to WALA!  Please see the contribution guidelines at https://github.com/wala/WALA/blob/master/CONTRIBUTING.md for information on code style and general guidelines for pull requests.
> Upgrade to newer JSON dependency

- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- cast/build.gradle.kts
- cast/java/build.gradle.kts
- cast/java/ecj/build.gradle.kts
- cast/js/build.gradle.kts
- cast/js/nodejs/build.gradle.kts
- cast/js/rhino/build.gradle.kts
- core/build.gradle.kts
- dalvik/build.gradle.kts
- gradle/libs.versions.toml
- ide/jdt/test/build.gradle.kts
- ide/jsdt/tests/build.gradle.kts
- ide/tests/build.gradle.kts
- util/build.gradle.kts
The tests themselves are still written using JUnit 4, so we're using JUnit 5's Vintage component to discover and run those tests.  Hooray for backward compatibility!
Eventually we can try porting JUnit 4 tests forward to JUnit 5, but this is a decent first step.
> Use JUnit 5 to find and run tests

- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- core/src/test/java/com/ibm/wala/core/tests/basic/ExtensionGraphTest.java
- gradle/libs.versions.toml
The migration was mostly automated by IntelliJ IDEA.  We're starting with just a single test class so that we have a clear demonstration of the kinds of changes that will later be applied more broadly.
It's also good to verify here, by manual inspection, that we are correctly running a mix of `core` tests from JUnit 5 (`ExtensionGraphTest`) and JUnit 4 (all the rest).  This confirms that it's OK to use multiple `TestEngine`s at the same time, which in turn confirms that it's OK to migrate tests from JUnit 4 to JUnit 5 incrementally rather than in one giant batch.
> Migrate one test class from JUnit 4 to JUnit 5

- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/SyncDuplicatorTests.java
- cast/js/rhino/src/main/java/com/ibm/wala/cast/js/examples/drivers/RunBuilder.java
- cast/js/rhino/src/test/java/com/ibm/wala/cast/js/rhino/callgraph/fieldbased/test/AbstractFieldBasedTest.java
- cast/js/src/testFixtures/java/com/ibm/wala/cast/js/test/TestArgumentSensitivity.java
- cast/js/src/testFixtures/java/com/ibm/wala/cast/js/test/TestSimpleCallGraphShape.java
- core/src/test/java/com/ibm/wala/core/tests/callGraph/Java7CallGraphTest.java
- core/src/test/java/com/ibm/wala/core/tests/callGraph/LambdaTest.java
These graph dumps add hundreds of megabytes to test logs, and presumably are manually inspected approximately never.  Let's turn them off. Anyone chasing a specific bug or regression can add more debug output in their local working tree, as needed, but there's no benefit to dumping all of this data on every automated test run.
Furthermore, I'm exploring an option for getting a nice test summaries after each GitHub actions workflow run.  Unfortunately, the tool I am considering has some limits on the sizes `CDATA` sections it can read in JUnit's XML test logs.  When our test logs include call graph dumps, several of them exceed these limits.
> Avoid printing many call graphs during testing

- cast/js/src/testFixtures/java/com/ibm/wala/cast/js/test/TestSimplePageCallGraphShape.java
- core/src/test/java/com/ibm/wala/core/tests/callGraph/ReflectionTest.java
Following up #1294 by removing a few more rarely examined graph dumps.
> Avoid printing some call graphs during testing

- cast/js/rhino/src/main/java/com/ibm/wala/cast/js/examples/drivers/RunBuilder.java
- cast/js/rhino/src/test/java/com/ibm/wala/cast/js/test/TestCPA.java
- cast/js/src/main/java/com/ibm/wala/cast/js/ipa/callgraph/JSSSAPropagationCallGraphBuilder.java
- cast/js/src/testFixtures/java/com/ibm/wala/cast/js/test/TestArgumentSensitivity.java
- cast/js/src/testFixtures/java/com/ibm/wala/cast/js/test/TestSimpleCallGraphShape.java
- cast/js/src/testFixtures/java/com/ibm/wala/cast/js/test/TestSimplePageCallGraphShape.java
- cast/src/main/java/com/ibm/wala/cast/ipa/callgraph/CAstCallGraphUtil.java
- cast/src/testFixtures/java/com/ibm/wala/cast/util/test/TestCallGraphShape.java
- core/src/testFixtures/java/com/ibm/wala/core/tests/shrike/DynamicCallGraphTestBase.java
Also, turn `com.ibm.wala.cast.ipa.callgraph.CAstCallGraphUtil.AVOID_DUMP` into a thread-local flag.  We should be able to turn it on or off without potential interference from different threads (e.g., during concurrent test execution) that have conflicting opinions.
> Remove more debugging output produced during testing

- cast/js/rhino/src/test/java/com/ibm/wala/cast/js/test/TestSimpleCallGraphShapeRhino.java
- core/src/test/java/com/ibm/wala/core/tests/cha/CodeDeletedTest.java
IntelliJ IDEA does not know how to migrate tests that are expected to fail, so these were ported by hand.
> Migrate a few test classes from JUnit 4 to JUnit 5

- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- cast/build.gradle.kts
- cast/java/ecj/build.gradle.kts
- cast/js/build.gradle.kts
- cast/js/nodejs/build.gradle.kts
- cast/js/src/testFixtures/java/com/ibm/wala/cast/js/test/TestSimpleCallGraphShape.java
- core/src/test/java/com/ibm/wala/core/tests/callGraph/KawaCallGraphTest.java
- core/src/testFixtures/java/com/ibm/wala/tests/util/SlowTests.java
- util/build.gradle.kts
These tests were all migrated by hand, including updating the Gradle logic for conditionally excluding them.
> Migrate slow tests from JUnit 4 to JUnit 5

- dalvik/build.gradle.kts
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/DroidBenchCGTest.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/droidbench/AliasingTest.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/droidbench/AndroidSpecificTest.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/droidbench/ArraysAndListsTest.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/droidbench/CallbacksTest.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/droidbench/EmulatorDetectionTest.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/droidbench/FieldAndObjectSensitivityTest.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/droidbench/GeneralJavaTest.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/droidbench/ImplicitFlowsTest.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/droidbench/InterAppCommunicationTest.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/droidbench/InterComponentCommunicationTest.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/droidbench/LifecycleTest.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/droidbench/ReflectionTest.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/droidbench/ThreadingTest.java
- gradle/libs.versions.toml
IntelliJ IDEA does not know how to migrate parameterized tests, so these test classes were migrated by hand.
> Migrate parameterized DroidBench tests from JUnit 4 to JUnit 5

- core/build.gradle.kts
- core/src/testFixtures/java/com/ibm/wala/core/tests/util/WalaTestCase.java
- gradle/libs.versions.toml
`WalaTestCase.justThisTest` offers a convenient way to run a single test class as a `main` application.  Previously this worked using JUnit 4; now it uses JUnit 5.
> Port WalaTestCase.justThisTest from JUnit 4 to JUnit 5

- core/build.gradle.kts
- core/src/test/java/com/ibm/wala/core/tests/arraybounds/ArrayboundsAnalysisTest.java
- core/src/test/java/com/ibm/wala/core/tests/arraybounds/PruneArrayOutOfBoundExceptionEdge.java
- core/src/test/java/com/ibm/wala/core/tests/exceptionpruning/ExceptionAnalysis2EdgeFilterTest.java
- core/src/test/java/com/ibm/wala/core/tests/exceptionpruning/ExceptionAnalysisTest.java
- gradle/libs.versions.toml
JUnit 5 itself offers only a very limited API for soft assertions. The rigid structure of this API does not align well with ways that WALA already uses soft assertions. AssertJ offers much more flexibility, if we're willing to pick that up as an additional dependency.
> Port soft assertions from JUnit 4 to JUnit 5 + AssertJ

- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- gradle/libs.versions.toml
All tests and test infrastructure have been migrated or ported to JUnit 5. Nothing remains that uses JUnit 4.
> Remove JUnit 4 dependency

- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
[`Project.getBuildDir()` will likely be deprecated in Gradle 8.3.](https://github.com/gradle/gradle/issues/20210)  Fortunately we only had a few remaining uses of this getter, all easily modernized.
> Stop using Project.getBuildDir()

- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/JavaIRTests.java
- cast/js/src/testFixtures/java/com/ibm/wala/cast/js/test/TestCorrelatedPairExtraction.java
- cast/js/src/testFixtures/java/com/ibm/wala/cast/js/test/TestForInBodyExtraction.java
- core/src/test/java/com/ibm/wala/core/tests/callGraph/Java7CallGraphTest.java
- core/src/test/java/com/ibm/wala/core/tests/callGraph/KawaCallGraphTest.java
- core/src/test/java/com/ibm/wala/core/tests/shrike/FloatingPointsTest.java
- core/src/testFixtures/java/com/ibm/wala/core/tests/shrike/DynamicCallGraphTestBase.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/DalvikCallGraphTestBase.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/DynamicDalvikComparisonJavaLibsTest.java
This change implements [a suggestion previously made by @msridhar](https://github.com/wala/WALA/pull/1301#discussion_r1275297725), not just in the class originally under review, but in several other test (and test fixture) classes as well.
> Let JUnit 5 manage tests' temporary files

- core/src/test/java/com/ibm/wala/core/tests/callGraph/CallGraphTest.java
- core/src/test/java/com/ibm/wala/core/tests/callGraph/DebuggingBitsetCallGraphTest.java
Empirically, these tests start but take a long time to finish on my personal laptop.  Some of them wedge the entire laptop, requiring that I cycle power to recover.  Granted, my laptop is a bit old and not the most powerful.  I think it's reasonable to skip a few tests to make development on this laptop feasible.  We still run the full test suite, including "slow"-tagged tests, in our GitHub Actions workflows.
> Tag additional slow tests

- gradle/libs.versions.toml
This update seems to fix the problem of #1278 on JDK 11, but not on JDK 17.  Still it's good to update.
> Update Gradle Goomph plugin

- cast/js/src/main/java/com/ibm/wala/cast/js/html/DomLessSourceExtractor.java
- core/src/main/java/com/ibm/wala/types/generics/MethodTypeSignature.java
- core/src/test/java/com/ibm/wala/types/generics/MethodTypeSignatureTest.java
Whoever wrote these `String.replaceAll` calls was a bit confused about how backslashes behave in the replacement text.  They actually behave less like backslashes in generic `String` literals, and more like backslashes in regular expressions.  For example, to replace a newline with a backslash followed by an `n`, the replacement text should be `\\\\n`, not `\\n`.
I've added a test for
`com.ibm.wala.types.generics.MethodTypeSignature.getArguments()` to affirm that my changes there leave us with an implementation that has the intended effects.  I haven't added a
`com.ibm.wala.cast.js.html.DomLessSourceExtractor.HtmlCallback.quotify(String)` test, though, because this method is buried too deep inside `protected` APIs that are difficult for a unit test to get access to.  Instead, to argue …
> Correct redundant escaping

- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
- cast/java/ecj/build.gradle.kts
- cast/java/test/data/build.gradle.kts
- cast/js/build.gradle.kts
- cast/js/nodejs/build.gradle.kts
- core/build.gradle.kts
We're intentionally using [an unstable Gradle Kotlin feature that allows direct `... = ...` assignment to `Property` instances](https://blog.gradle.org/simpler-kotlin-dsl-property-assignment). This feature may be considered unstable, but it's stable enough to have been [enabled by default since Gradle 8.2](https://docs.gradle.org/8.2.1/release-notes.html#simple-property-assignment-in-kotlin-dsl-enabled-by-default).
> Suppress warnings about unstable Gradle APIs

- build-logic/src/main/kotlin/com/ibm/wala/gradle/VerifiedDownload.kt
Leaking `this` before the constructor has completed can be dangerous in general, specifically if any methods are called or not-yet-initialized fields are used.  However, in the specific cases addressed here, the escaping `this` is merely recorded in fields of other objects for later use.  Members of `this` instance are not actually used during construction, so these escapes are safe.
> Suppress warnings about safe `this` leaks

- build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
These values are returned from Java code without nullability information.  Kotlin needs a little extra help to know whether those Java APIs can return `null` here or not.
> Add explicit Kotlin types

- shrike/src/main/java/com/ibm/wala/shrike/cg/Runtime.java
Setting a thread-local value to `null` is not the same as removing it. The former retains an entry mapping the current thread's value to `null` in a hidden global map.  The latter removes the current thread's entry entirely.
> Avoid memory leak for thread-local values

- cast/build.gradle.kts
- cast/smoke_main/build.gradle.kts
For precise caching, task inputs should be set during task configuration. If we use `doFirst` to postpone setting inputs until task execution, then we're preventing the cache from seeing an accurate representation of the task's real inputs.
> Avoid using doFirst to postpone setting task inputs

- cast/src/test/java/com/ibm/wala/cast/test/TestCAstTranslator.java
- core/src/testFixtures/java/com/ibm/wala/core/tests/shrike/DynamicCallGraphTestBase.java
`com.ibm.wala.cast.test.TestCAstTranslator.checkAssertions` is a `public` method that takes an argument of type
`com.ibm.wala.cast.test.TestCAstTranslator.TranslatorAssertions`.  The latter, therefore, needs to be `public` as well or else the checkAssertions` method can never be called.
Similarly,
`com.ibm.wala.core.tests.shrike.DynamicCallGraphTestBase.check` is a `protected` method that takes an argument of type
`com.ibm.wala.core.tests.shrike.DynamicCallGraphTestBase.EdgesTest`. The latter must at least have `protected` visibility too, or else the `check` method can never be called.
> Expose some types that are used in exposed APIs

- cast/js/src/testFixtures/java/com/ibm/wala/cast/js/test/TestLexicalModRef.java
- cast/src/test/java/com/ibm/wala/cast/test/TestCAstTranslator.java
- core/src/test/java/com/ibm/wala/core/tests/cha/MissingSuperTest.java
- core/src/test/java/com/ibm/wala/core/tests/slicer/SlicerTest.java
- core/src/testFixtures/java/com/ibm/wala/core/tests/shrike/DynamicCallGraphTestBase.java
For each of these assertions, if the check succeeds, then no diagnostic message will be formed and there's no need to call `toString`.
> Don't call toString unless actually needed

- README.md
The old URLs pointing to Sourceforge no longer work.
Fixes #1335
> Update URLs for tutorial slides

- README.md
Fixes #1340.  I recovered the logo from the Internet Archive!  New URL is https://wala.github.io/logos/WALA-banner.png.
> Update logo URL in README

- build-logic/src/main/kotlin/com/ibm/wala/gradle/CompileKawaScheme.kt
- build-logic/src/main/kotlin/com/ibm/wala/gradle/CreatePackageList.kt
- build-logic/src/main/kotlin/com/ibm/wala/gradle/VerifiedDownload.kt
Also conform to KDoc conventions: initial capital letter and trailing period for the first sentence.
> Use structured KDoc comments

- build-logic/src/main/kotlin/com/ibm/wala/gradle/CompileKawaScheme.kt
We don't need to inject a `Project` argument into this custom task's constructor.  The `JavaExec` superclass already has a perfectly good `getProject` method, and the value that it returns will already have been initialized before we are initializing this custom task's fields.
> Remove an unnecessary argument injection

- build-logic/src/main/kotlin/com/ibm/wala/gradle/NullAway.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/eclipse-maven-central.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/project.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/subproject.gradle.kts
I find these to be a bit more readable than `the<T>` and `configure<T>`.
> Use Kotlin DSL type-safe accessors

- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/project.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
- settings.gradle.kts
In addition to the usual automated tests, I've also manually verified that `./gradlew compile{,Test}Java` succeeds and correctly uses the configuration cache on an M2 macOS machine using either Java 11 or 17. So these changes should not cause a regression of #1230 or #1278.
> Upgrade to Spotless 2.43.1 and Spotless Gradle 6.23.3

- README.md
We previously had this on the WALA MediaWiki home page.
> Re-add YourKit acknowledgement to README

- core/build.gradle.kts
- dalvik/build.gradle.kts
- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/JVMLDalvikComparisonTest.java
- dalvik/src/test/java/com/ibm/wala/dalvik/test/util/Util.java
- gradle/libs.versions.toml
Updating to the latest R8 version lets us run the Dalvik tests on JDK 21.  We disable one check due to https://issuetracker.google.com/issues/316744331; we'll have to update R8 again once that is fixed.  We also needed to tweak how we construct the test jar for use with Dalvik.  My best guess is some classes caused issues with D8 before, but they no longer do so.  Finally, we performed some cleanup in `JVMLDalvikComparisonTest` to make failures easier to understand.
Fixes #1349
> Update R8 and enable Dalvik tests on JDK 21

- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
There's no need to explicitly use `project.` to get the current project when that project is already a Kotlin implicit receiver.
> Simplify access to current project's members

- build.gradle.kts
For some reason, IntelliJ IDEA's Kotlin support does not recognize that `destinationDir = ...` is a correct invocation of the `setDestinationDir` setter.  That works just fine when run in Gradle, but IntelliJ IDEA flags it as an error.  To keep IntelliJ IDEA happy, we can write this property assignment as an explicit setter call instead.
> Use an explicit setter to help IntelliJ IDEA

- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
We needed each of these dependency tweaks at some point, but everything builds fine now without them.
> Remove obsolete dependency tweaks

- util/src/main/java/com/ibm/wala/fixedpoint/impl/DefaultFixedPointSystem.java
Everything seems to compile fine with these changes.  Let's us get rid of a rawtypes suppression.
> Add some generic type arguments

- core/src/main/java/com/ibm/wala/analysis/reflection/GetMethodContextInterpreter.java
- core/src/test/java/com/ibm/wala/core/tests/callGraph/CallGraphTest.java
- core/src/testSubjects/java/simple/Example.java
Change how we access the `TypeAbstraction` in a `Context` to avoid a `ClassCastException`.
Fixes #1356
> Fix issue 1356

- build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
- build.gradle.kts
If we only need to fetch a single property, then we don't need to build an entire mutable `Map` that represents all properties.
> Simplify access to single properties

- cast/js/build.gradle.kts
The previous approach was needlessly complicated.  It was also flat-out wrong, since it turned a property (rather than a property's value) into a `String` for use in a `File` name.
> Correct and simplify access to Javadoc directory

- build-logic/src/main/kotlin/com/ibm/wala/gradle/NullAway.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- gradle/libs.versions.toml
- util/src/main/java/com/ibm/wala/util/graph/GraphSlicer.java
- util/src/main/java/com/ibm/wala/util/io/RtJar.java
NullAway's JSpecify mode does greater checking around generic types.  It is still experimental, but I will ensure that future fixes in JSpecify mode won't break WALA's build.
> Update to NullAway 0.10.24 and enable experimental JSpecify mode

- core/src/main/java/com/ibm/wala/ipa/cha/SeqClassHierarchyFactory.java
I believe this should address #1377.  See https://github.com/wala/WALA/commit/74b6c744926146ecaeaae5da5a74e18c95891fff.  For some reason at that point we decided not to use the type system to enforce use of a `ConcurrentHashMap` always.  In this spirit of trying not to break things I didn't do that here, but instead changed `SeqClassHierarchyFactory` to use `ConcurrentHashMap`.
Fixes #1377 (though we can reopen if the crash still happens)
> Switch to ConcurrentHashMap in SeqClassHierarchyFactory

- cast/src/main/java/com/ibm/wala/cast/ir/translator/AbstractScriptEntity.java
Fixes https://github.com/wala/WALA/issues/1378.
> Write `AbstractScriptEntity.toString()`  in terms of `getName()`

- ide/src/main/java/com/ibm/wala/ide/classloader/EclipseSourceDirectoryTreeModule.java
- ide/src/main/java/com/ibm/wala/ide/classloader/EclipseSourceFileModule.java
The removed null checks seem to happen further up the class hierarchy. Replace the static construction method with a public constructor. A lone private constructor basically makes it basically impossible to subclass.
> Refactor `EclipseSourceFileModule` to make it more extension-friendly

- .github/workflows/continuous-integration.yml
- build-logic/src/main/kotlin/com/ibm/wala/gradle/NullAway.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/cast/helpers.kt
- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- build.gradle.kts
- cast/cast/build.gradle.kts
- cast/smoke_main/build.gradle.kts
- cast/xlator_test/build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- gradlew.bat
Upgrade to Gradle 8.7, and fully support macOS on Apple Silicon, i.e., M1 CPUs. Specifically:
1. 327f3598a Remove customizations for macOS on Apple Silicon
1. b2a8f5d25 Add automated tests on Apple Silicon M1 CPU
1. 5a3f53410 Upgrade to Gradle 8.7
1. 5cdc1920b Use new API for updating collection properties
> Gradle 8.7 and Apple Silicon

- ide/src/main/java/com/ibm/wala/ide/classloader/EclipseSourceDirectoryTreeModule.java
When I subclassed `EclipseSourceDirectoryTreeModule`, I found myself needing to make a copy of `rootIPath` because it is private in the super class so that I could override a method. Overloading the `makeFile()` method now allows a bit more flexibility with the type of `FileModule` being created.
> Refactor `EclipseSourceDirectoryTreeModule` for more extensibility

- build.gradle.kts
Teach the `versions` plugin that we don't want to use prerelease versions of JUnit and SLF4J.
> Refine excluded dependency versions

- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
[This plugin](https://github.com/littlerobots/version-catalog-update-plugin) will help us clean and update the shared version catalog in `gradle/libs.versions.toml`.  It does not run automatically.  Instead, it provides a few helpful housekeeping tasks in the `version catalog update` group that we can run manually whenever convenient.
These updates were all discovered and applied using the `versionCatalogUpdate` task provided by the `nl.littlerobots.version-catalog-update` plugin.
For now, I'm considering only those upgrades that cause no test regressions and that require no changes to WALA's Java code.  There are a few additional update opportunities that currently cause regressions. We can consider those separately, along with any Java code changes needed to make them work correctly.
> Add and use version catalog updater

- core/src/main/java/com/ibm/wala/ipa/callgraph/AnalysisScope.java
- gradle/libs.versions.toml
The `versionCatalogUpdate` task found this upgrade opportunity, but we also needed to suppress a resource-leak diagnostic that the newer ECJ produces for some of our `JarFile`-manipulating code.
> Upgrade to newer ECJ release

- core/src/main/java/com/ibm/wala/ipa/callgraph/AnalysisScope.java
Replace a general `for (;;)` loop with something in a more functional style.  The restructured code also makes it more obvious that exactly one `List` instance is *always* put into the `Exclusions` key of the `res` `Map`.
> Modernize a `for` loop

- .github/workflows/continuous-integration.yml
v3 of this action is [deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) and will stop working in November 2024.
> Upgrade to v4 of `upload-artifact` GitHub action

- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- build.gradle.kts
- cast/build.gradle.kts
- cast/java/build.gradle.kts
- cast/java/ecj/build.gradle.kts
- cast/js/build.gradle.kts
- cast/js/html/nu_validator/build.gradle.kts
- cast/js/nodejs/build.gradle.kts
- cast/js/rhino/build.gradle.kts
- core/build.gradle.kts
- dalvik/build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- ide/build.gradle.kts
- ide/jdt/build.gradle.kts
- ide/jdt/test/build.gradle.kts
- ide/jsdt/build.gradle.kts
- ide/jsdt/tests/build.gradle.kts
- ide/tests/build.gradle.kts
- scandroid/build.gradle.kts
- shrike/build.gradle.kts
- util/build.gradle.kts
1. Add a dependency analysis plugin: 69ea56f834f6708ae24eae470b88b0f9ffc3d035
1. Add dependency checking to standard build checks: d1bd3356837db687ba9ffd46cde3bc27fc5aa8ee
1. Print dependency problems directly to build output: d76b1451627fb47d425f7a1aed4ebef9ffc1347c
Dependency problems are always reported in `build/reports/dependency-analysis/build-health-report.txt`.  With this property setting, they are also printed directly as build output.  The latter is more accessible when debugging dependency problems that are discovered during GitHub Actions builds.
1. Correct numerous dependency nits: d34b25621d4bcc5ee8a824893129c8a014dcb4b9
These tweaks correct all warnings provided by the excellent [dependency-analysis-gradle-plugin](https://github.com/autonomousapps/dependency-analysis-gradle- …
> Correct numerous small dependency nits

- core/src/test/java/com/ibm/wala/core/tests/cha/JunitEntrypointSupportTest.java
- core/src/testSubjects/java/junit/JunitTests.java
Additional test for https://github.com/wala/WALA/pull/1398.
> Add inner class test for JUnit entrypoints

- .github/workflows/continuous-integration.yml
This broke recently since I had to rotate my Sonatype credentials.  I think we should just disable it.  Building a snapshot locally is pretty easy, and it's generally not a great practice to add a dependence on a remote snapshot build that may change unexpectedly.  If anyone needs us to cut a release to get some change, they can just ask and we will do it.
> Remove snapshot uploading CI job

- cast/js/nodejs/build.gradle.kts
- core/build.gradle.kts
`Sync` tasks remove any files in the destination that were not actually copied from the source.  This feels safer than `Copy`, which is happy to retain leftover destination files.  Those leftover files might have been copied manually or by an earlier version of the build logic, either of which threatens reproducibility of a build.
> Prefer Gradle Sync tasks over Copy tasks

- core/build.gradle.kts
All the cool kinds encrypt these days.
Our only remaining `http:` URL is for OCaml-Java, which does not have an `https:` server.
https://github.com/wala/WALA/blob/1f29f627e1e4415279734bbe16331ee77aa62bb1/core/build.gradle.kts#L259
> Prefer HTTPS over HTTP

- .github/workflows/continuous-integration.yml
- core/build.gradle.kts
- core/src/test/java/com/ibm/wala/core/tests/slicer/SlicerTest.java
- core/src/testSubjects/java/slice/TestList.java
- shrike/src/main/java/com/ibm/wala/shrike/shrikeCT/ClassReader.java
We don't immediately crash on JDK 22 bytecodes, but new bytecode features have not been tested.
We modify the `TestList` test input to avoid a blowup when running `SlicerTest.testList`.  https://github.com/openjdk/jdk/commit/b62e774e6a531db934de04211724a2a8159d94db introduced calls to `String.format` from `Integer.parseInt`, which dramatically increased the number of reachable methods for the previous version of this test, which in turn led to very slow performance with the slicer.  Changing the test to use a `List<String>` and string constants removes this blowup.  (Whole-program analysis is fun!)
Fixes #1414
> Support building and running on JDK 22

- CONTRIBUTING.md
- README-Gradle.md
- README.md
- build.gradle.kts
- gradle/libs.versions.toml
I would rather use Spotless for these checks, for consistency with other format checkers that we already use.  [Spotless supports Markdown via flexmark](https://github.com/diffplug/spotless/tree/main/plugin-gradle#flexmark), but unfortunately [Spotless does not provide access to any of flexmark's configuration options](https://github.com/diffplug/spotless/issues/2183).  That would leave us with a Markdown linter that is too lenient for my tastes.  For example, [Spotless's flexmark configuration does not even restrict maximum line length](https://github.com/diffplug/spotless/issues/2167).
Resolves #818.
> Add a Markdown linter to `check` validation tasks

- gradle/libs.versions.toml
- util/build.gradle.kts
Also switch to an `api` dependence as suggested in [the docs](https://jspecify.dev/docs/using/#gradle).
> Update to JSpecify 1.0 annotations

- util/src/main/java/com/ibm/wala/util/collections/IteratorPlusOne.java
`next()` should throw a `NoSuchElementException` when there are no more elements.  Before it returned `null`.
> Fix a bug in IteratorPlusOne

- util/src/main/java/com/ibm/wala/util/collections/IteratorPlusTwo.java
Throw `NoSuchElementException` and `UnsupportedOperationException` in the right places.
> Fixes in IteratorPlusTwo

- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
- gradle/libs.versions.toml
Thoroughly testing these changes is delicate, since publishing to Maven Central involves an outside service, authentication, etc.  Instead, I've checked these changes in a limited manner:  I have verified that the `publishAllPublicationsToFakeRemoteRepository` task creates a local Maven repository containing exactly the same named files (in the same locations) as that task did before these changes.
> Publish using gradle-maven-publish plugin (#521)

- build-logic/settings.gradle.kts
- settings.gradle.kts
Use the latest 0.8.0 release of this plugin.
Use this plugin in the build-logic subproject, in case that subproject needs a Java toolchain that is not already installed system-wide or by the user.  In particular, this subproject compiles Kotlin for Java 11, but there's no guarantee that a Java 11 toolchain is already present.
> Update and broaden use of Java toolchain resolver

- .devcontainer/devcontainer.json
This configuration file is fairly simple: WALA bundles what it needs (e.g., Gradle) or downloads components at build time.  But there's no harm providing this metadata, and perhaps it will be helpful if someone wants to spin up a container that is ready to use for WALA development.  See [Development
Containers](https://containers.dev/) for more information.
Right now there is no automated validation of this file.  Potentially we could validate by running the Development Container CLI as `devcontainer read-configuration`.  But doing that requires the `devcontainer` command, which in turn is installed using `npm`.  This seems like a lot of extra material to bring in just to validate one file.  I'm going to hold off on that for now.
> Add development container configuration

- build-logic/src/main/kotlin/com/ibm/wala/gradle/cast/helpers.kt
The `FileCollection` provided by `outputs.files` already offers an `elementAt(Int)` method.  There's no need to convert this `FileCollection` to a `Sequence<File>` just for indexed access.
> Remove a redundant `asSequence()` call

- build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
In Kotlin script files (`*.kts`), we can use extension methods that various plugins add.  IntelliJ IDEA understands these too, so we still get static-type-aware autocompletion and other nice IDE features.
> Simplify access to various extensions

- build-logic/src/main/kotlin/com/ibm/wala/gradle/cast/helpers.kt
- build-logic/src/main/kotlin/com/ibm/wala/gradle/project.gradle.kts
- cast/cast/build.gradle.kts
- cast/smoke_main/build.gradle.kts
- cast/xlator_test/build.gradle.kts
- core/build.gradle.kts
The `cast/helpers.kt` script defines various functions that help us configure tasks that work with native code, such as natively compiled libraries.  I ported these from Groovy to Kotlin when I was still fairly new to the latter.  I've gotten better with Kotlin since then, and I now see how some of these functions could be simplified.
For example, judicious use of extension methods makes some functions easier to call, and also makes it easier for those functions' implementations to access properties of the receiver object.  In other cases, some function parameters can be computed from other parameters, thereby making the function easier to call correctly and harder to call incorrectly.
None of this constitutes a radical change to the suite of helper functions or how they are used to …
> Simplify helper functions for native code

- .github/workflows/continuous-integration.yml
This keeps us up to date and also moves us off of some deprecated Gradle-related actions.  
We also generate Javadoc on a more recent JDK version to get latest Javadoc improvements.
> Update CI actions and generate Javadoc on JDK 21

- .github/workflows/continuous-integration.yml
- core/src/main/java/com/ibm/wala/analysis/reflection/GetMethodContext.java
- core/src/main/java/com/ibm/wala/dataflow/IFDS/TabulationSolver.java
- core/src/main/java/com/ibm/wala/ipa/callgraph/impl/ExplicitCallGraph.java
- shrike/src/main/java/com/ibm/wala/shrike/shrikeCT/ClassReader.java
As usual, we verify existing tests don't crash on JDK 23 bytecodes, but we haven't added or tested support for any new features.
> Support JDK 23

- .github/workflows/continuous-integration.yml
- generate-latest-docs.sh
We need to pass `-Pcom.ibm.wala.jdk-version` in the `generate-latest-docs.sh` script.
Attempted to test locally, but the real test will be when this lands.
> Actually generate javadoc on latest JDK version

- build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
In attempting to cut release 1.6.7 I found that the artifact upload to Maven Central fails unless this is set.  I got the error thrown [here](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/ebe12f08dca6a29eaa08e7050d772e426f55d8cc/nexus/src/main/kotlin/com/vanniktech/maven/publish/nexus/Nexus.kt#L66-L70).  So, this property should be set to the name of the staging profile.
> Set the group property on the Maven publication

- .idea/scopes/Java_Sources_as_Test_Subjects.xml
- .idea/scopes/Sketchy_HTML.xml
These IntelliJ IDEA scopes broke way back in 941036214fe19f737b22fe57f190f7d1cebb4f16, but we didn't notice. Unfortunately I don't have a clever way to test for this regression without building some sort of custom IntelliJ IDEA plugin.
> Update IntelliJ IDEA scopes

- .idea/inspectionProfiles/No_Back_Sliding.xml
Java source code used as test inputs often does things in old or strange ways.  We usually want it that way.
> Suppress some inspections on test subject code

- dalvik/src/main/java/com/ibm/wala/dalvik/classLoader/DexUtil.java
Declaring and initializing a local variable in one `switch` branch, then using that same local variable in a different `switch` branch, is legal but confusing.  Even more so if the first switch branch returns rather than falling through.  Let's just not do that.
> Don't leak local variables between switch branches

- .idea/inspectionProfiles/No_Back_Sliding.xml
- .idea/ktfmt.xml
These are changes to project metadata that arise from opening the project in IntelliJ IDEA 2024.2.2.  None of these changes should affect the way that IDE actually behaves for this project.  Rather, these should all just reflect changes to some settings' default values, which in turn affects what's written out to settings files versus being used implicitly.
> IntelliJ IDEA 2024.2.2 settings churn

- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- gradle/libs.versions.toml
The `-parameters` flag is required for certain checks like [ArgumentSelectionDefectChecker](https://errorprone.info/bugpattern/ArgumentSelectionDefectChecker).  We enable a couple of those checks; they don't turn up any issues at the moment.  In a follow up I'd like to enable [BooleanParameter](https://errorprone.info/bugpattern/BooleanParameter) and auto-fix extant issues.
> Bump Error Prone to 2.35.1 and enable javac `-parameters` flag

- core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/ConcreteTypeKey.java
- util/src/main/java/com/ibm/wala/fixedpoint/impl/GeneralStatement.java
- util/src/main/java/com/ibm/wala/fixedpoint/impl/NullaryOperator.java
- util/src/main/java/com/ibm/wala/fixedpoint/impl/NullaryStatement.java
- util/src/main/java/com/ibm/wala/fixpoint/UnaryOperator.java
- util/src/main/java/com/ibm/wala/fixpoint/UnaryStatement.java
- util/src/main/java/com/ibm/wala/util/heapTrace/HeapTracer.java
We shouldn't describe a method as returning a "set of" anything when it actually returns an array.
We shouldn't describe a method as returning `true` or `false` when it actually returns a `byte`.
> Update Javadoc `@return`s that have deviated from code

- core/src/main/java/com/ibm/wala/core/util/strings/StringStuff.java
`StringBuilder` provides no benefit when building a `String` using just one concatenation.
> Replace some StringBuilders with String concatenation

- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/JavaIRTests.java
- core/src/test/java/com/ibm/wala/core/tests/callGraph/ReflectionTest.java
- core/src/test/java/com/ibm/wala/core/tests/ir/TypeAnnotationTest.java
- core/src/test/java/com/ibm/wala/core/tests/shrike/FloatingPointsTest.java
- core/src/testFixtures/java/com/ibm/wala/core/tests/ir/AnnotationTest.java
In particular, use `assertInstanceOf` instead of `assertTrue` on the result of an `instanceof` check.  If the assertion fails, `assertInstanceOf` will produce a more informative error message.
> Use more specialized JUnit assertions

- build-logic/src/main/kotlin/com/ibm/wala/gradle/cast/native.gradle.kts
- cast/cast/build.gradle.kts
- cast/smoke_main/build.gradle.kts
- cast/xlator_test/build.gradle.kts
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
Note that Gradle 8.11 finally includes configuration cache support for C++ applications and libraries. Yay!
> Upgrade to Gradle 8.11

- core/src/main/java/com/ibm/wala/types/generics/TypeSignature.java
- core/src/test/java/com/ibm/wala/types/generics/MethodTypeSignatureTest.java
I'm not sure why there was an assert fail before, but it's straightforward enough to do the right thing.
> Fix crash with void return type in TypeSignature code

- core/src/main/java/com/ibm/wala/core/util/ssa/SSAValueManager.java
- dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/androidModel/parameters/AndroidModelParameterManager.java
- dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/androidModel/parameters/ReuseParameters.java
- gradle/libs.versions.toml
- scandroid/src/main/java/org/scandroid/prefixtransfer/PrefixTransferGraph.java
The new [DuplicateBranches](https://errorprone.info/bugpattern/DuplicateBranches) check caught some cases which I tried to comment out more clearly for readability.
> Update to Error Prone 2.36.0

- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- gradle/libs.versions.toml
> Update Google Java Format to 1.25.0

- core/src/main/java/com/ibm/wala/types/generics/TypeSignature.java
- core/src/test/java/com/ibm/wala/types/generics/MethodTypeSignatureTest.java
We forgot to increment a variable, and we didn't handle all the primitive types.
> Fix a couple of bugs in parsing array type arguments in type signatures

- core/src/main/java/com/ibm/wala/types/generics/TypeSignature.java
- core/src/test/java/com/ibm/wala/types/generics/TypeSignatureTest.java
We generalize the method so it is useful for parsing either method argument types or generic type arguments.  (The latter required handling wildcards.)  Also factor out some common logic, and make the method public so it can be used from other projects.
> Further enhancements to `parseForTypeSignatures`

- cast/java/ecj/src/test/java/com/ibm/wala/cast/java/test/ECJJava15IRTest.java
- cast/java/test/data/src/test/java/javaonepointfive/SimpleEnums2.java
- cast/java/test/data/src/test/java/javaonepointfive/TypeInferencePrimAndStringOp.java
Creates ECJJava15IRTest similar to ECJJava17IRTest in order to test classes using javaonepointfive package.
> enable tests for java onepointfive

- gradle.properties
According to [Gradle's
documentation](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:usage:parallel), "Configuration cache storing and loading are done sequentially by default. Parallel storing and loading provide better performance, however not all builds are compatible with it."  Our build appears to be compatible, so let's turn this feature on.
That being said, I haven't actually noticed a significant change in build times.  This feature may affect WALA more in theory than in practice.
> Enable parallel configuration caching

- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- gradle/libs.versions.toml
Guava and Error Prone to latest, and use JDK 24 to compile code.  (We can't test WALA on JDK 24 under Gradle supports running on JDK 24.)
> Bump deps and version used for compiling Java

- .github/workflows/publish-test-results.yml
- cast/java/build.gradle.kts
- cast/java/ecj/build.gradle.kts
- cast/java/ecj/src/test/java/com/ibm/wala/cast/java/test/ECJJava15IRTest.java
- cast/java/ecj/src/test/java/com/ibm/wala/cast/java/test/ECJJava17IRTest.java
- cast/java/ecj/src/test/java/com/ibm/wala/cast/java/test/ECJTestComments.java
- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/IRTests.java
- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/Issue666Test.java
- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/Issue667Test.java
- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/JLexTest.java
- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/JavaIRTests.java
- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/SyncDuplicatorTests.java
Cleaned up `ECJJava15IRTest.java` by refactoring the tests to be parameterized to not rely on method name for running the tests. Also removed the `getTestName` from `IRTests` so the tests do not rely on that method to get the name of the test it should run. With this we pass in the name and tests can now be parameterized as well instead of relying on naming tests differently
> refactor: remove getTestName from IRTests.java so tests do not rely on method name

- build-logic/src/main/kotlin/com/ibm/wala/gradle/javadoc.gradle.kts
- build.gradle.kts
- cast/build.gradle.kts
- cast/java/ecj/build.gradle.kts
- cast/java/test/data/build.gradle.kts
- cast/js/build.gradle.kts
- cast/js/html/nu_validator/build.gradle.kts
- cast/js/rhino/build.gradle.kts
- cast/smoke_main/build.gradle.kts
- cast/xlator_test/build.gradle.kts
- core/build.gradle.kts
- dalvik/build.gradle.kts
- ide/tests/build.gradle.kts
[Gradle 8.14](https://docs.gradle.org/current/release-notes.html#configurations-are-initialized-lazily) allows dependency configurations to be "realized only when necessary."  "This change can lead to reduced configuration time and lower memory usage in some builds."
> Initialize Gradle dependency configurations lazily

- cast/java/ecj/src/test/java/com/ibm/wala/cast/java/test/ECJJava17IRTest.java
- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/JavaIRTests.java
Previously several parameterized tests used `List`s of items without custom `toString` methods.  Including these in test names led to generated test names like `java17IRTestName=CatchMultipleExceptionTypes, ca=[com.ibm.wala.cast.java.test.ECJJava17IRTest$3@6e576b5a]`, where the `6e576b5a` part varied randomly from one run to the next.  That nondeterminism, in turn, led to misleading claims of test churn in test reports.  For example, [this report](https://github.com/wala/WALA/pull/1495#issuecomment-2832598703) states that "this pull request removes 118 and adds 118 tests."  No tests were actually removed, though: 118 tests simply changed the hex digits in their names.
Now we customize the name template for some parameterized tests to omit items with nondeterministic `toString` results. …
> Make parameterized test names deterministic

- .idea/inspectionProfiles/No_Back_Sliding.xml
- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/JavaIRTests.java
- core/src/test/java/com/ibm/wala/core/tests/basic/PrimitivesTest.java
- core/src/test/java/com/ibm/wala/core/tests/cha/DupFieldsTest.java
JUnit 5's `assertEquals` method should be called with the _expected_ value _first_ and the _actual_ value _second_.
> Correct assertEquals argument order

- dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/DroidBenchCGTest.java
If the `TestParameters` class is going to be `protected`, then test-parameter generators that return streams of this type may as well be `protected` too:  nothing outside of this class hierarchy would be able to use those generators anyway.
> Limit visibility of test-parameter generators

- code-coverage-report/build.gradle.kts
When aggregating, automatically include every subproject that uses the `jacoco` plugin.  The logic for doing this works out quite nicely thanks to `PluginContainer::withId`.  That method executes an action immediately if a project has already loaded the plugin of interest, _or_ registers the action to run later if the project loads the plugin of interest later.  Thus, everything works as intended regardless of the order in which subprojects are configured.
> Simplify JaCoCo report aggregation

- code-coverage-report/build.gradle.kts
Previously we might only have been aggregating coverage from the root project's immediate subprojects. Now it should be clear that we're considering all projects regardless of nesting depth.
> Aggregate coverage from nested subprojects

- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
If we have two settings to tweak for `java.toolchain`, then it's slightly more concise to use one configuration block for both rather than repeating `java.toolchain` twice.
> Simplify Java toolchain configuration

- gradle/libs.versions.toml
- ide/build.gradle.kts
The previous version did not yet support Gradle 9.  This newer version does, and also detects a few dependency problems that the previous version missed.
Fixes #1521.
> Update `dependency-analysis` plugin

- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
Gradle 9 will no longer add a `junit-platform-launcher` dependency automatically unless a (sub)project uses Gradle's test suites feature. We're not using that feature yet, so we need to add this dependency ourselves.
Fixes #1523.
> Use explicit JUnit 5 launcher

- build-logic/src/main/kotlin/com/ibm/wala/gradle/JavaCompileUsingEcj.kt
- core/build.gradle.kts
Before this change, several project activities could trigger downloads of `ecj`, `java-cup`, and `ocamljava`.  For example, this would happen when running `./gradlew tasks` or when importing the WALA project into IntelliJ IDEA.  Those three downloads pulled in 101 MB of cacheable data, 95 MB of which was for `ocamljava` alone.  As [discussed elsewhere](https://github.com/wala/WALA/pull/1536#issuecomment-3014794567), it's undesirable to download anything more than what we actually need.
With this change applied, we no longer download `ecj` or any of the ad-hoc downloads (including `java-cup` and `ocamljava`) during `./gradle tasks` or during IntelliJ IDEA project import.  Thus, those actions now download 101 MB less than they did before.  Of course, these downloads will still happen …
> Delay some downloads until actually needed

- build-logic/src/main/kotlin/com/ibm/wala/gradle/cast/helpers.kt
- cast/build.gradle.kts
- cast/java/ecj/build.gradle.kts
- cast/smoke_main/build.gradle.kts
The more work we do during task _configuration_, the more likely we are to trigger something (e.g., a large dependency download) that won't actually be needed.  We should prefer to postpone work until task _execution_ time, since at that point we know that there is truly something to do.
> Postpone some work until after task configuration

- code-coverage-report/build.gradle.kts
- gradle.properties
[Configuration-on-demand](https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html) lets Gradle skip configuring subprojects that have no tasks to run.  For example, if you tell Gradle to build the `:util` subproject, then there is no need to configure the `:dalvik` subproject or even to compile the `:dalvik` subproject's build script.
> Enable Gradle configuration-on-demand

- code-coverage-report/build.gradle.kts
According to [Gradle's
documentation](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/PluginAware.html#getPlugins()), `getPlugins` is not deprecated, but it is preferred to use the plugin manager (via `getPluginManager`).
> Use `pluginManager`, not `plugins`

- cast/java/ecj/build.gradle.kts
Previously the `test` task had this dependence, but this prevented running the unit tests when the command-line driver was failing for some reason.
> Make check task depend on running ECJ command-line driver

- cast/smoke_main/build.gradle.kts
The `checkSmokeMain` task requires that `libxlator_test.so` be available when the test is run.  However, the `smoke_main` executable used for that test does not actually need to be linked with `libxlator_test.so`.
> Treat a library as a non-linked input file

- build-logic/src/main/kotlin/com/ibm/wala/gradle/cast/helpers.kt
- cast/cast/build.gradle.kts
- cast/smoke_main/build.gradle.kts
- cast/xlator_test/build.gradle.kts
Previously, we used various helper functions to add an rpath for each shared library.  However, it turns out to be simpler to manage rpaths all in one place.  Now, we wait until linker arguments are actually needed, and then compute _all_ required rpath arguments based on the _complete_ set of linked libraries.
A nice side effect of this change is that preparing to add these rpaths can work solely on a linker task _provider_, without requiring that the linker task be eagerly instantiated.
> Simplify rpath handling for Gradle native linking

- build-logic/src/main/kotlin/com/ibm/wala/gradle/cast/helpers.kt
- cast/cast/build.gradle.kts
- cast/smoke_main/build.gradle.kts
- cast/xlator_test/build.gradle.kts
Previously, this helper was an `AbstractLinkTask` extension method. However, we no longer do anything special with that link task.  Instead, we're operating on the enclosing `Project` instance and the target `CppBinary` instance.  So we can simplify a bit by turning `addJvmLibrary` into a `CppBinary` extension method instead of an `AbstractLinkTask` extension method.
A desirable side effect of this change is that we no longer force eager configuration of an `AbstractLinkTask` task in order to add the JVM library to its target binary.
> Treat `addJvmLibrary` as a `CppBinary` method

- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/project.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
- build-logic/src/main/kotlin/com/ibm/wala/gradle/subproject.gradle.kts
- cast/js/rhino/build.gradle.kts
- ide/tests/build.gradle.kts
Gradle subprojects inherit properties from their parent projects.  Thus, looking for a property on a project may involve a cascaded sequence of lookups, eventually reaching the root project.  Unfortunately, these cascades are incompatible with Gradle project isolation.  So we now use a different strategy for property lookups.  This strategy should give us the same results in the case of properties on the root Gradle project, which is all we really care about.  However, this strategy is (apparently) compatible with project isolation.
Before this change, trying to enable Gradle project isolation failed with 632 problems, in 10 distinct locations, having 82 distinct messages.  After this change, trying to enable Gradle project isolation fails with 451 problems, in 7 distinct locations, …
> Avoid cascaded project property lookups

- cast/java/ecj/build.gradle.kts
- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/IRTests.java
- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/JavaIRTests.java
Previously the tests in `cast/java/ect` could only run correctly from the `cast/cata/test/data` directory.  That made things brittle.  For example IntelliJ IDEA was not setting this directory correctly when running individual test methods.  Furthermore, Gradle did not know that these tests implicitly took all of
`cast/cata/test/data/src/testSubjects/java/**/*.java` as potential test inputs.
Now we formally declare those test-subject source files as inputs to the `cast/java/ect` subproject's tests.  Furthermore, we find these files using the JVM classpath, which means that we no longer depend on the current working directory being set to anything in particular.  If some test resource cannot be found, we now show a more informative diagnostic message.
> Find Java test inputs as classpath resources

- cast/java/ecj/src/test/java/com/ibm/wala/cast/java/test/ECJIssue666Test.java
- cast/java/ecj/src/test/java/com/ibm/wala/cast/java/test/ECJIssue667Test.java
- cast/java/ecj/src/test/java/com/ibm/wala/cast/java/test/ECJJava15IRTest.java
- cast/java/ecj/src/test/java/com/ibm/wala/cast/java/test/ECJJava17IRTest.java
- cast/java/ecj/src/test/java/com/ibm/wala/cast/java/test/ECJJavaIRTest.java
- cast/java/ecj/src/test/java/com/ibm/wala/cast/java/test/ECJSyncDuplicatorTest.java
- cast/java/ecj/src/test/java/com/ibm/wala/cast/java/test/ECJTestComments.java
- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/IRTests.java
- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/JavaIRTests.java
A `String` can represent just about anything.  For strings that represent paths in the filesystem, prefer to use `Path`.  It gives us a better API for file-related operations, makes argument-swapping errors less likely, and is simply a semantically richer description of what we are doing.
Ordinarily I would consider an API change like this as backward-incompatible and therefore requiring careful management of version numbers, deprecation, etc..  But the APIs affected by this change are all in test code.  So I think we can justify making this change without a lot of backward-compatibility ceremony.
> Prefer `Path` for filesystem paths

- cast/java/ecj/build.gradle.kts
The `:cast:java:ecj:run` task passes a directory full of source files as a command-line parameter to a subprocess.  We should probably assume that everything in that directory is a potential input to the task.
This same task can be cached, now that we have its inputs and outputs modeled correctly.  It takes about three seconds to run, but its outputs are small.  So we'd rather grab cached outputs if possible instead of computing them from scratch.
> Improve modeling and caching of a Gradle task

- core/src/main/java/com/ibm/wala/ipa/slicer/SDG.java
Both branches of this conditional end by returning an empty set.
> Factor out common `if`/`else` code

- .idea/inspectionProfiles/No_Back_Sliding.xml
Presumably the actual classes for each of these went away at some point in the past.  Whatever they were, they were apparently both enabled and enabled-by-default.  So removing them presumably does nothing bad.
> Deconfigure two unknown inspections

- .idea/develocity.xml
The Develocity plugin gives some of the features of a Gradle build scan (`--scan`) but can operate locally, with nice IntelliJ IDEA integration.  I've found the timeline view useful recently for finding opportunities to speed up our builds.
This additional fragment of project metadata will be used if the corresponding IntelliJ IDEA plugin is present.  If that plugin is absent, then this new configuration file will quietly do nothing.
> Add configuration for IntelliJ IDEA Develocity plugin

- cast/java/src/testFixtures/java/com/ibm/wala/cast/java/test/IRTests.java
- core/src/test/java/com/ibm/wala/core/tests/callGraph/CallGraphTest.java
- core/src/test/java/com/ibm/wala/core/tests/cha/DupFieldsTest.java
- core/src/test/java/com/ibm/wala/core/tests/cha/MissingSuperTest.java
`isTrue` asserts the truth of some opaque predicate that was already checked.  For better diagnostics when assertions fail, we prefer to use various higher-level checks that AssertJ provides.
> Improve assertions that use `isTrue`

- build-logic/src/main/kotlin/com/ibm/wala/gradle/xml-apis-ext.gradle.kts
- gradle/libs.versions.toml
- ide/build.gradle.kts
- ide/tests/build.gradle.kts
`org.eclipse.platform:org.eclipse.e4.ui.css.core:0.14.200`, `org.eclipse.platform:org.eclipse.e4.ui.css.swt.theme:0.14.200`, and `org.eclipse.platform:org.eclipse.e4.ui.css.swt:0.15.200` depend on `xml-apis:xml-apis-ext:1.0.0.v20230923-0644`, which is not available in any configured repository.
`org.eclipse.platform:org.eclipse.e4.ui.css.core:0.14.200` also depends on `org.apache.xmlgraphics:batik-css:1.17`, which depends on `xml-apis:xml-apis-ext:1.3.04`, which is available from Maven Central. So force that version of `xml-apis-ext` to be used instead of the missing one.
This tweak eliminates three failed attempts to download a POM for `xml-apis:xml-apis-ext:1.0.0.v20230923-0644` during build configuration. Avoiding those saves us a bit of time and useless network traffic.
> Stop trying to download a non-existent dependency

- build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
- gradle/libs.versions.toml
Fixes #1517
I followed the instructions at https://github.com/vanniktech/gradle-maven-publish-plugin/releases/tag/0.33.0.  I successfully uploaded a `SNAPSHOT` release with these changes, but we should cut a normal release after this lands to make sure that works.
> Migrate to Central Portal for publishing releases

- dalvik/build.gradle.kts
DroidBench unpacks into 119.4 MB of data.  That's quite a lot to unpack and write into one's filesystem.  However, it turns out that we only use the `apk` subdirectory in our tests: 24.5 MB.  The rest of this archive is stuff we never touch, including 94.9 MB in the `eclipse-project` subdirectory.
Instead of unpacking everything, let's just unpack the 24.5 MB we need from that `apk` subdirectory.  Storing and hashing the other 94.9 MB is a waste of compute time and disk space.
Before this change, `:dalvik:unpackDroidBench` took about 1.7 seconds to run when the archive had not already been extracted.  After this change, that time drops to 0.4 seconds.  When the task is already up-to-date, we don't see much change:  both before and after this change, Gradle takes about 0.1 seconds to …
> Extract only the subset of DroidBench that we use

- .github/workflows/continuous-integration.yml
When a PR enters GitHub's merge queue, the `merge_group` event triggers a CI run.  However, GitHub uses short-lived Git branches to manage the merge queue.  Adding a PR's commits to a merge queue branch creates a `push` event, which _also_ triggers a CI run.  These two runs have the same concurrency group, and our `cancel-in-progress` setting means that one will cancel the other.  If the `merge_group` run is canceled, then the job is evicted from the merge queue without having satisfied the checks that are required for merging.
The fix is to exclude the merge queue's short-lived Git branches from the `push` trigger.  Fortunately, that's easy to do based on these branches' names.
Big thanks to Arthur from GitHub Support for reviewing [our problem …
> Fix concurrency conflict on merge queue branches

- .idea/inspectionProfiles/No_Back_Sliding.xml
- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
- cast/java/ecj/src/main/java/com/ibm/wala/cast/java/translator/jdt/JDTJava2CAstTranslator.java
- cast/js/src/main/java/com/ibm/wala/cast/js/html/DomLessSourceExtractor.java
- cast/src/main/java/com/ibm/wala/cast/ipa/callgraph/CAstCallGraphUtil.java
- cast/src/main/java/com/ibm/wala/cast/util/BOMInputStreamFactory.java
- core/build.gradle.kts
- ide/jdt/src/main/java/com/ibm/wala/cast/java/translator/jdt/JDTSourceModuleTranslator.java
- ide/jdt/src/main/java/com/ibm/wala/ide/util/JdtUtil.java
Also, treat deprecated API uses as fatal errors in most Java compilations.  The only exception is for
`:core:compileTestSubjectsJava`, since those sources _intentionally_ use some deprecated APIs.
> Correct several uses of deprecated APIs

- .idea/inspectionProfiles/No_Back_Sliding.xml
- .idea/scopes/Java_Sources_as_Test_Subjects.xml
Update IntelliJ IDEA's definition of "Java Sources as Test Subjects" to reflect where these kinds of files are now found.
Turn off numerous IntelliJ IDEA inspection warnings in Java sources as test subjects.  We intentionally do questionable things in many of these files.
> Disable some IntelliJ IDEA warnings for Java test subjects

- .idea/inspectionProfiles/No_Back_Sliding.xml
- cast/js/src/main/java/com/ibm/wala/cast/js/loader/JavaScriptLoader.java
- cast/js/src/main/java/com/ibm/wala/cast/js/ssa/JSAbstractInstructionVisitor.java
- cast/src/main/java/com/ibm/wala/cast/analysis/typeInference/AstTypeInference.java
- cast/src/main/java/com/ibm/wala/cast/ipa/callgraph/AstSSAPropagationCallGraphBuilder.java
- cast/src/main/java/com/ibm/wala/cast/ipa/modref/AstModRef.java
- cast/src/main/java/com/ibm/wala/cast/ir/cfg/AstInducedCFG.java
- cast/src/main/java/com/ibm/wala/cast/ir/ssa/AstAbstractInstructionVisitor.java
- cast/src/main/java/com/ibm/wala/cast/ir/ssa/AstConsumeInstruction.java
- cast/src/main/java/com/ibm/wala/cast/ir/ssa/AstGlobalRead.java
- cast/src/main/java/com/ibm/wala/cast/ir/ssa/AstGlobalWrite.java
- cast/src/main/java/com/ibm/wala/cast/ir/ssa/AstLexicalRead.java
- cast/src/main/java/com/ibm/wala/cast/ir/ssa/AstLexicalWrite.java
- cast/src/main/java/com/ibm/wala/cast/ir/translator/AstTranslator.java
- core/src/main/java/com/ibm/wala/core/util/ssa/SSAValue.java
- core/src/main/java/com/ibm/wala/ipa/callgraph/impl/FakeRootClass.java
- core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/rta/DelegatingExplicitCallGraph.java
- core/src/main/java/com/ibm/wala/ipa/summaries/BypassSyntheticClass.java
- core/src/main/java/com/ibm/wala/ssa/SSAArrayStoreInstruction.java
- core/src/main/java/com/ibm/wala/ssa/SSAInstruction.java
- dalvik/src/main/java/com/ibm/wala/dalvik/classLoader/DexIClass.java
- dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/androidModel/AndroidModelClass.java
- shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/analysis/Verifier.java
- util/src/main/java/com/ibm/wala/fixpoint/BitVectorVariable.java
- util/src/main/java/com/ibm/wala/fixpoint/BooleanVariable.java
Each of these methods is equivalent to the corresponding superclass method.
> Remove redundant method overrides

- cast/src/main/java/com/ibm/wala/cast/ir/translator/AstTranslator.java
- core/src/main/java/com/ibm/wala/core/util/strings/StringStuff.java
- core/src/main/java/com/ibm/wala/demandpa/util/ArrayContents.java
- core/src/main/java/com/ibm/wala/ipa/callgraph/impl/FakeRootClass.java
- core/src/test/java/com/ibm/wala/core/tests/ptrs/MultiDimArrayTest.java
- core/src/test/java/com/ibm/wala/core/tests/ptrs/TypeBasedArrayAliasTest.java
- ide/jdt/src/main/java/com/ibm/wala/ide/util/JdtUtil.java
- util/src/main/java/com/ibm/wala/util/collections/ImmutableStack.java
- util/src/main/java/com/ibm/wala/util/collections/IteratorUtil.java
- util/src/main/java/com/ibm/wala/util/io/FileUtil.java
`static` methods don't use dynamic dispatch, so declaring such methods `final` doesn't do anything to boost performance.  Technically, `final` does prevent any subclass from declaring its own `static` method with the same name.  That restriction doesn't seem particularly useful, though.
> Remove useless `final` for `static` methods

- cast/java/build.gradle.kts
- cast/java/src/main/java/com/ibm/wala/cast/java/translator/JavaCAst2IRTranslator.java
- core/build.gradle.kts
- core/src/main/java/com/ibm/wala/core/util/strings/StringStuff.java
- core/src/main/java/com/ibm/wala/ipa/callgraph/AnalysisScope.java
- core/src/test/java/com/ibm/wala/util/io/FileProviderTest.java
- util/src/main/java/com/ibm/wala/util/io/FileUtil.java
These parameter annotations activate some nice coding-assistance features in JetBrains IDEs.  Annotating parameters rather than uses magnifies the impact:  one annotated parameter actives improved coding assistance wherever that parameter is used.
> Add semantic annotations to some `String` parameters

- scandroid/src/main/java/org/scandroid/util/DexDotUtil.java
There's no need to poll a subprocess while draining its stdout and stderr every half second.  We can simply redirect those streams into `/dev/null` (or the platform equivalent) and block waiting for the subprocess to terminate.
> Streamline using a silent, synchronous subprocess

- util/src/main/java/com/ibm/wala/util/processes/Launcher.java
The value returned by `InputStream.available()` is an _estimate_ of the number of bytes that can be read without blocking.  There is no guarantee that a subsequent `InputStream.read(byte[])` will receive exactly that same number of bytes.  Instead, we should use the `int` returned by the latter to tell us how many bytes were actually read.
Also, while we're here, make this method slightly more efficient by skipping UTF-8 encoding/decoding.  It's fine to just transfer raw bytes from one stream to another.
> Be more careful when printing some bytes in an input stream

- cast/js/nodejs/src/main/java/com/ibm/wala/cast/js/nodejs/NodejsRequiredSourceModule.java
- util/src/main/java/com/ibm/wala/util/io/Streams.java
`InputStream.readAllBytes()` does the same thing as `Stream.inputStream2ByteArray(InputStream)`, and has been available since Java 9.
`InputStream.readAllBytes()` also doesn't make the mistake of assuming that `InputStream.available()` predicts the exact number of bytes that the next `InputStream.read(byte[])` will receive. That is not guaranteed!
> Replace a utility for reading an `InputStream`

- util/src/main/java/com/ibm/wala/util/intset/MutableSparseLongSet.java
In these specific cases, the "common" code is just `return` statements.
> Lift common code out of some `if` statements

- cast/js/src/main/java/com/ibm/wala/cast/js/ipa/callgraph/ArgumentSpecialization.java
- core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/rta/DelegatingExplicitCallGraph.java
- core/src/main/java/com/ibm/wala/ssa/SSAInstruction.java
- core/src/main/java/com/ibm/wala/types/TypeReference.java
- dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/androidModel/parameters/ReuseParameters.java
- scandroid/src/main/java/org/scandroid/domain/FieldElement.java
- scandroid/src/main/java/org/scandroid/domain/InstanceKeyElement.java
- scandroid/src/main/java/org/scandroid/domain/ReturnElement.java
- scandroid/src/main/java/org/scandroid/flow/OutflowAnalysis.java
- scandroid/src/main/java/org/scandroid/flow/functions/TaintTransferFunctions.java
- scandroid/src/main/java/org/scandroid/util/DexDotUtil.java
- util/src/main/java/com/ibm/wala/util/collections/ImmutableStack.java
- util/src/main/java/com/ibm/wala/util/intset/BitVector.java
- util/src/main/java/com/ibm/wala/util/intset/FixedSizeBitVector.java
- util/src/main/java/com/ibm/wala/util/intset/OffsetBitVector.java
Each removed Boolean condition is redundant, as it is covered by some other subsequent condition.  For example, the `null` check is redundant in "`x != null && x instanceof C`", because "`null instanceof C`" always evaluates to `false`.
> Remove redundant conditions

- core/src/test/java/com/ibm/wala/core/tests/arraybounds/PruneArrayOutOfBoundExceptionEdge.java
- shrike/src/main/java/com/ibm/wala/shrike/shrikeCT/StackMapTableWriter.java
- util/src/main/java/com/ibm/wala/util/intset/OffsetBitVector.java
In `PruneArrayOutOfBoundExceptionEdge`, two `static final int` fields are initialized to "`0 + …`".  We want to keep them in this form.  A comment for each of those fields makes it clear that the value is "#[array access] + #[other]", and we would lose that structure if we simplified.  So we suppress IntelliJ IDEA's warnings for these fields.
In the other cases, though, the simplification seems natural and useful.
> Simplify some arithmetic expressions

- dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/androidModel/stubs/AndroidStartComponentTool.java
- dalvik/src/main/java/com/ibm/wala/dalvik/util/AndroidEntryPointLocator.java
- dalvik/src/main/java/com/ibm/wala/dalvik/util/AndroidEntryPointManager.java
Concatenation evaluates the complete log message regardless of whether it will actually be logged somewhere or not.  A parameterized message avoids that extra work if the logging level is set to discard the message anyway.
> Prefer parameterized log message over concatenation

- core/build.gradle.kts
CI jobs are failing due to `ftp.gnu.org` being down (from where we grab our Kawa download).  Using the mirror gateway for the download should be more robust.
> Try to use a Mirror for Kawa download

- build-logic/src/main/kotlin/com/ibm/wala/gradle/project.gradle.kts
The bug in question was fixed quite some time ago.
> Remove obsolete workaround for an Eclipse IDE bug

- core/src/main/java/com/ibm/wala/types/generics/TypeSignature.java
Pre-sizing the destination array used to be more efficient.  In OpenJDK 6 and later, though, the empty array style is as fast or faster.  The empty array style also avoids a potential race if the size of the `Collection` being copied might change due to activity in other threads.
> Avoid pre-sized array in `Collections.toArray()` call

- gradle/libs.versions.toml
Each of these entries is actually used.  But those uses are in `build-logic` code that must look these entries up as strings instead of using generated Kotlin bindings.  That causes IntelliJ IDEA to mistakenly think that these entries are unused.
We could turn off that IntelliJ IDEA warning entirely, for the whole catalog.  But the vast majority of catalog entries are used in standard, detectable ways.  It's still useful to have this warning in case any of those stop being used in the future.
> Suppress warnings for seemingly unused catalog entries

- .idea/inspectionProfiles/No_Back_Sliding.xml
We intentionally number all Markdown list items as "1.", rather than "1.", "2.", "3.", etc..  The rendered HTML will look the same either way but the style we use reduces Git churn when inserting or removing items.
> Allow non-sequential Markdown list numbering

- build-logic/src/main/kotlin/com/ibm/wala/gradle/CompileKawaScheme.kt
- build-logic/src/main/kotlin/com/ibm/wala/gradle/EclipseCompatibleJavaExtension.kt
- build-logic/src/main/kotlin/com/ibm/wala/gradle/JavaCompileUsingEcj.kt
Gradle's Kotlin DSL offers an overloaded `assign` operator that we can use to set a `Property`'s value instead of calling `Property.set`.
> Use overloaded assignment operator in Gradle Kotlin code

- cast/js/rhino/src/main/java/com/ibm/wala/cast/js/translator/RhinoToAstTranslator.java
`noteSourcePosition` expects a `WalkContext` formal parameter, but `WalkContext` is a `private` nested class.  Nobody outside of this class would ever be able to call `noteSourcePosition`.  So that method may as well be `private` too.
> Reduce visibility scope of a method

- .github/workflows/continuous-integration.yml
- build-logic/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
Previously Linux jobs included ECJ compilation but macOS and Windows jobs did not.  [Unfortunately, that allowed a Windows-specific ECJ compilation problem to go undetected.](https://github.com/wala/WALA/pull/1518)  In discussion of that fix, WALA maintainers agreed that testing ECJ on all platforms was advisable.
> Test ECJ builds on all platforms

- core/build.gradle.kts
Previously we were using an alpha OCaml-Java release that was eleven years old.  Now we're using an alpha release that is only ten years old. Progress!  :laughing:
> Upgrade OCaml-Java

- build-logic/src/main/kotlin/com/ibm/wala/gradle/CompileKawaScheme.kt
Previously the `outputDir` was added to the command line quite early, as soon as a `CompileKawaScheme` task was instantiated.  We should delay that, though, because it's entirely possible (and supported) for a task to change its output directory during task configuration.
> Postpone gathering Kawa compilation command line

- build-logic/src/main/kotlin/com/ibm/wala/gradle/AbstractCopyTask-dropTopDirectory.kt
- cast/js/build.gradle.kts
- dalvik/build.gradle.kts
Several Gradle `Copy` or `Sync` tasks need to strip off a single topmost directory from a source tree.  We can extract that logic into a helpful extension method that any `AbstractCopyTask` can use.
> Factor out dropping the top directory

- dalvik/build.gradle.kts
Previously, `installAndroidSdk` worked in two stages:
1. **Unpack** the downloaded Android SDK zip archive.
2. **Install** the Android SDK Using tools in that unpacked archive.
Now we split these into two separate tasks.  Unpacking is now the responsibility of a new `Sync` task named `unpackAndroidSdkInstaller`. Installing is done by `installAndroidSdk`, which is now an `Exec` task. The latter benefits from using the `Exec.useCurrentJavaHome()` extension method that we recently created.
> Break `installAndroidSdk` into two smaller tasks

- build.gradle.kts
This task takes ~5 seconds to run.  It's computationally intensive, not I/O intensive.  The input files that it consumes rarely change.  All of that makes this task an excellent use case for Gradle's build cache.
> Enable build cache for `lintMarkdown` task

- .github/workflows/continuous-integration.yml
Gradle's configuration cache is "a preferred mode" as of Gradle 9.0.0, and the Gradle developers "now recommend enabling Configuration Cache in most scenarios."  We've been using it in development builds for a _long_ time.  Let's enable it in GitHub CI/CD actions too.  That should help us discover regressions in our configuration cache compatibility before they make it into the `master` branch.
> Enable configuration cache in GitHub CI/CD actions

- build-logic/src/main/kotlin/com/ibm/wala/gradle/ad-hoc-download.kt
The Kotlin-specific `DependencyHandler.create` extension method that accepted separate parameters for group, name, version, classifier, and extension has been deprecated.  Instead we have to use the standard `DependencyHandler.create` method that combines all of these into [a single string](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.DependencyHandler.html#N16845).
> Avoid deprecated `DependencyHandler.create` method

- build-logic/src/main/kotlin/com/ibm/wala/gradle/publishing.gradle.kts
A `MavenPublication` has a `groupId`, which defaults to the current `Project`'s `group`.  A `MavenPublication` does not have a `group`, though.  So when we were assigning to `group` inside a `publishing` block, we were actually changing the `group` of the `Project`, which is not a sensible or useful thing to do here.
> Fix project vs. publication group confusion

- build-logic/src/main/kotlin/com/ibm/wala/gradle/project.gradle.kts
When registering a Gradle task that requires no special configuration, it's not necessary to include an empty `{}` configuration block.
> Discard an empty task configuration block

- build-logic/src/main/kotlin/com/ibm/wala/gradle/Exec-useCurrentJavaHome.kt
- build-logic/src/main/kotlin/com/ibm/wala/gradle/version-catalog.kt
A Kotlin function with a single-statement block body can use an expression body instead.
A Kotlin function that explicitly `null`-checks a platform type can use an explicit return type instead.
> Simplify some Kotlin functions

- settings.gradle.kts
We need this plugin to make certain platform-querying methods compatible with the Gradle configuration cache.  For example, without this plugin, the `useNativesForRunningPlatform()` call in `WalaMavenCentralReleaseConfigurerExtension` eventually does things that are incompatible with the configuration cache.
> Update a Gradle settings plugin
